In [1]:
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import numpy as np
import json
import gseapy as gp

In [2]:
DISEASE = input("Disease: ")
DISEASE_FOLDER = f"../output/{DISEASE}/"
RESULT_FOLDER = DISEASE_FOLDER + "leiden_results"

# Loading

In [3]:
def load(d):
    with open(f"../output/{d}/leiden_results/result_communities_selected.pkl", "rb") as f:
        communities = pickle.load(f)
    with open(f"../output/{d}/leiden_results/result_communities_HGNC_selected.pkl", "rb") as f:
        communities_HGNC = pickle.load(f)
    # with open(f"../output/{d}/leiden_results/result_graph.pkl", "rb") as f:
    #     graph = pickle.load(f)    
    with open(f"../output/{d}/gene_to_index_distinct.json", "r") as file:
        gene_to_index_distinct = json.load(file)
        
    return communities,communities_HGNC,gene_to_index_distinct

In [4]:
communities_selected,communities_HGNC_selected,gene_to_index_distinct = load(DISEASE)

# index to HGNC

In [5]:
index_to_gene_distinct = {v: u for (u,v) in gene_to_index_distinct.items()}

In [6]:
hgnc = pd.read_csv("../../Data/hgnc_complete_set.txt", sep="\t", dtype=str)
ncbi_to_hgnc_dict = dict(
    zip(
        hgnc["entrez_id"].dropna(),
        hgnc.loc[hgnc["entrez_id"].notna(), "symbol"]
    )
)

# Select top genes

In [7]:
# comm_idx = 0

In [8]:
def zscore(values):
    arr = np.asarray(values, dtype=float)
    if arr.size == 0:
        return arr

    mean = arr.mean()
    std = arr.std(ddof=0)

    if std == 0 or np.isnan(std):
        # no variation: all z-scores = 0
        return np.zeros_like(arr)

    return (arr - mean) / std

def community_central_genes_ranked(G, community_nodes, weight="weight"):
    C = set(community_nodes)
    H = G.subgraph(C).copy()                       # induced subgraph
    # within-community (weighted) degree
    k = {u: H.degree(u, weight=weight) for u in H}
    ks = np.array(list(k.values()), dtype=float)
    zscore_list = zscore(ks)
    Z = dict(zip(H,zscore_list))        # within-module degree z-score
    
    return Z

In [9]:
index_to_gene_distinct

{10: '1',
 11: '2',
 12: '3',
 13: '9',
 14: '10',
 15: '12',
 16: '13',
 17: '14',
 18: '15',
 19: '16',
 20: '18',
 21: '19',
 22: '20',
 23: '21',
 24: '22',
 25: '23',
 26: '24',
 27: '25',
 28: '26',
 29: '27',
 30: '28',
 31: '29',
 32: '30',
 33: '31',
 34: '32',
 35: '33',
 36: '34',
 37: '35',
 38: '36',
 39: '37',
 40: '38',
 41: '39',
 42: '40',
 43: '41',
 44: '43',
 45: '47',
 46: '48',
 47: '49',
 48: '50',
 49: '51',
 50: '52',
 51: '53',
 52: '54',
 53: '55',
 54: '56',
 55: '58',
 56: '59',
 57: '60',
 58: '69',
 59: '70',
 60: '71',
 61: '72',
 62: '81',
 63: '83',
 64: '86',
 65: '87',
 66: '88',
 67: '89',
 68: '90',
 69: '91',
 70: '92',
 71: '93',
 72: '94',
 73: '95',
 74: '97',
 75: '98',
 76: '100',
 77: '101',
 78: '102',
 79: '103',
 80: '104',
 81: '105',
 82: '107',
 83: '108',
 84: '109',
 85: '111',
 86: '112',
 87: '113',
 88: '114',
 89: '115',
 90: '116',
 91: '117',
 92: '118',
 93: '119',
 94: '120',
 95: '123',
 96: '124',
 97: '125',
 98: '126',
 99: '127',
 100: '128',
 101: '130',
 102: '131',
 103: '132',
 104: '133',
 105: '134',
 106: '135',
 107: '136',
 108: '137',
 109: '140',
 110: '141',
 111: '142',
 112: '143',
 113: '146',
 114: '147',
 115: '148',
 116: '150',
 117: '151',
 118: '152',
 119: '153',
 120: '154',
 121: '155',
 122: '156',
 123: '157',
 124: '158',
 125: '159',
 126: '160',
 127: '161',
 128: '162',
 129: '163',
 130: '164',
 131: '165',
 132: '166',
 133: '167',
 134: '172',
 135: '173',
 136: '174',
 137: '175',
 138: '176',
 139: '177',
 140: '178',
 141: '181',
 142: '182',
 143: '183',
 144: '185',
 145: '186',
 146: '187',
 147: '189',
 148: '190',
 149: '191',
 150: '196',
 151: '197',
 152: '199',
 153: '202',
 154: '203',
 155: '204',
 156: '205',
 157: '207',
 158: '208',
 159: '210',
 160: '211',
 161: '212',
 162: '213',
 163: '214',
 164: '215',
 165: '216',
 166: '217',
 167: '218',
 168: '219',
 169: '220',
 170: '221',
 171: '222',
 172: '223',
 173: '224',
 174: '225',
 175: '226',
 176: '228',
 177: '229',
 178: '230',
 179: '231',
 180: '238',
 181: '239',
 182: '240',
 183: '241',
 184: '242',
 185: '245',
 186: '246',
 187: '247',
 188: '248',
 189: '249',
 190: '250',
 191: '251',
 192: '257',
 193: '258',
 194: '259',
 195: '262',
 196: '265',
 197: '266',
 198: '267',
 199: '268',
 200: '269',
 201: '270',
 202: '271',
 203: '272',
 204: '273',
 205: '274',
 206: '275',
 207: '276',
 208: '277',
 209: '278',
 210: '279',
 211: '280',
 212: '283',
 213: '284',
 214: '285',
 215: '286',
 216: '287',
 217: '288',
 218: '290',
 219: '291',
 220: '292',
 221: '293',
 222: '301',
 223: '302',
 224: '303',
 225: '304',
 226: '305',
 227: '306',
 228: '307',
 229: '308',
 230: '309',
 231: '310',
 232: '311',
 233: '312',
 234: '313',
 235: '314',
 236: '316',
 237: '317',
 238: '318',
 239: '319',
 240: '320',
 241: '321',
 242: '322',
 243: '323',
 244: '324',
 245: '325',
 246: '326',
 247: '327',
 248: '328',
 249: '329',
 250: '330',
 251: '331',
 252: '332',
 253: '333',
 254: '334',
 255: '335',
 256: '336',
 257: '337',
 258: '338',
 259: '339',
 260: '341',
 261: '342',
 262: '343',
 263: '344',
 264: '345',
 265: '346',
 266: '347',
 267: '348',
 268: '350',
 269: '351',
 270: '353',
 271: '354',
 272: '355',
 273: '356',
 274: '357',
 275: '358',
 276: '359',
 277: '360',
 278: '361',
 279: '362',
 280: '363',
 281: '364',
 282: '366',
 283: '367',
 284: '368',
 285: '369',
 286: '372',
 287: '373',
 288: '374',
 289: '375',
 290: '377',
 291: '378',
 292: '379',
 293: '381',
 294: '382',
 295: '383',
 296: '384',
 297: '387',
 298: '388',
 299: '389',
 300: '390',
 301: '391',
 302: '392',
 303: '393',
 304: '394',
 305: '395',
 306: '396',
 307: '397',
 308: '398',
 309: '399',
 310: '400',
 311: '401',
 312: '402',
 313: '403',
 314: '405',
 315: '406',
 316: '407',
 317: '408',
 318: '409',
 319: '410',
 320: '411',
 321: '412',
 322: '414',
 323: '415',
 324: '416',
 325: '417',
 326: '419',
 327: '420',
 328: '421',
 329: '427',
 330: '429',
 331: '430',
 332: '432',
 333: '433',
 334: '434',
 335: '435',
 336: '438',
 337: '439',
 338: '440',
 339: '443',
 340: '444',
 341: '445',
 342: '454',
 343: '460',
 344: '462',
 345: '463',
 346: '466',
 347: '467',
 348: '468',
 349: '471',
 350: '472',
 351: '473',
 352: '474',
 353: '475',
 354: '476',
 355: '477',
 356: '478',
 357: '479',
 358: '480',
 359: '481',
 360: '482',
 361: '483',
 362: '486',
 363: '487',
 364: '488',
 365: '489',
 366: '490',
 367: '491',
 368: '492',
 369: '493',
 370: '495',
 371: '496',
 372: '498',
 373: '501',
 374: '506',
 375: '509',
 376: '513',
 377: '514',
 378: '515',
 379: '516',
 380: '517',
 381: '518',
 382: '520',
 383: '521',
 384: '522',
 385: '523',
 386: '525',
 387: '526',
 388: '527',
 389: '528',
 390: '529',
 391: '533',
 392: '534',
 393: '535',
 394: '537',
 395: '538',
 396: '539',
 397: '540',
 398: '541',
 399: '545',
 400: '546',
 401: '547',
 402: '549',
 403: '550',
 404: '551',
 405: '552',
 406: '553',
 407: '554',
 408: '558',
 409: '563',
 410: '566',
 411: '567',
 412: '570',
 413: '571',
 414: '572',
 415: '573',
 416: '575',
 417: '576',
 418: '577',
 419: '578',
 420: '579',
 421: '580',
 422: '581',
 423: '582',
 424: '583',
 425: '585',
 426: '586',
 427: '587',
 428: '590',
 429: '593',
 430: '594',
 431: '595',
 432: '596',
 433: '597',
 434: '598',
 435: '599',
 436: '602',
 437: '604',
 438: '605',
 439: '606',
 440: '607',
 441: '608',
 442: '610',
 443: '611',
 444: '613',
 445: '617',
 446: '618',
 447: '622',
 448: '623',
 449: '624',
 450: '627',
 451: '629',
 452: '631',
 453: '632',
 454: '633',
 455: '634',
 456: '635',
 457: '636',
 458: '637',
 459: '638',
 460: '639',
 461: '640',
 462: '641',
 463: '642',
 464: '643',
 465: '644',
 466: '645',
 467: '646',
 468: '648',
 469: '649',
 470: '650',
 471: '651',
 472: '652',
 473: '653',
 474: '654',
 475: '655',
 476: '656',
 477: '657',
 478: '658',
 479: '659',
 480: '660',
 481: '661',
 482: '662',
 483: '663',
 484: '664',
 485: '665',
 486: '666',
 487: '667',
 488: '668',
 489: '669',
 490: '670',
 491: '671',
 492: '672',
 493: '673',
 494: '675',
 495: '676',
 496: '677',
 497: '678',
 498: '680',
 499: '682',
 500: '683',
 501: '684',
 502: '685',
 503: '686',
 504: '687',
 505: '688',
 506: '689',
 507: '690',
 508: '694',
 509: '695',
 510: '696',
 511: '699',
 512: '701',
 513: '705',
 514: '706',
 515: '708',
 516: '710',
 517: '711',
 518: '712',
 519: '713',
 520: '714',
 521: '715',
 522: '716',
 523: '717',
 524: '718',
 525: '719',
 526: '720',
 527: '721',
 528: '722',
 529: '725',
 530: '726',
 531: '727',
 532: '728',
 533: '729',
 534: '730',
 535: '731',
 536: '732',
 537: '733',
 538: '734',
 539: '735',
 540: '738',
 541: '740',
 542: '741',
 543: '744',
 544: '745',
 545: '746',
 546: '747',
 547: '750',
 548: '752',
 549: '753',
 550: '754',
 551: '755',
 552: '757',
 553: '758',
 554: '759',
 555: '760',
 556: '761',
 557: '762',
 558: '763',
 559: '765',
 560: '766',
 561: '767',
 562: '768',
 563: '770',
 564: '771',
 565: '773',
 566: '774',
 567: '775',
 568: '776',
 569: '777',
 570: '778',
 571: '779',
 572: '780',
 573: '781',
 574: '782',
 575: '783',
 576: '784',
 577: '785',
 578: '786',
 579: '788',
 580: '789',
 581: '790',
 582: '793',
 583: '794',
 584: '795',
 585: '796',
 586: '797',
 587: '799',
 588: '800',
 589: '801',
 590: '805',
 591: '808',
 592: '810',
 593: '811',
 594: '813',
 595: '814',
 596: '815',
 597: '816',
 598: '817',
 599: '818',
 600: '819',
 601: '820',
 602: '821',
 603: '822',
 604: '823',
 605: '824',
 606: '825',
 607: '826',
 608: '827',
 609: '828',
 610: '829',
 611: '830',
 612: '831',
 613: '832',
 614: '833',
 615: '834',
 616: '835',
 617: '836',
 618: '837',
 619: '838',
 620: '839',
 621: '840',
 622: '841',
 623: '842',
 624: '843',
 625: '844',
 626: '845',
 627: '846',
 628: '847',
 629: '857',
 630: '858',
 631: '859',
 632: '860',
 633: '861',
 634: '862',
 635: '863',
 636: '864',
 637: '865',
 638: '866',
 639: '867',
 640: '868',
 641: '869',
 642: '871',
 643: '873',
 644: '874',
 645: '875',
 646: '881',
 647: '883',
 648: '885',
 649: '886',
 650: '887',
 651: '889',
 652: '890',
 653: '891',
 654: '892',
 655: '894',
 656: '895',
 657: '896',
 658: '898',
 659: '899',
 660: '900',
 661: '901',
 662: '902',
 663: '904',
 664: '905',
 665: '908',
 666: '909',
 667: '910',
 668: '911',
 669: '912',
 670: '913',
 671: '914',
 672: '915',
 673: '916',
 674: '917',
 675: '919',
 676: '920',
 677: '921',
 678: '922',
 679: '923',
 680: '924',
 681: '925',
 682: '926',
 683: '928',
 684: '929',
 685: '930',
 686: '931',
 687: '932',
 688: '933',
 689: '936',
 690: '938',
 691: '939',
 692: '940',
 693: '941',
 694: '942',
 695: '943',
 696: '944',
 697: '945',
 698: '946',
 699: '947',
 700: '948',
 701: '949',
 702: '950',
 703: '951',
 704: '952',
 705: '953',
 706: '954',
 707: '955',
 708: '956',
 709: '957',
 710: '958',
 711: '959',
 712: '960',
 713: '961',
 714: '962',
 715: '963',
 716: '965',
 717: '966',
 718: '967',
 719: '968',
 720: '969',
 721: '970',
 722: '971',
 723: '972',
 724: '973',
 725: '974',
 726: '975',
 727: '976',
 728: '977',
 729: '978',
 730: '983',
 731: '984',
 732: '987',
 733: '988',
 734: '989',
 735: '990',
 736: '991',
 737: '993',
 738: '994',
 739: '995',
 740: '996',
 741: '997',
 742: '998',
 743: '999',
 744: '1000',
 745: '1001',
 746: '1002',
 747: '1003',
 748: '1004',
 749: '1005',
 750: '1006',
 751: '1007',
 752: '1008',
 753: '1009',
 754: '1010',
 755: '1012',
 756: '1013',
 757: '1014',
 758: '1015',
 759: '1016',
 760: '1017',
 761: '1018',
 762: '1019',
 763: '1020',
 764: '1021',
 765: '1022',
 766: '1024',
 767: '1025',
 768: '1026',
 769: '1027',
 770: '1028',
 771: '1029',
 772: '1030',
 773: '1031',
 774: '1032',
 775: '1033',
 776: '1036',
 777: '1038',
 778: '1039',
 779: '1040',
 780: '1041',
 781: '1043',
 782: '1044',
 783: '1045',
 784: '1046',
 785: '1047',
 786: '1048',
 787: '1050',
 788: '1051',
 789: '1052',
 790: '1053',
 791: '1054',
 792: '1056',
 793: '1057',
 794: '1058',
 795: '1059',
 796: '1060',
 797: '1062',
 798: '1063',
 799: '1066',
 800: '1068',
 801: '1069',
 802: '1070',
 803: '1071',
 804: '1072',
 805: '1073',
 806: '1075',
 807: '1080',
 808: '1081',
 809: '1082',
 810: '1084',
 811: '1087',
 812: '1088',
 813: '1089',
 814: '1101',
 815: '1102',
 816: '1103',
 817: '1104',
 818: '1105',
 819: '1106',
 820: '1107',
 821: '1108',
 822: '1109',
 823: '1111',
 824: '1112',
 825: '1113',
 826: '1114',
 827: '1116',
 828: '1117',
 829: '1118',
 830: '1119',
 831: '1120',
 832: '1121',
 833: '1122',
 834: '1123',
 835: '1124',
 836: '1128',
 837: '1129',
 838: '1130',
 839: '1131',
 840: '1132',
 841: '1133',
 842: '1134',
 843: '1135',
 844: '1136',
 845: '1137',
 846: '1138',
 847: '1139',
 848: '1140',
 849: '1141',
 850: '1142',
 851: '1143',
 852: '1144',
 853: '1145',
 854: '1146',
 855: '1147',
 856: '1149',
 857: '1152',
 858: '1153',
 859: '1154',
 860: '1155',
 861: '1158',
 862: '1159',
 863: '1160',
 864: '1161',
 865: '1163',
 866: '1164',
 867: '1173',
 868: '1174',
 869: '1175',
 870: '1176',
 871: '1178',
 872: '1179',
 873: '1180',
 874: '1181',
 875: '1182',
 876: '1183',
 877: '1184',
 878: '1185',
 879: '1186',
 880: '1187',
 881: '1188',
 882: '1191',
 883: '1192',
 884: '1193',
 885: '1195',
 886: '1196',
 887: '1198',
 888: '1200',
 889: '1201',
 890: '1203',
 891: '1207',
 892: '1208',
 893: '1209',
 894: '1211',
 895: '1212',
 896: '1213',
 897: '1215',
 898: '1230',
 899: '1232',
 900: '1233',
 901: '1234',
 902: '1235',
 903: '1236',
 904: '1237',
 905: '1238',
 906: '1240',
 907: '1241',
 908: '1244',
 909: '1258',
 910: '1259',
 911: '1260',
 912: '1261',
 913: '1262',
 914: '1263',
 915: '1264',
 916: '1265',
 917: '1266',
 918: '1267',
 919: '1268',
 920: '1269',
 921: '1270',
 922: '1271',
 923: '1272',
 924: '1277',
 925: '1278',
 926: '1280',
 927: '1281',
 928: '1282',
 929: '1284',
 930: '1285',
 931: '1286',
 932: '1287',
 933: '1288',
 934: '1289',
 935: '1290',
 936: '1291',
 937: '1292',
 938: '1293',
 939: '1294',
 940: '1295',
 941: '1296',
 942: '1297',
 943: '1298',
 944: '1299',
 945: '1300',
 946: '1301',
 947: '1302',
 948: '1303',
 949: '1305',
 950: '1306',
 951: '1307',
 952: '1308',
 953: '1310',
 954: '1311',
 955: '1312',
 956: '1314',
 957: '1315',
 958: '1316',
 959: '1317',
 960: '1318',
 961: '1325',
 962: '1326',
 963: '1327',
 964: '1329',
 965: '1337',
 966: '1339',
 967: '1340',
 968: '1345',
 969: '1346',
 970: '1347',
 971: '1349',
 972: '1350',
 973: '1351',
 974: '1352',
 975: '1353',
 976: '1355',
 977: '1356',
 978: '1357',
 979: '1358',
 980: '1359',
 981: '1360',
 982: '1361',
 983: '1362',
 984: '1363',
 985: '1364',
 986: '1365',
 987: '1366',
 988: '1368',
 989: '1369',
 990: '1370',
 991: '1371',
 992: '1373',
 993: '1374',
 994: '1375',
 995: '1376',
 996: '1378',
 997: '1379',
 998: '1380',
 999: '1381',
 1000: '1382',
 1001: '1384',
 1002: '1385',
 1003: '1386',
 1004: '1387',
 1005: '1388',
 1006: '1389',
 1007: '1390',
 1008: '1392',
 1009: '1393',
 ...}

In [10]:
# zscore_dict = community_central_genes_ranked(graph,communities[comm_idx])

In [11]:
# zscore_dict = dict(sorted(zscore_dict.items(), key=lambda x: x[1], reverse=True))

In [12]:
# zscore_dict

In [13]:
# top_genes = [u for u,v in zscore_dict.items()][:3]

In [14]:
# top_genes

# Community deepdive

In [48]:
comm_idx = 0

In [49]:
comm_HGNC = communities_HGNC_selected[comm_idx]

In [50]:
len(comm_HGNC)

1124

In [51]:
important_terms = pd.read_csv(DISEASE_FOLDER + "important_terms.csv")

In [59]:
important_terms

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,Overlap (value)
0,0,1124,Mitochondrial Translation (GO:0032543),21/98,5.786204e-05,['cellular process'],GO_Biological_Process_2023,9.265339e-08,0.0,0.0,4.648232,7.527533e+01,MRPS25;MRPS11;MRPS23;MRPL16;MRPL27;MRPL38;MRPL...,0.214286
1,0,1124,Mitochondrial Translation Termination R-HSA-54...,20/82,1.970428e-06,['Metabolism of proteins'],Reactome_2022,1.847276e-08,0.0,0.0,5.497312,9.789046e+01,MRPS35;MRPS25;MRPS11;MRPS23;MRPL38;MRPL49;MRPL...,0.243902
2,0,1124,Mitochondrial Translation Initiation R-HSA-536...,20/82,1.970428e-06,['Metabolism of proteins'],Reactome_2022,1.847276e-08,0.0,0.0,5.497312,9.789046e+01,MRPS35;MRPS25;MRPS11;MRPS23;MRPL38;MRPL49;MRPL...,0.243902
3,0,1124,Mitochondrial Translation Elongation R-HSA-538...,20/82,1.970428e-06,['Metabolism of proteins'],Reactome_2022,1.847276e-08,0.0,0.0,5.497312,9.789046e+01,MRPS35;MRPS25;MRPS11;MRPS23;MRPL38;MRPL49;MRPL...,0.243902
4,0,1124,Mitochondrial Translation R-HSA-5368287,20/88,5.301778e-06,['Metabolism of proteins'],Reactome_2022,6.627222e-08,0.0,0.0,5.010656,8.282362e+01,MRPS35;MRPS25;MRPS11;MRPS23;MRPL38;MRPL49;MRPL...,0.227273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,9,383,Sensory Perception Of Smell (GO:0007608),187/230,2.066115e-297,['multicellular organismal process'],GO_Biological_Process_2023,5.903185e-299,0.0,0.0,434.306834,2.982374e+05,OR8I2;OR1C1;OR2M7;OR2M5;OR2M4;OR2M3;OR2M2;OR2T...,0.813043
857,9,383,Sensory Perception Of Chemical Stimulus (GO:00...,80/110,2.718961e-114,['multicellular organismal process'],GO_Biological_Process_2023,3.107384e-115,0.0,0.0,172.382838,4.545106e+04,OR10J1;OR8I2;OR1C1;OR10J5;OR8U9;OR8U8;OR2M4;OR...,0.727273
858,9,383,Olfactory transduction,367/440,0.000000e+00,['Sensory system'],KEGG_2021_Human,0.000000e+00,0.0,0.0,6140.965753,inf,OR7G2;OR7G1;OR8I2;OR9K2;OR11H2;OR11H1;OR11H4;O...,0.834091
859,9,383,Detection Of Chemical Stimulus Involved In Sen...,118/139,1.506544e-186,['response to stimulus'],GO_Biological_Process_2023,1.291324e-187,0.0,0.0,415.512668,1.788066e+05,OR2M7;OR2M5;OR2M4;OR2M3;OR2M2;OR2T12;OR2T10;OR...,0.848921
860,9,383,Sensory Perception R-HSA-9709957,360/616,0.000000e+00,['Sensory Perception'],Reactome_2022,0.000000e+00,0.0,0.0,1183.756793,inf,OR7G2;OR7G1;OR8I2;OR9K2;OR11H2;OR11H1;OR11H4;O...,0.584416

In [52]:
go_df_filtered = important_terms[important_terms["Community Index"] == comm_idx]

In [53]:
go_df_filtered = go_df_filtered.sort_values(by = ["Adjusted P-value"], ascending = [True])

In [54]:
go_df_filtered

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,Overlap (value)
1,0,1124,Mitochondrial Translation Termination R-HSA-54...,20/82,0.000002,['Metabolism of proteins'],Reactome_2022,1.847276e-08,0.0,0.0,5.497312,97.890458,MRPS35;MRPS25;MRPS11;MRPS23;MRPL38;MRPL49;MRPL...,0.243902
2,0,1124,Mitochondrial Translation Initiation R-HSA-536...,20/82,0.000002,['Metabolism of proteins'],Reactome_2022,1.847276e-08,0.0,0.0,5.497312,97.890458,MRPS35;MRPS25;MRPS11;MRPS23;MRPL38;MRPL49;MRPL...,0.243902
3,0,1124,Mitochondrial Translation Elongation R-HSA-538...,20/82,0.000002,['Metabolism of proteins'],Reactome_2022,1.847276e-08,0.0,0.0,5.497312,97.890458,MRPS35;MRPS25;MRPS11;MRPS23;MRPL38;MRPL49;MRPL...,0.243902
4,0,1124,Mitochondrial Translation R-HSA-5368287,20/88,0.000005,['Metabolism of proteins'],Reactome_2022,6.627222e-08,0.0,0.0,5.010656,82.823620,MRPS35;MRPS25;MRPS11;MRPS23;MRPL38;MRPL49;MRPL...,0.227273
0,0,1124,Mitochondrial Translation (GO:0032543),21/98,0.000058,['cellular process'],GO_Biological_Process_2023,9.265339e-08,0.0,0.0,4.648232,75.275331,MRPS25;MRPS11;MRPS23;MRPL16;MRPL27;MRPL38;MRPL...,0.214286
5,0,1124,Mitochondrial Gene Expression (GO:0140053),22/103,0.000058,['cellular process'],GO_Biological_Process_2023,4.896699e-08,0.0,0.0,4.632318,77.971735,MRPS25;MRPS11;MTERF4;MRPS23;MRPL16;MRPL27;MRPL...,0.213592

In [55]:
go_df_filtered[go_df_filtered["Gene_set"] == "Reactome_2022"]

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,Overlap (value)
1,0,1124,Mitochondrial Translation Termination R-HSA-54...,20/82,0.000002,['Metabolism of proteins'],Reactome_2022,1.847276e-08,0.0,0.0,5.497312,97.890458,MRPS35;MRPS25;MRPS11;MRPS23;MRPL38;MRPL49;MRPL...,0.243902
2,0,1124,Mitochondrial Translation Initiation R-HSA-536...,20/82,0.000002,['Metabolism of proteins'],Reactome_2022,1.847276e-08,0.0,0.0,5.497312,97.890458,MRPS35;MRPS25;MRPS11;MRPS23;MRPL38;MRPL49;MRPL...,0.243902
3,0,1124,Mitochondrial Translation Elongation R-HSA-538...,20/82,0.000002,['Metabolism of proteins'],Reactome_2022,1.847276e-08,0.0,0.0,5.497312,97.890458,MRPS35;MRPS25;MRPS11;MRPS23;MRPL38;MRPL49;MRPL...,0.243902
4,0,1124,Mitochondrial Translation R-HSA-5368287,20/88,0.000005,['Metabolism of proteins'],Reactome_2022,6.627222e-08,0.0,0.0,5.010656,82.823620,MRPS35;MRPS25;MRPS11;MRPS23;MRPL38;MRPL49;MRPL...,0.227273

In [56]:
print(go_df_filtered[["Term","Adjusted P-value","Overlap"]].to_latex(longtable=True,index=False,caption=f"Enriched terms for {DISEASE} Community {comm_idx}",label=f"appendix:{DISEASE}_{comm_idx}_term", float_format="%.2e",column_format="p{8cm}cc",))

\begin{longtable}{p{8cm}cc}
\caption{Enriched terms for BIPOLAR Community 0} \label{appendix:BIPOLAR_0_term} \\
\toprule
Term & Adjusted P-value & Overlap \\
\midrule
\endfirsthead
\caption[]{Enriched terms for BIPOLAR Community 0} \\
\toprule
Term & Adjusted P-value & Overlap \\
\midrule
\endhead
\midrule
\multicolumn{3}{r}{Continued on next page} \\
\midrule
\endfoot
\bottomrule
\endlastfoot
Mitochondrial Translation Termination R-HSA-5419276 & 1.97e-06 & 20/82 \\
Mitochondrial Translation Initiation R-HSA-5368286 & 1.97e-06 & 20/82 \\
Mitochondrial Translation Elongation R-HSA-5389840 & 1.97e-06 & 20/82 \\
Mitochondrial Translation R-HSA-5368287 & 5.30e-06 & 20/88 \\
Mitochondrial Translation (GO:0032543) & 5.79e-05 & 21/98 \\
Mitochondrial Gene Expression (GO:0140053) & 5.79e-05 & 22/103 \\
\end{longtable}

In [57]:
list(go_df_filtered["Term"])

['Mitochondrial Translation Termination R-HSA-5419276',
 'Mitochondrial Translation Initiation R-HSA-5368286',
 'Mitochondrial Translation Elongation R-HSA-5389840',
 'Mitochondrial Translation R-HSA-5368287',
 'Mitochondrial Translation (GO:0032543)',
 'Mitochondrial Gene Expression (GO:0140053)']

In [58]:
list(go_df_filtered["Category"].unique())

["['Metabolism of proteins']", "['cellular process']"]