In [1]:
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import numpy as np
import json
import gseapy as gp

In [2]:
DISEASE = input("Disease: ")
DISEASE_FOLDER = f"../output/{DISEASE}/"
RESULT_FOLDER = DISEASE_FOLDER + "leiden_results"

# Loading

In [3]:
def load(d):
    with open(f"../output/{d}/leiden_results/result_communities_selected.pkl", "rb") as f:
        communities = pickle.load(f)
    with open(f"../output/{d}/leiden_results/result_communities_HGNC_selected.pkl", "rb") as f:
        communities_HGNC = pickle.load(f)
    # with open(f"../output/{d}/leiden_results/result_graph.pkl", "rb") as f:
    #     graph = pickle.load(f)    
    with open(f"../output/{d}/gene_to_index_distinct.json", "r") as file:
        gene_to_index_distinct = json.load(file)
        
    return communities,communities_HGNC,gene_to_index_distinct

In [4]:
communities_selected,communities_HGNC_selected,gene_to_index_distinct = load(DISEASE)

# index to HGNC

In [5]:
index_to_gene_distinct = {v: u for (u,v) in gene_to_index_distinct.items()}

In [6]:
hgnc = pd.read_csv("../../Data/hgnc_complete_set.txt", sep="\t", dtype=str)
ncbi_to_hgnc_dict = dict(
    zip(
        hgnc["entrez_id"].dropna(),
        hgnc.loc[hgnc["entrez_id"].notna(), "symbol"]
    )
)

# Community deepdive

In [7]:
comm_idx = 7

In [8]:
important_terms = pd.read_csv(DISEASE_FOLDER + "important_terms.csv")

In [9]:
important_terms

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,Overlap (value)
0,0,1120,Ubiquitin Ligase-Substrate Adaptor Activity (G...,16/44,5.987088e-08,['molecular adaptor activity'],GO_Molecular_Function_2023,7.919429e-10,0.0,0.0,9.757764,204.488891,KLHDC2;KLHDC3;FEM1A;KLHL25;PEF1;FEM1B;PDCD6;FB...,0.363636
1,0,1120,Cysteine-Type Deubiquitinase Activity (GO:0004...,21/98,4.122296e-06,['catalytic activity'],GO_Molecular_Function_2023,8.724436e-08,0.0,0.0,4.666143,75.846065,OTUD4;OTUB2;USP36;USP47;USP25;USP48;USP6;USP49...,0.214286
2,1,1129,G Protein-Coupled Peptide Receptor Activity (G...,39/77,8.638396e-27,['molecular transducer activity'],GO_Molecular_Function_2023,1.872823e-28,0.0,0.0,17.732665,1132.140880,OPRD1;OXTR;VIPR1;VIPR2;NPR1;MLNR;OPRL1;FPR3;GP...,0.506494
3,1,1129,Anterior/Posterior Pattern Specification (GO:0...,28/59,3.548246e-17,['multicellular organismal process'],GO_Biological_Process_2023,8.213533e-20,0.0,0.0,15.455744,679.216871,GATA4;HHEX;SIX2;HOXA3;HOXC5;HOXC4;HES3;HOXC9;H...,0.474576
4,1,1129,Voltage-Gated Potassium Channel Complex (GO:00...,30/73,1.127232e-16,['protein-containing complex'],GO_Cellular_Component_2023,6.515793e-19,0.0,0.0,11.952515,500.510224,DPP10;KCNG1;HCN4;KCNC1;LRRC38;KCNA1;KCNC4;KCNA...,0.410959
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
672,10,238,Exocytosis (GO:0006887),10/86,1.063367e-06,"['localization', 'cellular process']",GO_Biological_Process_2023,7.565454e-08,0.0,0.0,11.360803,186.284096,NSF;RAB10;SNAP47;VAMP7;TMED10;STX19;MIA3;SNAP2...,0.116279
673,10,238,Golgi Cisternae Pericentriolar Stack Reorganiz...,5/14,2.396149e-06,['Cell Cycle'],Reactome_2022,4.196644e-07,0.0,0.0,47.098236,691.581561,GOLGA2;RAB1A;RAB1B;GORASP1;USO1,0.357143
674,10,238,Protein Localization To Endoplasmic Reticulum ...,4/6,3.833169e-06,['localization'],GO_Biological_Process_2023,2.878665e-07,0.0,0.0,168.888889,2543.596563,SEC16B;SEC16A;GBF1;MIA3,0.666667
675,10,238,"Antigen Presentation: Folding, Assembly, Pepti...",6/28,4.461827e-06,['Immune System'],Reactome_2022,8.066580e-07,0.0,0.0,23.205329,325.579263,SEC23A;SEC24B;SEC24A;SEC24D;SEC24C;SEC31A,0.214286
676,10,238,Recycling Endosome Membrane (GO:0055038),8/70,8.274170e-06,['cellular anatomical structure'],GO_Cellular_Component_2023,1.787629e-06,0.0,0.0,11.051893,146.267612,VAMP8;GGA3;RAB14;RAB12;RAB35;RAB11A;RAB8B;RAB11B,0.114286

In [10]:
go_df_filtered = important_terms[important_terms["Community Index"] == comm_idx]

In [11]:
go_df_filtered = go_df_filtered.sort_values(by = ["Adjusted P-value"], ascending = [True])

In [12]:
go_df_filtered

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,Overlap (value)
306,7,754,VEGFA-VEGFR2 Pathway R-HSA-4420097,62/93,3.506578e-64,['Signal Transduction'],Reactome_2022,6.786926e-66,0.0,0.0,55.534682,8333.291043,CYFIP2;PRR5;CYFIP1;NCKAP1;AHCYL1;NCF1;ITGB3;BR...,0.666667
307,7,754,EPH-Ephrin Signaling R-HSA-2682334,60/91,1.211928e-61,['Developmental Biology'],Reactome_2022,2.475982e-63,0.0,0.0,53.588361,7725.095772,EPHB6;ARPC1B;ARPC1A;ITSN1;CLTB;WASL;ACTG1;SYNG...,0.659341
308,7,754,Fcgamma Receptor (FCGR) Dependent Phagocytosis...,58/87,5.199764e-60,['Immune System'],Reactome_2022,1.118229e-61,0.0,0.0,55.221264,7750.080509,CYFIP2;CYFIP1;NCKAP1;AHCYL1;WIPF1;ARPC1B;WIPF2...,0.666667
309,7,754,Bacterial invasion of epithelial cells,54/77,5.189699e-58,['Infectious disease: bacterial'],KEGG_2021_Human,2.192831e-59,0.0,0.0,64.474658,8708.419783,ITGB1;ARPC1B;ARPC1A;ARPC5L;CLTB;ILK;PIK3CD;WAS...,0.701299
310,7,754,ErbB signaling pathway,53/85,8.316038e-53,['Signal transduction'],KEGG_2021_Human,4.685092e-54,0.0,0.0,45.396844,5574.514944,GSK3B;CDKN1B;PIK3CD;CBLB;AREG;ELK1;CRKL;NCK2;N...,0.623529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
548,7,754,Negative Regulation Of Signaling (GO:0023057),9/28,5.939201e-06,['biological regulation'],GO_Biological_Process_2023,5.316013e-07,0.0,0.0,12.224868,176.617211,BRAP;PPP3CA;PTPN1;PPP3CB;MPIG6B;SRMS;ERBB3;INP...,0.321429
549,7,754,CD28 Dependent Vav1 Pathway R-HSA-389359,6/12,7.373627e-06,['Immune System'],Reactome_2022,2.140730e-06,0.0,0.0,25.721925,335.783360,CDC42;LCK;FYN;PKN1;ARHGEF7;VAV1,0.500000
550,7,754,Positive Regulation Of Microtubule Polymerizat...,9/29,8.201933e-06,['biological regulation'],GO_Biological_Process_2023,7.451303e-07,0.0,0.0,11.613020,163.856308,PAK1;OCLN;CAV3;FES;RAC1;MAPT;MET;GIT1;CDK5R1,0.310345
551,7,754,Synthesis Of PIPs At Plasma Membrane R-HSA-166...,11/51,8.340729e-06,['Metabolism'],Reactome_2022,2.439439e-06,0.0,0.0,7.108546,91.869023,INPP5D;INPPL1;PTEN;PIK3R3;PIK3R2;PIP5K1B;PIK3R...,0.215686
552,7,754,Mitogen-Activated Protein Kinase Binding (GO:0...,8/23,8.386598e-06,['binding'],GO_Molecular_Function_2023,1.165383e-06,0.0,0.0,13.748704,187.841128,DUSP10;MAPK7;MAPKAPK3;MAPKAPK2;PRKG2;NFATC1;PT...,0.347826

In [13]:
go_df_filtered[go_df_filtered["Gene_set"] == "Reactome_2022"]

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,Overlap (value)
306,7,754,VEGFA-VEGFR2 Pathway R-HSA-4420097,62/93,3.506578e-64,['Signal Transduction'],Reactome_2022,6.786926e-66,0.0,0.0,55.534682,8333.291043,CYFIP2;PRR5;CYFIP1;NCKAP1;AHCYL1;NCF1;ITGB3;BR...,0.666667
307,7,754,EPH-Ephrin Signaling R-HSA-2682334,60/91,1.211928e-61,['Developmental Biology'],Reactome_2022,2.475982e-63,0.0,0.0,53.588361,7725.095772,EPHB6;ARPC1B;ARPC1A;ITSN1;CLTB;WASL;ACTG1;SYNG...,0.659341
308,7,754,Fcgamma Receptor (FCGR) Dependent Phagocytosis...,58/87,5.199764e-60,['Immune System'],Reactome_2022,1.118229e-61,0.0,0.0,55.221264,7750.080509,CYFIP2;CYFIP1;NCKAP1;AHCYL1;WIPF1;ARPC1B;WIPF2...,0.666667
311,7,754,RAC2 GTPase Cycle R-HSA-9013404,53/87,1.128707e-51,['Signal Transduction'],Reactome_2022,2.912792e-53,0.0,0.0,42.721994,5167.989784,ITGB1;CYFIP1;NCKAP1;DOCK3;TRIO;NCF1;ARHGAP1;BR...,0.609195
313,7,754,NRAGE Signals Death Thru JNK R-HSA-193648,43/57,2.700996e-48,['Signal Transduction'],Reactome_2022,8.712890e-50,0.0,0.0,83.079767,9385.060271,TRIO;ARHGEF26;MAGED1;RASGRF2;ITSN1;ARHGEF10L;K...,0.754386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,7,754,Cell Junction Organization R-HSA-446728,15/86,2.479720e-06,['Cell-Cell communication'],Reactome_2022,6.932552e-07,0.0,0.0,5.481808,77.742280,ITGB1;VASP;PRKCI;JUP;ACTN1;ILK;CDH5;AFDN;PARD6...,0.174419
537,7,754,MET Activates RAP1 And RAC1 R-HSA-8875555,6/11,3.895066e-06,['Signal Transduction'],Reactome_2022,1.105696e-06,0.0,0.0,30.867914,423.354536,RAP1B;RAP1A;DOCK7;RAPGEF1;CRK;CRKL,0.545455
546,7,754,CREB Phosphorylation R-HSA-199920,5/7,5.161452e-06,"['Immune System', 'Signal Transduction']",Reactome_2022,1.481836e-06,0.0,0.0,64.232310,862.140746,RPS6KA3;RPS6KA5;RPS6KA2;MAPKAPK2;RPS6KA1,0.714286
549,7,754,CD28 Dependent Vav1 Pathway R-HSA-389359,6/12,7.373627e-06,['Immune System'],Reactome_2022,2.140730e-06,0.0,0.0,25.721925,335.783360,CDC42;LCK;FYN;PKN1;ARHGEF7;VAV1,0.500000
551,7,754,Synthesis Of PIPs At Plasma Membrane R-HSA-166...,11/51,8.340729e-06,['Metabolism'],Reactome_2022,2.439439e-06,0.0,0.0,7.108546,91.869023,INPP5D;INPPL1;PTEN;PIK3R3;PIK3R2;PIP5K1B;PIK3R...,0.215686

In [14]:
print(go_df_filtered[["Term","Adjusted P-value","Overlap"]].to_latex(longtable=True,index=False,caption=f"Enriched terms for {DISEASE} Community {comm_idx}",label=f"appendix:{DISEASE}_{comm_idx}_term", float_format="%.2e",column_format="p{8cm}cc",))

\begin{longtable}{p{8cm}cc}
\caption{Enriched terms for BIPOLAR Community 7} \label{appendix:BIPOLAR_7_term} \\
\toprule
Term & Adjusted P-value & Overlap \\
\midrule
\endfirsthead
\caption[]{Enriched terms for BIPOLAR Community 7} \\
\toprule
Term & Adjusted P-value & Overlap \\
\midrule
\endhead
\midrule
\multicolumn{3}{r}{Continued on next page} \\
\midrule
\endfoot
\bottomrule
\endlastfoot
VEGFA-VEGFR2 Pathway R-HSA-4420097 & 3.51e-64 & 62/93 \\
EPH-Ephrin Signaling R-HSA-2682334 & 1.21e-61 & 60/91 \\
Fcgamma Receptor (FCGR) Dependent Phagocytosis R-HSA-2029480 & 5.20e-60 & 58/87 \\
Bacterial invasion of epithelial cells & 5.19e-58 & 54/77 \\
ErbB signaling pathway & 8.32e-53 & 53/85 \\
RAC2 GTPase Cycle R-HSA-9013404 & 1.13e-51 & 53/87 \\
Fc gamma R-mediated phagocytosis & 1.48e-48 & 53/97 \\
NRAGE Signals Death Thru JNK R-HSA-193648 & 2.70e-48 & 43/57 \\
RHOB GTPase Cycle R-HSA-9013026 & 6.98e-46 & 45/69 \\
Semaphorin Interactions R-HSA-373755 & 2.46e-41 & 41/64 \\
Protein Tyrosine Kinase Activity (GO:0004713) & 3.25e-41 & 49/99 \\
Adherens junction & 4.90e-39 & 41/71 \\
Constitutive Signaling By Aberrant PI3K In Cancer R-HSA-2219530 & 6.83e-38 & 42/78 \\
RHOQ GTPase Cycle R-HSA-9013406 & 7.50e-37 & 37/59 \\
Oncogenic MAPK Signaling R-HSA-6802957 & 1.51e-33 & 39/78 \\
Prolactin signaling pathway & 6.83e-32 & 36/70 \\
Signaling By SCF-KIT R-HSA-1433557 & 8.76e-31 & 29/42 \\
Protein Phosphorylated Amino Acid Binding (GO:0045309) & 1.29e-30 & 30/45 \\
Choline metabolism in cancer & 3.32e-29 & 39/98 \\
VEGF signaling pathway & 5.28e-28 & 31/59 \\
Signaling By EGFR R-HSA-177929 & 6.90e-28 & 29/49 \\
B cell receptor signaling pathway & 8.49e-28 & 35/81 \\
PD-L1 expression and PD-1 checkpoint pathway in cancer & 2.29e-27 & 36/89 \\
Regulation Of Phosphatidylinositol 3-Kinase Signaling (GO:0014066) & 5.62e-27 & 37/90 \\
Fc epsilon RI signaling pathway & 5.87e-27 & 32/68 \\
Extra-nuclear Estrogen Signaling R-HSA-9009391 & 1.26e-26 & 33/73 \\
MAPK Cascade (GO:0000165) & 1.28e-26 & 38/98 \\
Signaling By ERBB2 R-HSA-1227986 & 2.36e-26 & 28/49 \\
Signaling By Non-Receptor Tyrosine Kinases R-HSA-9006927 & 2.21e-25 & 28/52 \\
RHOU GTPase Cycle R-HSA-9013420 & 2.27e-25 & 25/39 \\
Nuclear Events (Kinase And Transcription Factor Activation) R-HSA-198725 & 2.99e-24 & 29/61 \\
Renal cell carcinoma & 4.42e-24 & 30/69 \\
RHO GTPases Activate ROCKs R-HSA-5627117 & 4.80e-24 & 18/19 \\
Insulin Receptor Signaling Pathway (GO:0008286) & 3.86e-23 & 26/47 \\
Signaling To ERKs R-HSA-187687 & 6.07e-23 & 22/33 \\
Receptor Tyrosine Kinase Binding (GO:0030971) & 6.88e-23 & 28/59 \\
Non-small cell lung cancer & 3.34e-22 & 29/72 \\
FLT3 Signaling R-HSA-9607240 & 2.38e-21 & 22/37 \\
Regulation Of Actin Filament-Based Process (GO:0032970) & 2.44e-21 & 29/70 \\
ERBB Signaling Pathway (GO:0038127) & 3.53e-21 & 26/54 \\
Signaling By MET R-HSA-6806834 & 3.77e-21 & 27/63 \\
Netrin-1 Signaling R-HSA-373752 & 1.47e-20 & 24/49 \\
GPVI-mediated Activation Cascade R-HSA-114604 & 4.45e-20 & 20/32 \\
Glioma & 3.07e-19 & 27/75 \\
Pancreatic cancer & 4.51e-19 & 27/76 \\
Rho Protein Signal Transduction (GO:0007266) & 5.06e-19 & 24/52 \\
Stress-Activated MAPK Cascade (GO:0051403) & 5.92e-19 & 22/42 \\
Positive Regulation Of MAP Kinase Activity (GO:0043406) & 8.18e-19 & 30/91 \\
GnRH signaling pathway & 1.24e-18 & 29/93 \\
Downstream Signal Transduction R-HSA-186763 & 1.91e-18 & 18/28 \\
Ephrin Signaling R-HSA-3928664 & 2.96e-18 & 15/18 \\
L1CAM Interactions R-HSA-373760 & 2.19e-17 & 29/99 \\
Regulation Of Ras Protein Signal Transduction (GO:0046578) & 9.20e-17 & 26/76 \\
Costimulation By CD28 Family R-HSA-388841 & 1.46e-16 & 24/68 \\
FCERI Mediated Ca+2 Mobilization R-HSA-2871809 & 1.73e-16 & 17/29 \\
Positive Regulation Of Supramolecular Fiber Organization (GO:1902905) & 5.09e-16 & 28/96 \\
Regulation Of Stress Fiber Assembly (GO:0051492) & 7.75e-16 & 25/75 \\
Integrin Signaling R-HSA-354192 & 1.11e-15 & 16/27 \\
Regulation Of Hydrolase Activity (GO:0051336) & 2.30e-15 & 24/71 \\
FCERI Mediated MAPK Activation R-HSA-2871796 & 5.03e-15 & 16/29 \\
Vascular Endothelial Growth Factor Receptor Signaling Pathway (GO:0048010) & 1.32e-14 & 16/28 \\
Regulation Of Signaling By CBL R-HSA-912631 & 1.59e-14 & 13/18 \\
Ephrin Receptor Binding (GO:0046875) & 2.12e-14 & 14/21 \\
Post NMDA Receptor Activation Events R-HSA-438064 & 2.18e-14 & 21/61 \\
RHOF GTPase Cycle R-HSA-9035034 & 2.23e-14 & 18/42 \\
Growth Factor Receptor Binding (GO:0070851) & 2.27e-14 & 26/96 \\
VEGFR2 Mediated Vascular Permeability R-HSA-5218920 & 3.29e-14 & 15/27 \\
Inflammatory mediator regulation of TRP channels & 5.09e-14 & 25/98 \\
B Cell Receptor Signaling Pathway (GO:0050853) & 5.15e-14 & 19/46 \\
Interleukin-2 Family Signaling R-HSA-451927 & 5.82e-14 & 18/44 \\
Type II diabetes mellitus & 5.84e-14 & 18/46 \\
Protein Tyrosine Phosphatase Activity (GO:0004725) & 6.74e-14 & 23/76 \\
Acute myeloid leukemia & 6.92e-14 & 21/67 \\
Negative Regulation Of Insulin Receptor Signaling Pathway (GO:0046627) & 8.87e-14 & 15/26 \\
Regulation Of Epidermal Growth Factor-Activated Receptor Activity (GO:0007176) & 8.87e-14 & 15/26 \\
Chronic myeloid leukemia & 1.01e-13 & 22/76 \\
Insulin Receptor Signaling Cascade R-HSA-74751 & 1.79e-13 & 19/53 \\
Positive Regulation Of Endothelial Cell Migration (GO:0010595) & 1.97e-13 & 24/85 \\
Negative Regulation Of MAPK Pathway R-HSA-5675221 & 2.37e-13 & 17/41 \\
Regulation Of Lamellipodium Assembly (GO:0010591) & 3.63e-13 & 16/33 \\
RND3 GTPase Cycle R-HSA-9696264 & 3.73e-13 & 17/42 \\
Constitutive Signaling By AKT1 E17K In Cancer R-HSA-5674400 & 4.38e-13 & 14/26 \\
Antigen Activates B Cell Receptor Leading To Second Messenger Generation R-HSA-983695 & 4.38e-13 & 15/31 \\
SEMA3A-Plexin Repulsion Signaling By Inhibiting Integrin Adhesion R-HSA-399955 & 4.41e-13 & 11/14 \\
Fc-gamma Receptor Signaling Pathway (GO:0038094) & 5.50e-13 & 14/24 \\
Regulation Of Phosphatidylinositol 3-Kinase Activity (GO:0043551) & 6.28e-13 & 16/34 \\
Regulation Of Peptidyl-Tyrosine Phosphorylation (GO:0050730) & 7.22e-13 & 24/90 \\
Regulation Of Focal Adhesion Assembly (GO:0051893) & 1.36e-12 & 19/54 \\
Extrinsic Component Of Cytoplasmic Side Of Plasma Membrane (GO:0031234) & 1.50e-12 & 22/77 \\
Transmembrane Receptor Protein Kinase Activity (GO:0019199) & 1.68e-12 & 16/37 \\
Central carbon metabolism in cancer & 1.85e-12 & 20/70 \\
RET Signaling R-HSA-8853659 & 2.45e-12 & 16/40 \\
Growth Hormone Receptor Signaling R-HSA-982772 & 2.98e-12 & 13/24 \\
RHO GTPases Activate NADPH Oxidases R-HSA-5668599 & 2.98e-12 & 13/24 \\
SH3 Domain Binding (GO:0017124) & 4.42e-12 & 19/59 \\
Long-term potentiation & 7.96e-12 & 19/67 \\
Actin Filament (GO:0005884) & 2.22e-11 & 20/71 \\
Lamellipodium Organization (GO:0097581) & 2.66e-11 & 14/30 \\
Regulation Of Axonogenesis (GO:0050770) & 2.88e-11 & 16/42 \\
Dendritic Spine Organization (GO:0097061) & 5.42e-11 & 13/26 \\
Rac Protein Signal Transduction (GO:0016601) & 5.93e-11 & 11/17 \\
Myogenesis R-HSA-525793 & 6.41e-11 & 13/29 \\
1-Phosphatidylinositol-3-Kinase Regulator Activity (GO:0046935) & 7.40e-11 & 10/14 \\
Signaling By Erythropoietin R-HSA-9006335 & 7.84e-11 & 12/24 \\
Gap junction & 1.65e-10 & 20/88 \\
Translocation Of SLC2A4 (GLUT4) To Plasma Membrane R-HSA-1445148 & 1.68e-10 & 16/51 \\
MAP Kinase Kinase Kinase Activity (GO:0004709) & 1.74e-10 & 11/19 \\
Ephrin Receptor Activity (GO:0005003) & 1.99e-10 & 10/15 \\
Phosphatidylinositol-Mediated Signaling (GO:0048015) & 2.06e-10 & 18/62 \\
Platelet-Derived Growth Factor Receptor Signaling Pathway (GO:0048008) & 3.69e-10 & 10/15 \\
Transmembrane Receptor Protein Tyrosine Kinase Activator Activity (GO:0030297) & 3.92e-10 & 9/12 \\
Substrate Adhesion-Dependent Cell Spreading (GO:0034446) & 4.78e-10 & 14/36 \\
ERKs Are Inactivated R-HSA-202670 & 4.98e-10 & 9/13 \\
PTK6 Regulates RHO GTPases, RAS GTPase And MAP Kinases R-HSA-8849471 & 4.98e-10 & 9/13 \\
Nephrin Family Interactions R-HSA-373753 & 5.31e-10 & 11/22 \\
Plasma Membrane Bounded Cell Projection Morphogenesis (GO:0120039) & 5.48e-10 & 16/50 \\
RSK Activation R-HSA-444257 & 5.66e-10 & 7/7 \\
Protein Serine/Threonine/Tyrosine Kinase Activity (GO:0004712) & 5.84e-10 & 12/26 \\
Regulation Of Cell Size (GO:0008361) & 6.38e-10 & 12/25 \\
Aldosterone-regulated sodium reabsorption & 9.40e-10 & 13/37 \\
Signaling By ERBB4 R-HSA-1236394 & 1.03e-09 & 16/57 \\
Cellular Response To Nerve Growth Factor Stimulus (GO:1990090) & 1.22e-09 & 11/21 \\
Actin Cytoskeleton Reorganization (GO:0031532) & 1.37e-09 & 16/53 \\
Epithelial cell signaling in Helicobacter pylori infection & 1.37e-09 & 17/70 \\
RHOH GTPase Cycle R-HSA-9013407 & 1.53e-09 & 13/36 \\
DARPP-32 Events R-HSA-180024 & 1.69e-09 & 11/24 \\
InlB-mediated Entry Of Listeria Monocytogenes Into Host Cell R-HSA-8875360 & 3.03e-09 & 9/15 \\
Regulation Of Rho Protein Signal Transduction (GO:0035023) & 3.43e-09 & 18/73 \\
calcineurin-NFAT Signaling Cascade (GO:0033173) & 3.69e-09 & 8/10 \\
B Cell Activation (GO:0042113) & 3.73e-09 & 20/92 \\
Bladder cancer & 3.85e-09 & 13/41 \\
Platelet Aggregation (GO:0070527) & 4.16e-09 & 13/35 \\
Pertussis & 5.12e-09 & 17/76 \\
Polarized Epithelial Cell Differentiation (GO:0030859) & 5.32e-09 & 9/14 \\
Cell Chemotaxis (GO:0060326) & 5.39e-09 & 15/50 \\
Regulation Of Glucose Import (GO:0046324) & 6.14e-09 & 13/36 \\
Integrin-Mediated Signaling Pathway (GO:0007229) & 6.14e-09 & 19/85 \\
Regulation Of JUN Kinase Activity (GO:0043506) & 6.16e-09 & 14/43 \\
Regulation Of miRNA Transcription (GO:1902893) & 7.05e-09 & 16/59 \\
FLT3 Signaling In Disease R-HSA-9682385 & 7.59e-09 & 11/27 \\
PECAM1 Interactions R-HSA-210990 & 8.29e-09 & 8/12 \\
Adipocytokine signaling pathway & 8.45e-09 & 16/69 \\
Regulation Of Cellular Component Biogenesis (GO:0044087) & 8.84e-09 & 13/37 \\
DAP12 Signaling R-HSA-2424491 & 1.18e-08 & 11/28 \\
Positive Regulation Of Axonogenesis (GO:0050772) & 1.26e-08 & 13/38 \\
Tie2 Signaling R-HSA-210993 & 1.30e-08 & 9/17 \\
FLT3 Signaling Thru SRC Family Kinases R-HSA-9706374 & 1.34e-08 & 6/6 \\
PI3K/AKT Activation R-HSA-198203 & 1.67e-08 & 7/9 \\
RHO GTPases Activate Rhotekin And Rhophilins R-HSA-5666185 & 1.67e-08 & 7/9 \\
Smooth Muscle Contraction R-HSA-445355 & 1.68e-08 & 13/43 \\
Negative Regulation Of Cell Adhesion (GO:0007162) & 1.99e-08 & 17/72 \\
Cellular Response To Reactive Oxygen Species (GO:0034614) & 2.49e-08 & 17/73 \\
Negative Regulation Of ERK1 And ERK2 Cascade (GO:0070373) & 2.91e-08 & 14/48 \\
Non-Membrane Spanning Protein Tyrosine Phosphatase Activity (GO:0004726) & 3.67e-08 & 7/9 \\
Regulation Of Platelet Activation (GO:0010543) & 4.56e-08 & 11/28 \\
Signaling Receptor Complex Adaptor Activity (GO:0030159) & 4.98e-08 & 13/44 \\
Intrinsic Pathway For Apoptosis R-HSA-109606 & 4.98e-08 & 14/55 \\
Growth Hormone Receptor Signaling Pathway (GO:0060396) & 5.07e-08 & 9/17 \\
Generation Of Second Messenger Molecules R-HSA-202433 & 5.66e-08 & 11/32 \\
RAF Activation R-HSA-5673000 & 5.66e-08 & 11/32 \\
Regulation Of Filopodium Assembly (GO:0051489) & 6.49e-08 & 13/43 \\
Receptor Internalization (GO:0031623) & 6.49e-08 & 14/51 \\
Negative Regulation Of MAP Kinase Activity (GO:0043407) & 6.49e-08 & 14/51 \\
Positive Regulation Of Ras Protein Signal Transduction (GO:0046579) & 6.49e-08 & 14/51 \\
Glutamatergic Synapse (GO:0098978) & 6.59e-08 & 17/78 \\
Negative Regulation Of Protein Kinase Activity (GO:0006469) & 6.90e-08 & 18/88 \\
Regulation Of Cell Junction Assembly (GO:1901888) & 6.95e-08 & 10/23 \\
Long-term depression & 6.97e-08 & 14/60 \\
Peptidyl-Tyrosine Autophosphorylation (GO:0038083) & 7.34e-08 & 8/13 \\
ERBB2 Signaling Pathway (GO:0038128) & 7.34e-08 & 8/13 \\
Cellular Response To Peptide Hormone Stimulus (GO:0071375) & 8.11e-08 & 18/89 \\
ARMS-mediated Activation R-HSA-170984 & 8.37e-08 & 6/7 \\
Signaling By ERBB2 ECD Mutants R-HSA-9665348 & 8.65e-08 & 8/15 \\
Negative Regulation Of ERBB Signaling Pathway (GO:1901185) & 8.91e-08 & 9/18 \\
Signaling By FGFR1 R-HSA-5654736 & 9.03e-08 & 13/49 \\
Protein Kinase C Activity (GO:0004697) & 9.05e-08 & 8/14 \\
MTOR Signaling R-HSA-165159 & 9.35e-08 & 12/41 \\
Negative Regulation Of Peptidyl-Tyrosine Phosphorylation (GO:0050732) & 9.72e-08 & 11/30 \\
Tau Protein Binding (GO:0048156) & 1.04e-07 & 12/39 \\
Actin Polymerization Or Depolymerization (GO:0008154) & 1.06e-07 & 14/53 \\
DSCAM Interactions R-HSA-376172 & 1.27e-07 & 7/11 \\
Arp2/3 Complex-Mediated Actin Nucleation (GO:0034314) & 1.56e-07 & 9/19 \\
Positive Regulation Of Protein Kinase B Signaling (GO:0051897) & 1.59e-07 & 18/93 \\
Rap1 Signaling R-HSA-392517 & 1.60e-07 & 8/16 \\
Regulation of lipolysis in adipocytes & 1.79e-07 & 13/55 \\
Positive Regulation Of Actin Nucleation (GO:0051127) & 1.81e-07 & 7/10 \\
Protein Kinase Activator Activity (GO:0030295) & 2.25e-07 & 17/88 \\
Positive Regulation Of Phospholipase Activity (GO:0010518) & 2.62e-07 & 9/20 \\
Activation Of RAC1 R-HSA-428540 & 2.88e-07 & 7/12 \\
Regulation Of Localization Of FOXO Transcription Factors R-HSA-9614399 & 2.88e-07 & 7/12 \\
Sema4D Mediated Inhibition Of Cell Attachment And Migration R-HSA-416550 & 2.99e-07 & 6/8 \\
Signaling By NTRK2 (TRKB) R-HSA-9006115 & 2.99e-07 & 9/23 \\
Signaling By CSF3 (G-CSF) R-HSA-9674555 & 3.29e-07 & 10/30 \\
Peptidyl-Threonine Phosphorylation (GO:0018107) & 3.40e-07 & 14/58 \\
Mitophagy & 3.65e-07 & 14/68 \\
Signaling By ALK Fusions And Activated Point Mutants R-HSA-9725370 & 3.72e-07 & 13/55 \\
Cortical Cytoskeleton Organization (GO:0030865) & 3.84e-07 & 10/27 \\
Semaphorin-Plexin Signaling Pathway (GO:0071526) & 3.90e-07 & 11/34 \\
VEGFR2 Mediated Cell Proliferation R-HSA-5218921 & 4.83e-07 & 8/18 \\
Regulation Of Stress-Activated MAPK Cascade (GO:0032872) & 5.14e-07 & 13/51 \\
Negative Regulation Of Actin Filament Bundle Assembly (GO:0032232) & 5.58e-07 & 10/28 \\
Small cell lung cancer & 5.72e-07 & 16/92 \\
Regulation Of Protein Localization To Plasma Membrane (GO:1903076) & 5.77e-07 & 16/80 \\
Cell-Cell Junction Assembly (GO:0007043) & 7.03e-07 & 15/71 \\
Caveola (GO:0005901) & 7.39e-07 & 14/62 \\
Regulation Of Developmental Growth (GO:0048638) & 8.03e-07 & 10/29 \\
p75NTR Regulates Axonogenesis R-HSA-193697 & 8.21e-07 & 6/9 \\
NADPH Oxidase Complex (GO:0043020) & 8.61e-07 & 8/17 \\
SH2 Domain Binding (GO:0042169) & 9.73e-07 & 10/31 \\
Cell Projection Assembly (GO:0030031) & 9.90e-07 & 7/12 \\
Response To Epidermal Growth Factor (GO:0070849) & 1.12e-06 & 10/30 \\
Insulin-Like Growth Factor Receptor Binding (GO:0005159) & 1.17e-06 & 7/13 \\
Histone H3 Kinase Activity (GO:0140996) & 1.66e-06 & 6/9 \\
Leishmaniasis & 1.71e-06 & 14/77 \\
Caspase Activation Via Dependence Receptors In Absence Of Ligand R-HSA-418889 & 1.88e-06 & 6/10 \\
Activation Of PPARGC1A (PGC-1alpha) By Phosphorylation R-HSA-2151209 & 1.88e-06 & 6/10 \\
Actomyosin Structure Organization (GO:0031032) & 2.00e-06 & 15/77 \\
Positive Regulation Of JNK Cascade (GO:0046330) & 2.00e-06 & 15/77 \\
Positive Regulation Of Cell Adhesion (GO:0045785) & 2.12e-06 & 16/88 \\
Regulation Of Actin Cytoskeleton Reorganization (GO:2000249) & 2.23e-06 & 9/25 \\
Potential Therapeutics For SARS R-HSA-9679191 & 2.35e-06 & 16/97 \\
Cell Junction Organization R-HSA-446728 & 2.48e-06 & 15/86 \\
Regulation Of Cell Adhesion Mediated By Integrin (GO:0033628) & 2.87e-06 & 10/33 \\
Negative Regulation Of Cell Projection Organization (GO:0031345) & 3.05e-06 & 12/50 \\
Regulation Of Actin Filament Bundle Assembly (GO:0032231) & 3.17e-06 & 9/26 \\
Positive Regulation Of Nuclear Division (GO:0051785) & 3.17e-06 & 9/26 \\
Filopodium (GO:0030175) & 3.24e-06 & 13/60 \\
Vascular Endothelial Growth Factor Signaling Pathway (GO:0038084) & 3.50e-06 & 7/14 \\
Regulation Of Substrate Adhesion-Dependent Cell Spreading (GO:1900024) & 3.76e-06 & 12/51 \\
Positive Regulation Of Neuron Death (GO:1901216) & 3.77e-06 & 10/34 \\
Negative Regulation Of Ras Protein Signal Transduction (GO:0046580) & 3.77e-06 & 10/34 \\
MET Activates RAP1 And RAC1 R-HSA-8875555 & 3.90e-06 & 6/11 \\
Phospholipase Binding (GO:0043274) & 3.95e-06 & 7/15 \\
Positive Regulation Of Cell Junction Assembly (GO:1901890) & 4.09e-06 & 13/61 \\
Phosphatidylinositol-3,4,5-Trisphosphate Binding (GO:0005547) & 4.26e-06 & 10/36 \\
Regulation Of Phosphorylation (GO:0042325) & 4.28e-06 & 15/82 \\
Regulation Of Actin Polymerization Or Depolymerization (GO:0008064) & 4.37e-06 & 9/27 \\
Regulation Of Cell-Cell Adhesion (GO:0022407) & 4.47e-06 & 11/43 \\
Regulation Of Axon Extension (GO:0030516) & 4.85e-06 & 10/35 \\
Regulation Of Vascular Associated Smooth Muscle Cell Differentiation (GO:1905063) & 4.96e-06 & 5/6 \\
CREB Phosphorylation R-HSA-199920 & 5.16e-06 & 5/7 \\
Negative Regulation Of Platelet Activation (GO:0010544) & 5.83e-06 & 7/15 \\
Negative Regulation Of Signaling (GO:0023057) & 5.94e-06 & 9/28 \\
CD28 Dependent Vav1 Pathway R-HSA-389359 & 7.37e-06 & 6/12 \\
Positive Regulation Of Microtubule Polymerization (GO:0031116) & 8.20e-06 & 9/29 \\
Synthesis Of PIPs At Plasma Membrane R-HSA-1660499 & 8.34e-06 & 11/51 \\
Mitogen-Activated Protein Kinase Binding (GO:0051019) & 8.39e-06 & 8/23 \\
\end{longtable}

In [15]:
list(go_df_filtered["Term"])[:30]

['VEGFA-VEGFR2 Pathway R-HSA-4420097',
 'EPH-Ephrin Signaling R-HSA-2682334',
 'Fcgamma Receptor (FCGR) Dependent Phagocytosis R-HSA-2029480',
 'Bacterial invasion of epithelial cells',
 'ErbB signaling pathway',
 'RAC2 GTPase Cycle R-HSA-9013404',
 'Fc gamma R-mediated phagocytosis',
 'NRAGE Signals Death Thru JNK R-HSA-193648',
 'RHOB GTPase Cycle R-HSA-9013026',
 'Semaphorin Interactions R-HSA-373755',
 'Protein Tyrosine Kinase Activity (GO:0004713)',
 'Adherens junction',
 'Constitutive Signaling By Aberrant PI3K In Cancer R-HSA-2219530',
 'RHOQ GTPase Cycle R-HSA-9013406',
 'Oncogenic MAPK Signaling R-HSA-6802957',
 'Prolactin signaling pathway',
 'Signaling By SCF-KIT R-HSA-1433557',
 'Protein Phosphorylated Amino Acid Binding (GO:0045309)',
 'Choline metabolism in cancer',
 'VEGF signaling pathway',
 'Signaling By EGFR R-HSA-177929',
 'B cell receptor signaling pathway',
 'PD-L1 expression and PD-1 checkpoint pathway in cancer',
 'Regulation Of Phosphatidylinositol 3-Kinase Signaling (GO:0014066)',
 'Fc epsilon RI signaling pathway',
 'Extra-nuclear Estrogen Signaling R-HSA-9009391',
 'MAPK Cascade (GO:0000165)',
 'Signaling By ERBB2 R-HSA-1227986',
 'Signaling By Non-Receptor Tyrosine Kinases R-HSA-9006927',
 'RHOU GTPase Cycle R-HSA-9013420']

In [16]:
go_df_filtered

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,Overlap (value)
306,7,754,VEGFA-VEGFR2 Pathway R-HSA-4420097,62/93,3.506578e-64,['Signal Transduction'],Reactome_2022,6.786926e-66,0.0,0.0,55.534682,8333.291043,CYFIP2;PRR5;CYFIP1;NCKAP1;AHCYL1;NCF1;ITGB3;BR...,0.666667
307,7,754,EPH-Ephrin Signaling R-HSA-2682334,60/91,1.211928e-61,['Developmental Biology'],Reactome_2022,2.475982e-63,0.0,0.0,53.588361,7725.095772,EPHB6;ARPC1B;ARPC1A;ITSN1;CLTB;WASL;ACTG1;SYNG...,0.659341
308,7,754,Fcgamma Receptor (FCGR) Dependent Phagocytosis...,58/87,5.199764e-60,['Immune System'],Reactome_2022,1.118229e-61,0.0,0.0,55.221264,7750.080509,CYFIP2;CYFIP1;NCKAP1;AHCYL1;WIPF1;ARPC1B;WIPF2...,0.666667
309,7,754,Bacterial invasion of epithelial cells,54/77,5.189699e-58,['Infectious disease: bacterial'],KEGG_2021_Human,2.192831e-59,0.0,0.0,64.474658,8708.419783,ITGB1;ARPC1B;ARPC1A;ARPC5L;CLTB;ILK;PIK3CD;WAS...,0.701299
310,7,754,ErbB signaling pathway,53/85,8.316038e-53,['Signal transduction'],KEGG_2021_Human,4.685092e-54,0.0,0.0,45.396844,5574.514944,GSK3B;CDKN1B;PIK3CD;CBLB;AREG;ELK1;CRKL;NCK2;N...,0.623529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
548,7,754,Negative Regulation Of Signaling (GO:0023057),9/28,5.939201e-06,['biological regulation'],GO_Biological_Process_2023,5.316013e-07,0.0,0.0,12.224868,176.617211,BRAP;PPP3CA;PTPN1;PPP3CB;MPIG6B;SRMS;ERBB3;INP...,0.321429
549,7,754,CD28 Dependent Vav1 Pathway R-HSA-389359,6/12,7.373627e-06,['Immune System'],Reactome_2022,2.140730e-06,0.0,0.0,25.721925,335.783360,CDC42;LCK;FYN;PKN1;ARHGEF7;VAV1,0.500000
550,7,754,Positive Regulation Of Microtubule Polymerizat...,9/29,8.201933e-06,['biological regulation'],GO_Biological_Process_2023,7.451303e-07,0.0,0.0,11.613020,163.856308,PAK1;OCLN;CAV3;FES;RAC1;MAPT;MET;GIT1;CDK5R1,0.310345
551,7,754,Synthesis Of PIPs At Plasma Membrane R-HSA-166...,11/51,8.340729e-06,['Metabolism'],Reactome_2022,2.439439e-06,0.0,0.0,7.108546,91.869023,INPP5D;INPPL1;PTEN;PIK3R3;PIK3R2;PIP5K1B;PIK3R...,0.215686
552,7,754,Mitogen-Activated Protein Kinase Binding (GO:0...,8/23,8.386598e-06,['binding'],GO_Molecular_Function_2023,1.165383e-06,0.0,0.0,13.748704,187.841128,DUSP10;MAPK7;MAPKAPK3;MAPKAPK2;PRKG2;NFATC1;PT...,0.347826

In [17]:
print(list(go_df_filtered[go_df_filtered["Category"] == "['Signal Transduction']"]["Term"]))

['VEGFA-VEGFR2 Pathway R-HSA-4420097', 'RAC2 GTPase Cycle R-HSA-9013404', 'NRAGE Signals Death Thru JNK R-HSA-193648', 'RHOB GTPase Cycle R-HSA-9013026', 'RHOQ GTPase Cycle R-HSA-9013406', 'Signaling By SCF-KIT R-HSA-1433557', 'Signaling By EGFR R-HSA-177929', 'Extra-nuclear Estrogen Signaling R-HSA-9009391', 'Signaling By ERBB2 R-HSA-1227986', 'Signaling By Non-Receptor Tyrosine Kinases R-HSA-9006927', 'RHOU GTPase Cycle R-HSA-9013420', 'Nuclear Events (Kinase And Transcription Factor Activation) R-HSA-198725', 'RHO GTPases Activate ROCKs R-HSA-5627117', 'Signaling To ERKs R-HSA-187687', 'Signaling By MET R-HSA-6806834', 'Downstream Signal Transduction R-HSA-186763', 'RHOF GTPase Cycle R-HSA-9035034', 'VEGFR2 Mediated Vascular Permeability R-HSA-5218920', 'Insulin Receptor Signaling Cascade R-HSA-74751', 'Negative Regulation Of MAPK Pathway R-HSA-5675221', 'RND3 GTPase Cycle R-HSA-9696264', 'RHO GTPases Activate NADPH Oxidases R-HSA-5668599', 'Signaling By Erythropoietin R-HSA-9006335', 'PTK6 Regulates RHO GTPases, RAS GTPase And MAP Kinases R-HSA-8849471', 'Signaling By ERBB4 R-HSA-1236394', 'RHOH GTPase Cycle R-HSA-9013407', 'DARPP-32 Events R-HSA-180024', 'PI3K/AKT Activation R-HSA-198203', 'RHO GTPases Activate Rhotekin And Rhophilins R-HSA-5666185', 'RAF Activation R-HSA-5673000', 'ARMS-mediated Activation R-HSA-170984', 'Signaling By FGFR1 R-HSA-5654736', 'MTOR Signaling R-HSA-165159', 'Signaling By NTRK2 (TRKB) R-HSA-9006115', 'VEGFR2 Mediated Cell Proliferation R-HSA-5218921', 'p75NTR Regulates Axonogenesis R-HSA-193697', 'MET Activates RAP1 And RAC1 R-HSA-8875555']

In [18]:
A = ['Class A/1 (Rhodopsin-like Receptors) R-HSA-373076', 'GPCR Ligand Binding R-HSA-500792', 'Peptide Ligand-Binding Receptors R-HSA-375276', 'Signaling By GPCR R-HSA-372790', 'GPCR Downstream Signaling R-HSA-388396', 'G Alpha (I) Signaling Events R-HSA-418594', 'G Alpha (Q) Signaling Events R-HSA-416476', 'Amine Ligand-Binding Receptors R-HSA-375280', 'G Alpha (S) Signaling Events R-HSA-418555', 'Chemokine Receptors Bind Chemokines R-HSA-380108', 'Serotonin Receptors R-HSA-390666']

B = ['GPCR Ligand Binding R-HSA-500792', 'Signaling By GPCR R-HSA-372790', 'GPCR Downstream Signaling R-HSA-388396', 'Class A/1 (Rhodopsin-like Receptors) R-HSA-373076', 'Peptide Ligand-Binding Receptors R-HSA-375276', 'G Alpha (I) Signaling Events R-HSA-418594', 'G Alpha (S) Signaling Events R-HSA-418555', 'G Alpha (Q) Signaling Events R-HSA-416476', 'Class B/2 (Secretin Family Receptors) R-HSA-373080', 'Chemokine Receptors Bind Chemokines R-HSA-380108', 'Glucagon-type Ligand Receptors R-HSA-420092', 'Calcitonin-like Ligand Receptors R-HSA-419812', 'Lysosphingolipid And LPA Receptors R-HSA-419408', 'G Alpha (Z) Signaling Events R-HSA-418597', 'Formyl Peptide Receptors Bind Formyl Peptides And Many Other Ligands R-HSA-444473']

In [19]:
list(go_df_filtered["Category"].unique())

["['Signal Transduction']",
 "['Developmental Biology']",
 "['Immune System']",
 "['Infectious disease: bacterial']",
 "['Signal transduction']",
 "['Immune system']",
 "['catalytic activity']",
 "['Cellular community - eukaryotes']",
 "['Disease']",
 "['Endocrine system']",
 "['binding']",
 "['Cancer: overview']",
 '[]',
 "['cellular process', 'biological regulation']",
 "['Cancer: specific types']",
 "['biological regulation']",
 "['Hemostasis']",
 "['cellular process', 'response to stimulus', 'biological regulation']",
 "['Hemostasis', 'Signal Transduction']",
 "['Neuronal System']",
 "['Sensory system']",
 "['immune system process', 'cellular process', 'biological regulation']",
 "['Endocrine and metabolic disease']",
 "['cellular anatomical structure']",
 "['molecular transducer activity', 'catalytic activity']",
 "['Nervous system']",
 "['cellular process']",
 "['molecular function regulator activity']",
 "['Vesicle-mediated transport']",
 "['Immune System', 'Signal Transduction']",
 "['Cell-Cell communication']",
 "['developmental process', 'cellular process']",
 "['Excretory system']",
 "['response to stimulus']",
 "['immune system process', 'multicellular organismal process', 'cellular process']",
 "['cellular process', 'locomotion']",
 "['Muscle contraction']",
 "['cellular process', 'response to stimulus']",
 "['molecular adaptor activity']",
 "['Programmed Cell Death']",
 "['localization', 'cellular process']",
 "['Gene expression (Transcription)']",
 "['protein-containing complex']",
 "['Infectious disease: parasitic']",
 "['Organelle biogenesis and maintenance']",
 "['Metabolism']"]