In [1]:
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import numpy as np
import json
import gseapy as gp

In [2]:
DISEASE = input("Disease: ")
DISEASE_FOLDER = f"../output/{DISEASE}/"
RESULT_FOLDER = DISEASE_FOLDER + "leiden_results"

# Loading

In [3]:
def load(d):
    with open(f"../output/{d}/leiden_results/result_communities_selected.pkl", "rb") as f:
        communities = pickle.load(f)
    with open(f"../output/{d}/leiden_results/result_communities_HGNC_selected.pkl", "rb") as f:
        communities_HGNC = pickle.load(f)
    # with open(f"../output/{d}/leiden_results/result_graph.pkl", "rb") as f:
    #     graph = pickle.load(f)    
    with open(f"../output/{d}/gene_to_index_distinct.json", "r") as file:
        gene_to_index_distinct = json.load(file)
        
    return communities,communities_HGNC,gene_to_index_distinct

In [4]:
communities_selected,communities_HGNC_selected,gene_to_index_distinct = load(DISEASE)

# index to HGNC

In [5]:
index_to_gene_distinct = {v: u for (u,v) in gene_to_index_distinct.items()}

In [6]:
hgnc = pd.read_csv("../../Data/hgnc_complete_set.txt", sep="\t", dtype=str)
ncbi_to_hgnc_dict = dict(
    zip(
        hgnc["entrez_id"].dropna(),
        hgnc.loc[hgnc["entrez_id"].notna(), "symbol"]
    )
)

# Select top genes

In [7]:
# comm_idx = 0

In [8]:
def zscore(values):
    arr = np.asarray(values, dtype=float)
    if arr.size == 0:
        return arr

    mean = arr.mean()
    std = arr.std(ddof=0)

    if std == 0 or np.isnan(std):
        # no variation: all z-scores = 0
        return np.zeros_like(arr)

    return (arr - mean) / std

def community_central_genes_ranked(G, community_nodes, weight="weight"):
    C = set(community_nodes)
    H = G.subgraph(C).copy()                       # induced subgraph
    # within-community (weighted) degree
    k = {u: H.degree(u, weight=weight) for u in H}
    ks = np.array(list(k.values()), dtype=float)
    zscore_list = zscore(ks)
    Z = dict(zip(H,zscore_list))        # within-module degree z-score
    
    return Z

In [9]:
index_to_gene_distinct

{10: '1',
 11: '2',
 12: '3',
 13: '9',
 14: '10',
 15: '12',
 16: '13',
 17: '14',
 18: '15',
 19: '16',
 20: '18',
 21: '19',
 22: '20',
 23: '21',
 24: '22',
 25: '23',
 26: '24',
 27: '25',
 28: '26',
 29: '27',
 30: '28',
 31: '29',
 32: '30',
 33: '31',
 34: '32',
 35: '33',
 36: '34',
 37: '35',
 38: '36',
 39: '37',
 40: '38',
 41: '39',
 42: '40',
 43: '41',
 44: '43',
 45: '47',
 46: '48',
 47: '49',
 48: '50',
 49: '51',
 50: '52',
 51: '53',
 52: '54',
 53: '55',
 54: '56',
 55: '58',
 56: '59',
 57: '60',
 58: '69',
 59: '70',
 60: '71',
 61: '72',
 62: '81',
 63: '83',
 64: '86',
 65: '87',
 66: '88',
 67: '89',
 68: '90',
 69: '91',
 70: '92',
 71: '93',
 72: '94',
 73: '95',
 74: '97',
 75: '98',
 76: '100',
 77: '101',
 78: '102',
 79: '103',
 80: '104',
 81: '105',
 82: '107',
 83: '108',
 84: '109',
 85: '111',
 86: '112',
 87: '113',
 88: '114',
 89: '115',
 90: '116',
 91: '117',
 92: '118',
 93: '119',
 94: '120',
 95: '123',
 96: '124',
 97: '125',
 98: '126',
 99: '127',
 100: '128',
 101: '130',
 102: '131',
 103: '132',
 104: '133',
 105: '134',
 106: '135',
 107: '136',
 108: '137',
 109: '140',
 110: '141',
 111: '142',
 112: '143',
 113: '146',
 114: '147',
 115: '148',
 116: '150',
 117: '151',
 118: '152',
 119: '153',
 120: '154',
 121: '155',
 122: '156',
 123: '157',
 124: '158',
 125: '159',
 126: '160',
 127: '161',
 128: '162',
 129: '163',
 130: '164',
 131: '165',
 132: '166',
 133: '167',
 134: '172',
 135: '173',
 136: '174',
 137: '175',
 138: '176',
 139: '177',
 140: '178',
 141: '181',
 142: '182',
 143: '183',
 144: '185',
 145: '186',
 146: '187',
 147: '189',
 148: '190',
 149: '191',
 150: '196',
 151: '197',
 152: '199',
 153: '202',
 154: '203',
 155: '204',
 156: '205',
 157: '207',
 158: '208',
 159: '210',
 160: '211',
 161: '212',
 162: '213',
 163: '214',
 164: '215',
 165: '216',
 166: '217',
 167: '218',
 168: '219',
 169: '220',
 170: '221',
 171: '222',
 172: '223',
 173: '224',
 174: '225',
 175: '226',
 176: '228',
 177: '229',
 178: '230',
 179: '231',
 180: '238',
 181: '239',
 182: '240',
 183: '241',
 184: '242',
 185: '245',
 186: '246',
 187: '247',
 188: '248',
 189: '249',
 190: '250',
 191: '251',
 192: '257',
 193: '258',
 194: '259',
 195: '262',
 196: '265',
 197: '266',
 198: '267',
 199: '268',
 200: '269',
 201: '270',
 202: '271',
 203: '272',
 204: '273',
 205: '274',
 206: '275',
 207: '276',
 208: '277',
 209: '278',
 210: '279',
 211: '280',
 212: '283',
 213: '284',
 214: '285',
 215: '286',
 216: '287',
 217: '288',
 218: '290',
 219: '291',
 220: '292',
 221: '293',
 222: '301',
 223: '302',
 224: '303',
 225: '304',
 226: '305',
 227: '306',
 228: '307',
 229: '308',
 230: '309',
 231: '310',
 232: '311',
 233: '312',
 234: '313',
 235: '314',
 236: '316',
 237: '317',
 238: '318',
 239: '319',
 240: '320',
 241: '321',
 242: '322',
 243: '323',
 244: '324',
 245: '325',
 246: '326',
 247: '327',
 248: '328',
 249: '329',
 250: '330',
 251: '331',
 252: '332',
 253: '333',
 254: '334',
 255: '335',
 256: '336',
 257: '337',
 258: '338',
 259: '339',
 260: '341',
 261: '342',
 262: '343',
 263: '344',
 264: '345',
 265: '346',
 266: '347',
 267: '348',
 268: '350',
 269: '351',
 270: '353',
 271: '354',
 272: '355',
 273: '356',
 274: '357',
 275: '358',
 276: '359',
 277: '360',
 278: '361',
 279: '362',
 280: '363',
 281: '364',
 282: '366',
 283: '367',
 284: '368',
 285: '369',
 286: '372',
 287: '373',
 288: '374',
 289: '375',
 290: '377',
 291: '378',
 292: '379',
 293: '381',
 294: '382',
 295: '383',
 296: '384',
 297: '387',
 298: '388',
 299: '389',
 300: '390',
 301: '391',
 302: '392',
 303: '393',
 304: '394',
 305: '395',
 306: '396',
 307: '397',
 308: '398',
 309: '399',
 310: '400',
 311: '401',
 312: '402',
 313: '403',
 314: '405',
 315: '406',
 316: '407',
 317: '408',
 318: '409',
 319: '410',
 320: '411',
 321: '412',
 322: '414',
 323: '415',
 324: '416',
 325: '417',
 326: '419',
 327: '420',
 328: '421',
 329: '427',
 330: '429',
 331: '430',
 332: '432',
 333: '433',
 334: '434',
 335: '435',
 336: '438',
 337: '439',
 338: '440',
 339: '443',
 340: '444',
 341: '445',
 342: '454',
 343: '460',
 344: '462',
 345: '463',
 346: '466',
 347: '467',
 348: '468',
 349: '471',
 350: '472',
 351: '473',
 352: '474',
 353: '475',
 354: '476',
 355: '477',
 356: '478',
 357: '479',
 358: '480',
 359: '481',
 360: '482',
 361: '483',
 362: '486',
 363: '487',
 364: '488',
 365: '489',
 366: '490',
 367: '491',
 368: '492',
 369: '493',
 370: '495',
 371: '496',
 372: '498',
 373: '501',
 374: '506',
 375: '509',
 376: '513',
 377: '514',
 378: '515',
 379: '516',
 380: '517',
 381: '518',
 382: '520',
 383: '521',
 384: '522',
 385: '523',
 386: '525',
 387: '526',
 388: '527',
 389: '528',
 390: '529',
 391: '533',
 392: '534',
 393: '535',
 394: '537',
 395: '538',
 396: '539',
 397: '540',
 398: '541',
 399: '545',
 400: '546',
 401: '547',
 402: '549',
 403: '550',
 404: '551',
 405: '552',
 406: '553',
 407: '554',
 408: '558',
 409: '563',
 410: '566',
 411: '567',
 412: '570',
 413: '571',
 414: '572',
 415: '573',
 416: '575',
 417: '576',
 418: '577',
 419: '578',
 420: '579',
 421: '580',
 422: '581',
 423: '582',
 424: '583',
 425: '585',
 426: '586',
 427: '587',
 428: '590',
 429: '593',
 430: '594',
 431: '595',
 432: '596',
 433: '597',
 434: '598',
 435: '599',
 436: '602',
 437: '604',
 438: '605',
 439: '606',
 440: '607',
 441: '608',
 442: '610',
 443: '611',
 444: '613',
 445: '617',
 446: '618',
 447: '622',
 448: '623',
 449: '624',
 450: '627',
 451: '629',
 452: '631',
 453: '632',
 454: '633',
 455: '634',
 456: '635',
 457: '636',
 458: '637',
 459: '638',
 460: '639',
 461: '640',
 462: '641',
 463: '642',
 464: '643',
 465: '644',
 466: '645',
 467: '646',
 468: '648',
 469: '649',
 470: '650',
 471: '651',
 472: '652',
 473: '653',
 474: '654',
 475: '655',
 476: '656',
 477: '657',
 478: '658',
 479: '659',
 480: '660',
 481: '661',
 482: '662',
 483: '663',
 484: '664',
 485: '665',
 486: '666',
 487: '667',
 488: '668',
 489: '669',
 490: '670',
 491: '671',
 492: '672',
 493: '673',
 494: '675',
 495: '676',
 496: '677',
 497: '678',
 498: '680',
 499: '682',
 500: '683',
 501: '684',
 502: '685',
 503: '686',
 504: '687',
 505: '688',
 506: '689',
 507: '690',
 508: '694',
 509: '695',
 510: '696',
 511: '699',
 512: '701',
 513: '705',
 514: '706',
 515: '708',
 516: '710',
 517: '711',
 518: '712',
 519: '713',
 520: '714',
 521: '715',
 522: '716',
 523: '717',
 524: '718',
 525: '719',
 526: '720',
 527: '721',
 528: '722',
 529: '725',
 530: '726',
 531: '727',
 532: '728',
 533: '729',
 534: '730',
 535: '731',
 536: '732',
 537: '733',
 538: '734',
 539: '735',
 540: '738',
 541: '740',
 542: '741',
 543: '744',
 544: '745',
 545: '746',
 546: '747',
 547: '750',
 548: '752',
 549: '753',
 550: '754',
 551: '755',
 552: '757',
 553: '758',
 554: '759',
 555: '760',
 556: '761',
 557: '762',
 558: '763',
 559: '765',
 560: '766',
 561: '767',
 562: '768',
 563: '770',
 564: '771',
 565: '773',
 566: '774',
 567: '775',
 568: '776',
 569: '777',
 570: '778',
 571: '779',
 572: '780',
 573: '781',
 574: '782',
 575: '783',
 576: '784',
 577: '785',
 578: '786',
 579: '788',
 580: '789',
 581: '790',
 582: '793',
 583: '794',
 584: '795',
 585: '796',
 586: '797',
 587: '799',
 588: '800',
 589: '801',
 590: '805',
 591: '808',
 592: '810',
 593: '811',
 594: '813',
 595: '814',
 596: '815',
 597: '816',
 598: '817',
 599: '818',
 600: '819',
 601: '820',
 602: '821',
 603: '822',
 604: '823',
 605: '824',
 606: '825',
 607: '826',
 608: '827',
 609: '828',
 610: '829',
 611: '830',
 612: '831',
 613: '832',
 614: '833',
 615: '834',
 616: '835',
 617: '836',
 618: '837',
 619: '838',
 620: '839',
 621: '840',
 622: '841',
 623: '842',
 624: '843',
 625: '844',
 626: '845',
 627: '846',
 628: '847',
 629: '857',
 630: '858',
 631: '859',
 632: '860',
 633: '861',
 634: '862',
 635: '863',
 636: '864',
 637: '865',
 638: '866',
 639: '867',
 640: '868',
 641: '869',
 642: '871',
 643: '873',
 644: '874',
 645: '875',
 646: '881',
 647: '883',
 648: '885',
 649: '886',
 650: '887',
 651: '889',
 652: '890',
 653: '891',
 654: '892',
 655: '894',
 656: '895',
 657: '896',
 658: '898',
 659: '899',
 660: '900',
 661: '901',
 662: '902',
 663: '904',
 664: '905',
 665: '908',
 666: '909',
 667: '910',
 668: '911',
 669: '912',
 670: '913',
 671: '914',
 672: '915',
 673: '916',
 674: '917',
 675: '919',
 676: '920',
 677: '921',
 678: '922',
 679: '923',
 680: '924',
 681: '925',
 682: '926',
 683: '928',
 684: '929',
 685: '930',
 686: '931',
 687: '932',
 688: '933',
 689: '936',
 690: '938',
 691: '939',
 692: '940',
 693: '941',
 694: '942',
 695: '943',
 696: '944',
 697: '945',
 698: '946',
 699: '947',
 700: '948',
 701: '949',
 702: '950',
 703: '951',
 704: '952',
 705: '953',
 706: '954',
 707: '955',
 708: '956',
 709: '957',
 710: '958',
 711: '959',
 712: '960',
 713: '961',
 714: '962',
 715: '963',
 716: '965',
 717: '966',
 718: '967',
 719: '968',
 720: '969',
 721: '970',
 722: '971',
 723: '972',
 724: '973',
 725: '974',
 726: '975',
 727: '976',
 728: '977',
 729: '978',
 730: '983',
 731: '984',
 732: '987',
 733: '988',
 734: '989',
 735: '990',
 736: '991',
 737: '993',
 738: '994',
 739: '995',
 740: '996',
 741: '997',
 742: '998',
 743: '999',
 744: '1000',
 745: '1001',
 746: '1002',
 747: '1003',
 748: '1004',
 749: '1005',
 750: '1006',
 751: '1007',
 752: '1008',
 753: '1009',
 754: '1010',
 755: '1012',
 756: '1013',
 757: '1014',
 758: '1015',
 759: '1016',
 760: '1017',
 761: '1018',
 762: '1019',
 763: '1020',
 764: '1021',
 765: '1022',
 766: '1024',
 767: '1025',
 768: '1026',
 769: '1027',
 770: '1028',
 771: '1029',
 772: '1030',
 773: '1031',
 774: '1032',
 775: '1033',
 776: '1036',
 777: '1038',
 778: '1039',
 779: '1040',
 780: '1041',
 781: '1043',
 782: '1044',
 783: '1045',
 784: '1046',
 785: '1047',
 786: '1048',
 787: '1050',
 788: '1051',
 789: '1052',
 790: '1053',
 791: '1054',
 792: '1056',
 793: '1057',
 794: '1058',
 795: '1059',
 796: '1060',
 797: '1062',
 798: '1063',
 799: '1066',
 800: '1068',
 801: '1069',
 802: '1070',
 803: '1071',
 804: '1072',
 805: '1073',
 806: '1075',
 807: '1080',
 808: '1081',
 809: '1082',
 810: '1084',
 811: '1087',
 812: '1088',
 813: '1089',
 814: '1101',
 815: '1102',
 816: '1103',
 817: '1104',
 818: '1105',
 819: '1106',
 820: '1107',
 821: '1108',
 822: '1109',
 823: '1111',
 824: '1112',
 825: '1113',
 826: '1114',
 827: '1116',
 828: '1117',
 829: '1118',
 830: '1119',
 831: '1120',
 832: '1121',
 833: '1122',
 834: '1123',
 835: '1124',
 836: '1128',
 837: '1129',
 838: '1130',
 839: '1131',
 840: '1132',
 841: '1133',
 842: '1134',
 843: '1135',
 844: '1136',
 845: '1137',
 846: '1138',
 847: '1139',
 848: '1140',
 849: '1141',
 850: '1142',
 851: '1143',
 852: '1144',
 853: '1145',
 854: '1146',
 855: '1147',
 856: '1149',
 857: '1152',
 858: '1153',
 859: '1154',
 860: '1155',
 861: '1158',
 862: '1159',
 863: '1160',
 864: '1161',
 865: '1163',
 866: '1164',
 867: '1173',
 868: '1174',
 869: '1175',
 870: '1176',
 871: '1178',
 872: '1179',
 873: '1180',
 874: '1181',
 875: '1182',
 876: '1183',
 877: '1184',
 878: '1185',
 879: '1186',
 880: '1187',
 881: '1188',
 882: '1191',
 883: '1192',
 884: '1193',
 885: '1195',
 886: '1196',
 887: '1198',
 888: '1200',
 889: '1201',
 890: '1203',
 891: '1207',
 892: '1208',
 893: '1209',
 894: '1211',
 895: '1212',
 896: '1213',
 897: '1215',
 898: '1230',
 899: '1232',
 900: '1233',
 901: '1234',
 902: '1235',
 903: '1236',
 904: '1237',
 905: '1238',
 906: '1240',
 907: '1241',
 908: '1244',
 909: '1258',
 910: '1259',
 911: '1260',
 912: '1261',
 913: '1262',
 914: '1263',
 915: '1264',
 916: '1265',
 917: '1266',
 918: '1267',
 919: '1268',
 920: '1269',
 921: '1270',
 922: '1271',
 923: '1272',
 924: '1277',
 925: '1278',
 926: '1280',
 927: '1281',
 928: '1282',
 929: '1284',
 930: '1285',
 931: '1286',
 932: '1287',
 933: '1288',
 934: '1289',
 935: '1290',
 936: '1291',
 937: '1292',
 938: '1293',
 939: '1294',
 940: '1295',
 941: '1296',
 942: '1297',
 943: '1298',
 944: '1299',
 945: '1300',
 946: '1301',
 947: '1302',
 948: '1303',
 949: '1305',
 950: '1306',
 951: '1307',
 952: '1308',
 953: '1310',
 954: '1311',
 955: '1312',
 956: '1314',
 957: '1315',
 958: '1316',
 959: '1317',
 960: '1318',
 961: '1325',
 962: '1326',
 963: '1327',
 964: '1329',
 965: '1337',
 966: '1339',
 967: '1340',
 968: '1345',
 969: '1346',
 970: '1347',
 971: '1349',
 972: '1350',
 973: '1351',
 974: '1352',
 975: '1353',
 976: '1355',
 977: '1356',
 978: '1357',
 979: '1358',
 980: '1359',
 981: '1360',
 982: '1361',
 983: '1362',
 984: '1363',
 985: '1364',
 986: '1365',
 987: '1366',
 988: '1368',
 989: '1369',
 990: '1370',
 991: '1371',
 992: '1373',
 993: '1374',
 994: '1375',
 995: '1376',
 996: '1378',
 997: '1379',
 998: '1380',
 999: '1381',
 1000: '1382',
 1001: '1384',
 1002: '1385',
 1003: '1386',
 1004: '1387',
 1005: '1388',
 1006: '1389',
 1007: '1390',
 1008: '1392',
 1009: '1393',
 ...}

In [10]:
# zscore_dict = community_central_genes_ranked(graph,communities[comm_idx])

In [11]:
# zscore_dict = dict(sorted(zscore_dict.items(), key=lambda x: x[1], reverse=True))

In [12]:
# zscore_dict

In [13]:
# top_genes = [u for u,v in zscore_dict.items()][:3]

In [14]:
# top_genes

# Community deepdive

In [25]:
comm_idx = 2

In [26]:
comm_HGNC = communities_HGNC_selected[comm_idx]

In [27]:
len(comm_HGNC)

1270

In [28]:
important_terms = pd.read_csv(DISEASE_FOLDER + "important_terms.csv")

In [29]:
go_df_filtered = important_terms[important_terms["Community Index"] == comm_idx]

In [30]:
go_df_filtered = go_df_filtered.sort_values(by = ["Adjusted P-value"], ascending = [True])

In [31]:
go_df_filtered

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,GO_ID,Slim_IDs,Overlap (value),KEGG_ID
97,2,1270,Golgi Membrane (GO:0000139),78/427,2.377760e-15,['cellular anatomical structure'],GO_Cellular_Component_2023,1.595812e-17,0.0,0.0,3.446371,133.293797,GALNT12;SCARB2;GPSM1;GALNT11;GALNT14;ST6GALNAC...,GO:0000139,{'GO:0110165'},0.182670,NaN
103,2,1270,Bounding Membrane Of Organelle (GO:0098588),117/819,5.552438e-15,['cellular anatomical structure'],GO_Cellular_Component_2023,6.373014e-17,0.0,0.0,2.605955,97.180964,SCARB2;GALNT12;GALNT11;GALNT14;KDELR1;PITPNB;S...,GO:0098588,{'GO:0110165'},0.142857,NaN
30,2,1270,RNA Binding (GO:0003723),171/1411,3.366901e-14,['binding'],GO_Molecular_Function_2023,5.163958e-17,0.0,0.0,2.194656,82.304539,OTUD4;TCERG1;RPL31;CISD2;NOC2L;RPL8;MKI67;RRP8...,GO:0003723,{'GO:0005488'},0.121191,NaN
64,2,1270,Protein Glycosylation (GO:0006486),42/147,1.584063e-13,[],GO_Biological_Process_2023,4.623650e-17,0.0,0.0,6.066775,228.188174,GALNT12;GALNT11;GALNT14;ST6GALNAC2;GALNT18;PLO...,GO:0006486,set(),0.285714,NaN
23,2,1270,Metabolism Of RNA R-HSA-8953854,96/666,2.479166e-11,['Metabolism of RNA'],Reactome_2022,2.662906e-14,0.0,0.0,2.605218,81.430719,TUT7;RPL31;DDX47;TUT4;SPPL2A;DDX42;CWC25;YBX1;...,NaN,NaN,0.144144,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2,1270,cullin-RING Ubiquitin Ligase Complex (GO:0031461),26/174,6.679910e-04,['protein-containing complex'],GO_Cellular_Component_2023,4.034845e-05,0.0,0.0,2.624120,26.550736,ANAPC13;DET1;PEF1;CCNF;KLHL12;KLHL13;DDA1;DCAF...,GO:0031461,{'GO:0032991'},0.149425,NaN
41,2,1270,Glycosaminoglycan biosynthesis,13/53,7.100978e-04,[],KEGG_2021_Human,1.981668e-05,0.0,0.0,4.832339,52.329333,HS3ST3B1;GLCE;CSGALNACT2;EXTL2;FUT8;CHST11;DSE...,NaN,NaN,0.245283,NaN
42,2,1270,Glycosphingolipid biosynthesis,12/45,7.100978e-04,[],KEGG_2021_Human,1.652113e-05,0.0,0.0,5.404538,59.508669,B3GALNT1;ST8SIA1;B3GALT4;B3GNT3;B3GNT2;B4GALNT...,NaN,NaN,0.266667,NaN
29,2,1270,Protein Ubiquitination (GO:0016567),52/434,7.427047e-04,['cellular process'],GO_Biological_Process_2023,7.804252e-06,0.0,0.0,2.050602,24.116808,DET1;UBE3C;UBE3D;CCNF;MAGEF1;DDA1;RNF115;UBE2Q...,GO:0016567,{'GO:0009987'},0.119816,NaN
110,2,1270,protein-RNA Complex Assembly (GO:0022618),25/150,7.767248e-04,['cellular process'],GO_Biological_Process_2023,8.388446e-06,0.0,0.0,2.988755,34.934527,YTHDC1;CELF2;CELF3;SRSF1;CELF4;DDX20;NOL3;RBM5...,GO:0022618,{'GO:0009987'},0.166667,NaN

In [32]:
go_df_filtered[go_df_filtered["Gene_set"] == "Reactome_2022"]

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,GO_ID,Slim_IDs,Overlap (value),KEGG_ID
23,2,1270,Metabolism Of RNA R-HSA-8953854,96/666,2.479166e-11,['Metabolism of RNA'],Reactome_2022,2.662906e-14,0.0,0.0,2.605218,81.430719,TUT7;RPL31;DDX47;TUT4;SPPL2A;DDX42;CWC25;YBX1;...,NaN,NaN,0.144144,NaN
18,2,1270,Post-translational Protein Modification R-HSA-...,154/1383,1.217164e-09,['Metabolism of proteins'],Reactome_2022,2.614745e-12,0.0,0.0,1.965022,52.406862,RAB3B;GALNT12;GALNT11;GALNT14;KDELR1;GALNT18;C...,NaN,NaN,0.111352,NaN
26,2,1270,Metabolism Of Proteins R-HSA-392499,193/1890,2.962559e-09,['Metabolism of proteins'],Reactome_2022,9.546376e-12,0.0,0.0,1.798668,45.640937,KDELR1;RPL31;CCNF;RPL8;TFG;LONP2;FBXO6;FBXO9;S...,NaN,NaN,0.102116,NaN
25,2,1270,Membrane Trafficking R-HSA-199991,78/599,2.498259e-07,['Vesicle-mediated transport'],Reactome_2022,1.073366e-09,0.0,0.0,2.287003,47.232251,ITSN2;SCARB2;DENND1B;SCOC;C2CD5;KDELR1;DENND1A...,NaN,NaN,0.130217,NaN
19,2,1270,Vesicle-mediated Transport R-HSA-5653656,78/637,3.186330e-06,['Vesicle-mediated transport'],Reactome_2022,1.711241e-08,0.0,0.0,2.127088,38.039690,ITSN2;SCARB2;DENND1B;SCOC;C2CD5;KDELR1;DENND1A...,NaN,NaN,0.122449,NaN
48,2,1270,Processing Of Capped Intron-Containing Pre-mRN...,40/242,3.692972e-06,['Metabolism of RNA'],Reactome_2022,2.380003e-08,0.0,0.0,2.982854,52.359770,FYTTD1;NUP205;POLDIP3;SF3B6;SRSF1;DDX42;CWC25;...,NaN,NaN,0.165289,NaN
39,2,1270,Intra-Golgi And Retrograde Golgi-to-ER Traffic...,33/181,4.772621e-06,['Vesicle-mediated transport'],Reactome_2022,3.588436e-08,0.0,0.0,3.349461,57.419697,SCOC;NBAS;KDELR1;UBE2Z;BICD1;BICD2;AGPAT3;STX1...,NaN,NaN,0.182320,NaN
46,2,1270,mRNA 3-End Processing R-HSA-72187,17/58,7.613316e-06,['Metabolism of RNA'],Reactome_2022,6.542054e-08,0.0,0.0,6.184435,102.305587,FYTTD1;CHTOP;CPSF7;CPSF6;CPSF1;POLDIP3;SRSF1;U...,NaN,NaN,0.293103,NaN
21,2,1270,Asparagine N-linked Glycosylation R-HSA-446203,43/282,8.278916e-06,['Metabolism of proteins'],Reactome_2022,8.003248e-08,0.0,0.0,2.711355,44.305801,SEC23A;UBXN1;ST6GALNAC2;KDELR1;PRKCSH;UAP1;NEU...,NaN,NaN,0.152482,NaN
47,2,1270,rRNA Modification In Nucleus And Cytosol R-HSA...,17/60,1.004998e-05,['Metabolism of RNA'],Reactome_2022,1.135994e-07,0.0,0.0,5.896156,94.283001,UTP25;DDX47;DIMT1;SPPL2A;HEATR1;WDR75;WDR43;RR...,NaN,NaN,0.283333,NaN
58,2,1270,RNA Polymerase II Transcription Termination R-...,18/67,1.004998e-05,['Gene expression (Transcription)'],Reactome_2022,1.187431e-07,0.0,0.0,5.481157,87.404188,FYTTD1;CHTOP;CPSF7;CPSF6;CPSF1;POLDIP3;SRSF1;U...,NaN,NaN,0.268657,NaN
20,2,1270,RHO GTPase Cycle R-HSA-9012999,57/441,1.928170e-05,['Signal Transduction'],Reactome_2022,2.485288e-07,0.0,0.0,2.245041,34.141921,ITSN2;DOCK5;ANKLE2;DOCK4;PRKCSH;ITSN1;FAF2;ARH...,NaN,NaN,0.129252,NaN
56,2,1270,Glycerophospholipid Biosynthesis R-HSA-1483206,25/127,2.536860e-05,['Metabolism'],Reactome_2022,3.542339e-07,0.0,0.0,3.667218,54.470318,AGPAT5;ABHD3;PRKCSH;PITPNB;LPCAT1;PCTP;PLD6;AG...,NaN,NaN,0.196850,NaN
57,2,1270,Rab Regulation Of Trafficking R-HSA-9007101,24/122,4.067378e-05,['Vesicle-mediated transport'],Reactome_2022,6.116357e-07,0.0,0.0,3.662070,52.393703,DENND1B;RAB4A;ANKRD27;RABGAP1;DENND1A;DENND2A;...,NaN,NaN,0.196721,NaN
38,2,1270,Late SARS-CoV-2 Infection Events R-HSA-9772573,15/58,1.401349e-04,['Disease'],Reactome_2022,2.257813e-06,0.0,0.0,5.194200,67.530385,ST6GALNAC2;PRKCSH;ZDHHC5;MOGS;ZDHHC11;PARP8;FU...,NaN,NaN,0.258621,NaN
55,2,1270,HATs Acetylate Histones R-HSA-3214847,21/106,1.561742e-04,['Chromatin organization'],Reactome_2022,2.696543e-06,0.0,0.0,3.688080,47.294239,DR1;MEAF6;JADE3;YEATS4;JADE2;SUPT7L;TAF5L;SUPT...,NaN,NaN,0.198113,NaN
37,2,1270,rRNA Processing In Nucleus And Cytosol R-HSA-8...,30/189,1.561742e-04,['Metabolism of RNA'],Reactome_2022,3.090298e-06,0.0,0.0,2.825776,35.851307,UTP25;RPL31;DDX47;SPPL2A;HEATR1;RPL8;WDR43;RRP...,NaN,NaN,0.158730,NaN
52,2,1270,Transport Of Mature mRNA Derived From An Intro...,17/74,1.561742e-04,['Metabolism of RNA'],Reactome_2022,2.886951e-06,0.0,0.0,4.444645,56.692824,NDC1;FYTTD1;NUP205;CHTOP;NUP155;POLDIP3;SRSF1;...,NaN,NaN,0.229730,NaN
34,2,1270,rRNA Processing R-HSA-72312,31/199,1.561742e-04,['Metabolism of RNA'],Reactome_2022,3.187229e-06,0.0,0.0,2.764432,34.987640,UTP25;RPL31;DDX47;HEATR1;SPPL2A;RPL8;WDR43;RRP...,NaN,NaN,0.155779,NaN
53,2,1270,Transport Of Mature Transcript To Cytoplasm R-...,18/83,1.672107e-04,['Metabolism of RNA'],Reactome_2022,3.592067e-06,0.0,0.0,4.128410,51.756978,NDC1;FYTTD1;NUP205;CHTOP;CPSF1;NUP155;POLDIP3;...,NaN,NaN,0.216867,NaN
22,2,1270,Chromatin Modifying Enzymes R-HSA-3247509,34/238,3.424458e-04,['Chromatin organization'],Reactome_2022,7.724342e-06,0.0,0.0,2.498112,29.405613,MEAF6;ASH2L;JADE3;YEATS4;JADE2;TAF5L;PHF8;NSD3...,NaN,NaN,0.142857,NaN
54,2,1270,Sphingolipid Metabolism R-HSA-428157,18/89,4.290948e-04,['Metabolism'],Reactome_2022,1.013973e-05,0.0,0.0,3.778315,43.447034,CERS3;CERS4;B3GALNT1;EGFL7;CERS6;CERK;SGMS1;SP...,NaN,NaN,0.202247,NaN
49,2,1270,Sphingolipid De Novo Biosynthesis R-HSA-1660661,12/44,5.202820e-04,['Metabolism'],Reactome_2022,1.285337e-05,0.0,0.0,5.573728,62.770794,CERS3;CERS4;SPTLC1;CERS6;SGMS1;SPTLC2;SPHK2;OR...,NaN,NaN,0.272727,NaN
24,2,1270,"Signaling By Rho GTPases, Miro GTPases And RHO...",70/660,6.241609e-04,['Signal Transduction'],Reactome_2022,1.676050e-05,0.0,0.0,1.793503,19.722228,ITSN2;DOCK5;ANKLE2;DOCK4;PRKCSH;ITSN1;FAF2;ARH...,NaN,NaN,0.106061,NaN
50,2,1270,TBC/RABGAPs R-HSA-8854214,12/45,6.241609e-04,['Vesicle-mediated transport'],Reactome_2022,1.652113e-05,0.0,0.0,5.404538,59.508669,GGA2;RAB43;RAB4A;RABGAP1;TBC1D10C;TBC1D24;TBC1...,NaN,NaN,0.266667,NaN

In [35]:
print(go_df_filtered.to_latex())

\begin{tabular}{lrrllrllrrrrrlllrl}
\toprule
 & Community Index & Community Size & Term & Overlap & Adjusted P-value & Category & Gene_set & P-value & Old P-value & Old Adjusted P-value & Odds Ratio & Combined Score & Genes & GO_ID & Slim_IDs & Overlap (value) & KEGG_ID \\
\midrule
97 & 2 & 1270 & Golgi Membrane (GO:0000139) & 78/427 & 0.000000 & ['cellular anatomical structure'] & GO_Cellular_Component_2023 & 0.000000 & 0.000000 & 0.000000 & 3.446371 & 133.293797 & GALNT12;SCARB2;GPSM1;GALNT11;GALNT14;ST6GALNAC2;KDELR1;PITPNB;ZDHHC5;ZDHHC7;GALNT10;SCAMP5;RAB43;GOLGA5;GLIPR2;DSE;QSOX1;LARGE1;GOLGA7;HS3ST3B1;TMED9;ST6GAL2;COG4;ATG9B;CSGALNACT2;COG2;ZDHHC11;RAB33B;RER1;GORASP2;B3GNT3;B3GNT2;KDELR2;KDELR3;VAMP4;SEC22B;CHST2;B4GALT4;SGMS1;GCNT1;FUT2;FUT4;AGPAT3;SCFD1;FUT8;CHST11;MAN2A2;MAN2A1;LMAN2;MGAT5;PDGFC;CHST15;GCNT3;B4GALNT1;CD59;MGAT1;MGAT2;CYTH1;FKTN;GALNT7;B3GALNT1;GALNT6;GALNT5;GALNT4;ST8SIA1;SURF4;B3GALT4;B3GALT5;B4GAT1;ZDHHC9;DOP1B;MGAT4A;C6ORF89;UST;MGAT4B;ACER3;TRIP11;CHPT1 & GO:0000139 & {'GO:0110165'} & 0.182670 & NaN \\
103 & 2 & 1270 & Bounding Membrane Of Organelle (GO:0098588) & 117/819 & 0.000000 & ['cellular anatomical structure'] & GO_Cellular_Component_2023 & 0.000000 & 0.000000 & 0.000000 & 2.605955 & 97.180964 & SCARB2;GALNT12;GALNT11;GALNT14;KDELR1;PITPNB;SPPL2A;ZDHHC5;ZDHHC7;ANTXR1;GALNT10;SCAMP5;RAB43;GOLGA5;LAMP1;ANKFY1;LARGE1;GOLGA7;ST6GAL2;CD93;ATG9B;COG4;VPS33B;CSGALNACT2;COG2;TYROBP;KDELR2;KDELR3;ATP6V0D1;TSG101;TTYH1;LY96;VPS26A;IQGAP2;FUT2;FUT4;SNX3;FUT8;SCFD1;CHST11;MAN2A2;MAN2A1;PDGFC;CHST15;VPS11;ATP6V0A2;B4GALNT1;B3GALNT1;ST8SIA1;SURF4;B3GALT4;B3GALT5;CHERP;B4GAT1;C6ORF89;UST;ACER3;GPSM1;ST6GALNAC2;ARHGAP1;SLC2A3;GLIPR2;CHMP1B;DSE;QSOX1;HS3ST3B1;TMED9;ATP6AP1;VPS13A;RHOF;ZDHHC11;RAB33B;BACE1;RER1;GORASP2;TMBIM1;B3GNT3;B3GNT2;VAMP4;SEC22B;ATP6V0C;CHST2;B4GALT4;SGMS1;GCNT1;AGPAT3;TMEM165;GGA2;MGAT5;LMAN2;ORMDL3;GCNT3;CD59;MGAT1;MGAT2;EMC6;CYTH1;FKTN;GALNT7;GALNT6;GALNT5;GALNT4;WNT7B;SVIP;TPCN2;TPCN1;MYO1B;FABP5;ZDHHC9;SNX17;DOP1B;MGAT4A;MGAT4B;VPS41;RAB18;TRIP11;CHPT1 & GO:0098588 & {'GO:0110165'} & 0.142857 & NaN \\
30 & 2 & 1270 & RNA Binding (GO:0003723) & 171/1411 & 0.000000 & ['binding'] & GO_Molecular_Function_2023 & 0.000000 & 0.000000 & 0.000000 & 2.194656 & 82.304539 & OTUD4;TCERG1;RPL31;CISD2;NOC2L;RPL8;MKI67;RRP8;ALKBH8;RRP9;THG1L;LSM10;EIF4ENIF1;FBL;ALKBH5;HMGN5;RBMX2;SNIP1;MTREX;CPNE3;UBAP2L;KPNA2;RBFOX2;MBNL2;SCAF11;DIMT1;WDR75;ALG13;ANXA11;LARP4B;THOC2;THOC5;PUS7;RC3H2;XRN1;CLNS1A;SARNP;NHP2;GEMIN5;MATR3;PPIG;FKBP4;DDX6;UTP25;PEF1;YTHDC1;YTHDC2;NOLC1;NMD3;DDX60;GIGYF2;GSPT1;PRDX1;DHX37;UTP20;MAP4;N4BP1;ZC3H15;TIA1;CHTOP;CPSF7;CPSF6;RPP40;HMGA1;PYM1;LARP7;UPF3B;UPF3A;H1-0;LARP6;PARP12;CHERP;PUM2;HNRNPL;EIF5;TBL2;HNRNPK;HNRNPF;TRIP6;MPHOSPH10;NOL11;LSM14A;CPEB2;RPS21;NOP10;TUT7;RBM26;DDX47;FASTKD2;TUT4;CELF2;CELF3;CELF4;DDX42;YBX1;WDR43;AFF2;SYNE1;DUSP11;RO60;FASTK;ANXA7;WDR6;TNPO1;METTL16;RBM5;EIF5B;RBM14;RBM15;NSUN2;GNL3;PKM;SYF2;HNRNPH1;SDE2;LUC7L3;ETF1;NCBP3;PABPC1;EIF4E2;NSRP1;RBM22;FYTTD1;CSTB;POLDIP3;SF3B6;SRSF1;HEATR1;DDX20;PARN;NOL8;NOL3;AKAP1;NXF1;RIDA;GANAB;RBM15B;EXOSC10;TCOF1;PABPN1;RPL13;RPS2;ASCC3;EXOSC3;RPP14;RAE1;CFAP20;RPL19;RBM38;RBM39;DUT;YTHDF1;TRMT10C;SSB;TAF15;GPKOW;YTHDF3;RFTN1;SAMD4A;SRP68;BICC1;KRT18;EIF3L;PRKRA;EIF3I;TRMT6;EIF3G;EIF3H;EIF3E;BUD13;EIF3D & GO:0003723 & {'GO:0005488'} & 0.121191 & NaN \\
64 & 2 & 1270 & Protein Glycosylation (GO:0006486) & 42/147 & 0.000000 & [] & GO_Biological_Process_2023 & 0.000000 & 0.000000 & 0.000000 & 6.066775 & 228.188174 & GALNT12;GALNT11;GALNT14;ST6GALNAC2;GALNT18;PLOD2;PLOD1;FUT2;TRAK1;GALNT10;FUT4;TMEM165;FUT8;MGAT5;MGAT5B;GCNT3;MGAT1;MGAT2;LARGE1;FKTN;B3GALNT2;GALNT7;B3GALNT1;GALNT6;GALNT5;GALNT4;ST8SIA1;ALG5;B3GALT4;ALG3;MOGS;B3GALT5;ALG10;POMGNT2;TMEM59;B4GAT1;MGAT4A;MGAT4B;STT3A;B3GNT3;POMK;B3GNT2 & GO:0006486 & set() & 0.285714 & NaN \\
23 & 2 & 1270 & Metabolism Of RNA R-HSA-8953854 & 96/666 & 0.000000 & ['Metabolism of RNA'] & Reactome_2022 & 0.000000 & 0.000000 & 0.000000 & 2.605218 & 81.430719 & TUT7;RPL31;DDX47;TUT4;SPPL2A;DDX42;CWC25;YBX1;RPL8;WDR43;ALKBH8;RRP9;THG1L;LSM10;FBL;PAPOLA;RIOK2;MTREX;RIOK1;TNPO1;RBM5;NDC1;DIMT1;NSUN2;WDR75;THOC3;TFIP11;THOC2;PLRG1;THOC5;PUS7;THOC7;GNL3;THOC6;SKIC8;XRN1;SYF2;HNRNPH1;CLNS1A;SARNP;NHP2;GEMIN4;CD2BP2;GEMIN5;ETF1;GEMIN6;PABPC1;SLU7;RBM22;FYTTD1;DDX6;UTP25;NUP205;POLDIP3;SF3B6;SRSF1;HEATR1;DDX20;PARN;GSPT1;NXF1;EXOSC10;PABPN1;GAR1;DHX37;UTP20;RPS2;EXOSC3;RPP14;RPL19;CHTOP;CPSF7;TRMT10C;CPSF6;GPKOW;CPSF1;NUP155;WTAP;RPP40;UPF3B;UPF3A;NUP153;WDR12;CHERP;PNRC2;HNRNPL;HNRNPK;HNRNPF;CNOT2;TRMT6;MPHOSPH10;NOL11;TRMT61A;RPS21;NOP10;TRMT61B & NaN & NaN & 0.144144 & NaN \\
60 & 2 & 1270 & Intracellular Non-Membrane-Bounded Organelle (GO:0043232) & 139/1195 & 0.000000 & ['cellular anatomical structure'] & GO_Cellular_Component_2023 & 0.000000 & 0.000000 & 0.000000 & 2.056947 & 56.073800 & MAPKBP1;FHOD1;NOC2L;MKI67;RRP8;RRP9;FBL;NSDHL;RBMX2;ARHGDIA;ARHGDIB;ARFIP2;CPNE3;SCAF11;DIMT1;PIH1D1;KRT1;ZFP69B;WDR74;WDR75;ANXA11;LDOC1;LARP4B;SDCBP2;EML3;TRAIP;CCNY;BIN2;GEMIN4;KIF20B;ATF3;MAD1L1;IPPK;UTP25;CDCA2;TSG101;MEAF6;TXK;NOLC1;XPC;NMD3;ABHD5;AK5;BCL2L10;MBIP;DHX37;CAMTA1;LPXN;UTP20;N4BP1;MARK1;PLK4;PYM1;UPF3B;NUP153;UPF3A;ELL3;UBLCP1;UVSSA;C6ORF89;TRIP6;MPHOSPH10;INTS7;NOL11;CEP85;FERMT3;DYRK3;FEN1;DOCK4;MCM7;DDX47;TUT4;FAF2;HILPDA;LPCAT1;SIX1;CTCF;BICD1;MYSM1;WDR43;PHF8;SYNE1;SFR1;SH3PXD2B;SPIN1;UBXN8;PRMT6;NSUN2;CEP295;VPS13C;VPS13A;TFIP11;RHOF;DYNLL1;GNL3;ITPKB;KIF9;ITPKA;ERGIC2;PAFAH1B2;AGPAT5;CSTB;RGS14;MVP;HEATR1;DDX20;PARN;TULP3;NOL8;PPM1D;FBXL22;RBM15B;EXOSC10;TCOF1;RBBP5;PPP1R7;BEND3;RPL13;RPS2;EXOSC3;RPP14;PDLIM4;E2F8;RPL19;TRIM41;TAF15;NAA10;SRP68;WDR12;YY1AP1;HINFP;VMP1;MYO1E;NIN;SCD;RAB18;TAF5;TRIP13;ZPR1 & GO:0043232 & {'GO:0110165'} & 0.116318 & NaN \\
18 & 2 & 1270 & Post-translational Protein Modification R-HSA-597592 & 154/1383 & 0.000000 & ['Metabolism of proteins'] & Reactome_2022 & 0.000000 & 0.000000 & 0.000000 & 1.965022 & 52.406862 & RAB3B;GALNT12;GALNT11;GALNT14;KDELR1;GALNT18;CCNF;UBE2Z;TOMM20;GALNT10;RAB43;TFG;FBXO6;LARGE1;FBXO9;PIAS3;ST6GAL2;USP5;COG4;ALG5;COG2;ALG3;ALG13;MOGS;FBXO10;KCTD6;RAB32;CD109;FKBP8;KDELR2;KDELR3;LY6E;NUP205;CTR9;DCUN1D1;UAP1;XPC;KLHL13;SOCS2;SNX3;NEU3;FUT8;SCFD1;MAN2A2;ATXN7;MAN2A1;ADAMTS18;TMEM129;SEC31A;SOCS5;B3GALNT2;SEC16B;RAB4A;KLHL25;NUP155;ST8SIA1;KLHL21;RAB39B;RAB27B;NUP153;STAM;FBXO31;PUM2;NR4A2;TF;RNF103;HNRNPK;H2AC25;B4GAT1;TADA3;STT3A;UBA2;FBXL3;MELTF;FBXL5;COPS8;SAE1;UBE2M;ST6GALNAC2;WDR48;UBXN1;GPAA1;PRKCSH;MYSM1;RAB22A;DDA1;PPP6C;ING3;GNPNAT1;QSOX1;RAB8B;NDC1;TMED9;EGFL7;USP42;AHSG;PRMT3;ANO8;FOXL2;DYNLL1;COMMD6;UCHL3;POMGNT2;RAD23B;COMMD7;RAB33B;SENP1;SKIC8;WAC;B3GNT3;B3GNT2;MVD;SEC22B;RAB7B;B4GALT4;OTUB1;SEC23A;GCNT1;USP12;METTL21A;FSTL1;TTL;USP18;FBXL22;RAB21;GANAB;CAND1;RAB25;RBBP5;MGAT5;TDG;LMAN2;SVBP;LEO1;GCNT3;CD59;RPS2;IL33;GALNT6;SEC24B;GALNT5;USP20;FBXL14;SGPP2;KLHL9;MGAT4A;ASB9;MGAT4B;RAB18;POMK;SEC24C;KBTBD8;SPSB4;OTUD3 & NaN & NaN & 0.111352 & NaN \\
33 & 2 & 1270 & Nucleolus (GO:0005730) & 98/771 & 0.000000 & ['cellular anatomical structure'] & GO_Cellular_Component_2023 & 0.000000 & 0.000000 & 0.000000 & 2.243515 & 54.451641 & MAPKBP1;NOC2L;MKI67;RRP8;RRP9;FBL;RBMX2;ARFIP2;CPNE3;SCAF11;DIMT1;PIH1D1;ZFP69B;WDR74;WDR75;LDOC1;LARP4B;SDCBP2;TRAIP;CCNY;GEMIN4;KIF20B;ATF3;IPPK;UTP25;TSG101;MEAF6;TXK;NOLC1;XPC;NMD3;AK5;MBIP;DHX37;CAMTA1;UTP20;N4BP1;PLK4;PYM1;UPF3B;NUP153;UPF3A;ELL3;UBLCP1;C6ORF89;MPHOSPH10;NOL11;CEP85;FEN1;DOCK4;MCM7;DDX47;TUT4;SIX1;CTCF;MYSM1;WDR43;PHF8;SYNE1;SFR1;SPIN1;UBXN8;PRMT6;NSUN2;TFIP11;GNL3;ERGIC2;PAFAH1B2;AGPAT5;CSTB;HEATR1;PARN;TULP3;NOL8;PPM1D;FBXL22;RBM15B;EXOSC10;TCOF1;RBBP5;BEND3;RPL13;RPS2;EXOSC3;RPP14;E2F8;RPL19;TRIM41;TAF15;NAA10;WDR12;YY1AP1;HINFP;VMP1;NIN;SCD;TAF5;ZPR1 & GO:0005730 & {'GO:0110165'} & 0.127108 & NaN \\
32 & 2 & 1270 & Nuclear Lumen (GO:0031981) & 98/780 & 0.000000 & ['cellular anatomical structure'] & GO_Cellular_Component_2023 & 0.000000 & 0.000000 & 0.000000 & 2.212805 & 52.246610 & MAPKBP1;NOC2L;MKI67;RRP8;RRP9;FBL;RBMX2;ARFIP2;CPNE3;SCAF11;DIMT1;PIH1D1;ZFP69B;WDR74;WDR75;LDOC1;LARP4B;SDCBP2;TRAIP;CCNY;GEMIN4;KIF20B;ATF3;IPPK;UTP25;TSG101;MEAF6;TXK;NOLC1;XPC;NMD3;AK5;MBIP;DHX37;CAMTA1;UTP20;N4BP1;PLK4;PYM1;UPF3B;NUP153;UPF3A;ELL3;UBLCP1;C6ORF89;MPHOSPH10;NOL11;CEP85;FEN1;DOCK4;MCM7;DDX47;TUT4;SIX1;CTCF;MYSM1;WDR43;PHF8;SYNE1;SFR1;SPIN1;UBXN8;PRMT6;NSUN2;TFIP11;GNL3;ERGIC2;PAFAH1B2;AGPAT5;CSTB;HEATR1;PARN;TULP3;NOL8;PPM1D;FBXL22;RBM15B;EXOSC10;TCOF1;RBBP5;BEND3;RPL13;RPS2;EXOSC3;RPP14;E2F8;RPL19;TRIM41;TAF15;NAA10;WDR12;YY1AP1;HINFP;VMP1;NIN;SCD;TAF5;ZPR1 & GO:0031981 & {'GO:0110165'} & 0.125641 & NaN \\
26 & 2 & 1270 & Metabolism Of Proteins R-HSA-392499 & 193/1890 & 0.000000 & ['Metabolism of proteins'] & Reactome_2022 & 0.000000 & 0.000000 & 0.000000 & 1.798668 & 45.640937 & KDELR1;RPL31;CCNF;RPL8;TFG;LONP2;FBXO6;FBXO9;ST6GAL2;COG4;ALG5;COG2;ALG3;MOGS;CD109;KDELR2;KDELR3;NUP205;CTR9;DCUN1D1;XPC;GSPT1;SNX3;NEU3;SCFD1;ADAMTS18;SEC31A;B3GALNT2;ST8SIA1;RAB39B;RAB27B;STAM;PUM2;TF;EIF5;RNF103;HNRNPK;H2AC25;B4GAT1;FBXL3;FBXL5;RPS21;WDR48;UBXN1;GPAA1;RAB22A;DDA1;ING3;C1QTNF1;GNPNAT1;QSOX1;RAB8B;NDC1;TMED9;AHSG;PRMT3;ANO8;DYNLL1;COMMD6;UCHL3;COMMD7;RAB33B;MMP12;BACE1;WAC;B3GNT3;B3GNT2;PABPC1;RAB7B;GCNT1;METTL21A;FSTL1;GGA2;MGAT5;LMAN2;LEO1;GCNT3;CD59;RPS2;RPL19;IL33;SRP68;SNCAIP;KLHL9;KBTBD8;SPSB4;RAB3B;GALNT12;GALNT11;GALNT14;GALNT18;UBE2Z;TOMM20;GALNT10;RAB43;LARGE1;PIAS3;USP5;IGFBP2;ALG13;FBXO10;KCTD6;RAB32;FKBP8;LY6E;UAP1;KLHL13;SOCS2;FUT8;MAN2A2;ATXN7;MAN2A1;TMEM129;SOCS5;SEC16B;EIF2B4;EIF2B3;RAB4A;KLHL25;NUP155;KLHL21;NUP153;INHBB;FBXO31;NR4A2;TADA3;TBCE;STT3A;UBA2;MELTF;COPS8;SAE1;UBE2M;ST6GALNAC2;PRKCSH;MYSM1;SEC61A1;PPP6C;EIF2B1;EIF5B;EGFL7;USP42;VBP1;FOXL2;POMGNT2;RAD23B;SENP1;SKIC8;EEF1D;PFDN1;ETF1;MVD;PFDN2;SEC22B;PFDN4;B4GALT4;PFDN6;OTUB1;SEC23A;USP12;TTL;USP18;FBXL22;RAB21;GANAB;CAND1;RAB25;RBBP5;TDG;SVBP;H2AZ1;GALNT6;SEC24B;GALNT5;USP20;FBXL14;SGPP2;TSPAN15;EIF3K;EIF3L;EIF3I;MGAT4A;ASB9;MGAT4B;EIF3G;RAB18;POMK;EIF3H;EIF3E;SEC24C;EIF3D;EIF3A;OTUD3 & NaN & NaN & 0.102116 & NaN \\
68 & 2 & 1270 & Protein O-linked Glycosylation (GO:0006493) & 28/93 & 0.000000 & ['cellular process'] & GO_Biological_Process_2023 & 0.000000 & 0.000000 & 0.000000 & 6.473678 & 174.814695 & GALNT12;GALNT11;GALNT14;ST6GALNAC2;GALNT18;GCNT1;TMTC3;PLOD2;PLOD1;TRAK1;GALNT10;MGAT5B;GCNT3;LARGE1;FKTN;B3GALNT2;GALNT7;B3GALNT1;GALNT6;GALNT5;GALNT4;B3GALT4;B3GALT5;POMGNT2;B4GAT1;B3GNT3;POMK;B3GNT2 & GO:0006493 & {'GO:0009987'} & 0.301075 & NaN \\
73 & 2 & 1270 & Endosomal Transport (GO:0016197) & 39/180 & 0.000000 & ['localization', 'cellular process'] & GO_Biological_Process_2023 & 0.000000 & 0.000000 & 0.000000 & 4.176798 & 105.932796 & ITSN2;WASHC4;DENND1B;STX12;DENND1A;ITSN1;CLEC16A;VPS26C;ARHGAP1;SNX12;VPS26A;SNX33;STX10;RAB43;SNX3;AP5M1;SNX27;BLOC1S2;CHMP1B;MICALL1;VPS52;TBC1D10C;ANKFY1;DENND5A;ANXA8;ENTR1;TBC1D17;AP5S1;CCDC93;EPS15;TBC1D10A;TBC1D10B;ANKRD27;DENND2A;BLTP1;ARL4C;SNX17;TMCC1;VAMP4 & GO:0016197 & {'GO:0051179', 'GO:0009987'} & 0.216667 & NaN \\
111 & 2 & 1270 & mRNA Binding (GO:0003729) & 49/282 & 0.000000 & ['binding'] & GO_Molecular_Function_2023 & 0.000000 & 0.000000 & 0.000000 & 3.185853 & 73.095249 & CELF2;CELF3;CELF4;EIF4ENIF1;SNIP1;RBM5;RBFOX2;RBM15;LARP4B;THOC2;THOC5;GNL3;PKM;GEMIN5;LUC7L3;ETF1;NCBP3;PABPC1;NSRP1;FYTTD1;DDX6;YTHDC1;POLDIP3;SF3B6;SRSF1;PARN;NOL3;RBM15B;RIDA;RPS2;N4BP1;YTHDF1;CHTOP;CPSF7;TIA1;CPSF6;SSB;YTHDF3;SAMD4A;LARP7;UPF3B;UPF3A;LARP6;PUM2;HNRNPL;HNRNPK;CPEB2;LSM14A;EIF3D & GO:0003729 & {'GO:0005488'} & 0.173759 & NaN \\
77 & 2 & 1270 & Golgi Vesicle Transport (GO:0048193) & 40/197 & 0.000000 & ['localization', 'cellular process'] & GO_Biological_Process_2023 & 0.000000 & 0.000000 & 0.000000 & 3.847134 & 91.694468 & NBAS;SAR1A;KDELR1;PEF1;PITPNB;SNX12;KLHL12;BICD2;STX10;SNX3;RAB43;GOLGA4;SCFD1;GOLGA5;TFG;LMAN2;TMED5;SEC31A;RAB8B;SEC16B;TMED9;SEC24B;COG4;SURF4;COG2;TRAPPC8;SCAMP1;RAB33B;MYO1B;RER1;SPIRE2;TRIP11;SPIRE1;KDELR2;KDELR3;RAB7B;SEC22B;ERGIC2;SEC24C;ERGIC1 & GO:0048193 & {'GO:0051179', 'GO:0009987'} & 0.203046 & NaN \\
40 & 2 & 1270 & RNA transport & 37/186 & 0.000000 & [] & KEGG_2021_Human & 0.000000 & 0.000000 & 0.000000 & 3.742152 & 80.651916 & NUP205;DDX20;SUMO4;NMD3;NXF1;EIF2B1;RPP14;RAE1;NDC1;EIF2B4;EIF5B;EIF2B3;NUP155;RPP40;PYM1;UPF3B;THOC3;NUP153;UPF3A;THOC2;THOC5;THOC7;THOC6;EIF5;CLNS1A;EIF3I;GEMIN4;EIF3G;TACC3;GEMIN5;EIF3H;GEMIN6;EIF3E;PABPC1;EIF4E2;EIF3D;EIF3A & NaN & NaN & 0.198925 & NaN \\
25 & 2 & 1270 & Membrane Trafficking R-HSA-199991 & 78/599 & 0.000000 & ['Vesicle-mediated transport'] & Reactome_2022 & 0.000000 & 0.000000 & 0.000000 & 2.287003 & 47.232251 & ITSN2;SCARB2;DENND1B;SCOC;C2CD5;KDELR1;DENND1A;ITSN1;UBE2Z;BICD1;BICD2;RAB43;PPP6C;GOLGA4;TFG;GJA5;TBC1D10C;ARFIP2;DENND5A;TBC1D10A;TBC1D10B;RAB8B;TMED9;COG4;DENND2A;COG2;DYNLL1;RAB33B;RAB32;KIF9;TBC1D24;KDELR2;KDELR3;VAMP4;SEC22B;KIF20B;RAB7B;PAFAH1B2;NBAS;SEC23A;RABGAP1;TSG101;AGPAT3;STX10;GGA2;RAB21;SCFD1;KIF3B;MAN2A2;KIF3A;MAN2A1;LMAN2;VPS52;CD59;TBC1D17;EPS15;CYTH1;UBQLN2;SEC31A;SEC16B;RAB4A;SEC24B;ANKRD27;SURF4;HPS4;RAB39B;TRAPPC8;RAB27B;SYNJ2;STAM;MYO1E;GJB2;TF;AKR1B10;RAB18;TRIP11;COPS8;SEC24C & NaN & NaN & 0.130217 & NaN \\
44 & 2 & 1270 & N-Glycan biosynthesis & 17/50 & 0.000001 & ['Glycan biosynthesis and metabolism'] & KEGG_2021_Human & 0.000000 & 0.000000 & 0.000000 & 7.686982 & 146.483364 & ST6GAL2;ALG5;ALG13;ALG3;MOGS;ALG10;FUT8;GANAB;MAN2A2;MAN2A1;MGAT5;MGAT5B;MGAT4A;MGAT4B;STT3A;MGAT1;MGAT2 & NaN & NaN & 0.340000 & hsa00510 \\
102 & 2 & 1270 & Vesicle-Mediated Transport (GO:0016192) & 60/411 & 0.000001 & ['localization', 'cellular process'] & GO_Biological_Process_2023 & 0.000000 & 0.000000 & 0.000000 & 2.596454 & 53.173637 & ITSN2;WASHC4;DENND1B;DENND1A;ITSN1;ARHGAP1;RAB22A;EEA1;RAB43;GOLGA4;ZFYVE27;GOLGA5;DPYSL2;CHMP1B;ANKFY1;ANXA8;GPRASP1;AP5S1;CSNK1G3;RUBCN;STX8;STX7;VPS33B;RHOJ;KXD1;RAB7B;CSNK1G1;STX12;TSG101;MGRN1;TGFBRAP1;CLEC16A;SNX33;TRAK1;LRP8;STX10;AP5M1;SNX27;RAB25;BLOC1S2;FHIP1B;MICALL1;VPS11;EPS15;CYTH1;EXPH5;RAB4A;RAB39B;RAB27B;HOOK3;BLTP1;MYO1E;SNX16;HOOK2;SNX17;VPS41;SPIRE2;SPIRE1;MITD1;TMCC1 & GO:0016192 & {'GO:0051179', 'GO:0009987'} & 0.145985 & NaN \\
78 & 2 & 1270 & Endocytic Recycling (GO:0032456) & 20/64 & 0.000001 & ['localization', 'cellular process'] & GO_Biological_Process_2023 & 0.000000 & 0.000000 & 0.000000 & 6.794909 & 139.000817 & DENND1B;STX12;ANKRD27;ATP6AP1;DENND1A;SNX12;VPS26C;VPS26A;SNX33;BLTP1;ARL4C;SNX3;SNX27;SNX17;MICALL1;VPS52;ENTR1;VAMP4;CCDC93;EPS15 & GO:0032456 & {'GO:0051179', 'GO:0009987'} & 0.312500 & NaN \\
36 & 2 & 1270 & Endoplasmic Reticulum Membrane (GO:0005789) & 92/801 & 0.000001 & ['cellular anatomical structure'] & GO_Cellular_Component_2023 & 0.000000 & 0.000000 & 0.000000 & 1.985067 & 35.116508 & SCARB2;GPSM1;ANKLE2;TMEM41B;ARL6IP1;KDELR1;GPAA1;PITPNB;SPPL2A;LPCAT1;CISD2;PLOD2;PLOD1;TM7SF2;SEC61A1;NSDHL;ZFYVE27;SPTLC1;SPTLC2;UBXN8;ANXA7;CERS3;VKORC1;CERS4;TMED9;PCYT2;CERS6;VPS13C;ATG9B;ALG5;VPS13A;ALG3;ALG13;MOGS;DNAJB14;VRK2;POMGNT2;TMX2;TMX1;GORASP2;KDELR2;KDELR3;SEC22B;MGLL;CERS2;AGPAT5;SEC23A;NDRG4;TTYH1;INSIG2;UBA5;FITM2;SRI;AGPAT3;AGPAT4;EXTL2;NCLN;TP53INP2;LMAN2;ADGRG6;TMEM129;HAS2;CD59;GPAT3;EMC6;EXTL3;PDZD8;SEC31A;FDFT1;B3GALNT2;SEC24B;MBOAT7;SURF4;MBOAT1;MBOAT2;SVIP;SGPP2;CHERP;VMP1;ERP44;TBL2;RNF103;SCD;LPCAT3;ACER3;STT3A;RAB18;POMK;CHPT1;TMEM39A;SEC24C;CDS2 & GO:0005789 & {'GO:0110165'} & 0.114856 & NaN \\
89 & 2 & 1270 & Acetylglucosaminyltransferase Activity (GO:0008375) & 15/40 & 0.000002 & ['catalytic activity'] & GO_Molecular_Function_2023 & 0.000000 & 0.000000 & 0.000000 & 8.942629 & 165.651651 & GCNT1;POMGNT2;EXTL2;B4GAT1;MGAT5;MGAT5B;MGAT4A;MGAT4B;B3GNT3;GCNT3;B3GNT2;MGAT1;MGAT2;LARGE1;EXTL3 & GO:0008375 & {'GO:0003824'} & 0.375000 & NaN \\
19 & 2 & 1270 & Vesicle-mediated Transport R-HSA-5653656 & 78/637 & 0.000003 & ['Vesicle-mediated transport'] & Reactome_2022 & 0.000000 & 0.000000 & 0.000000 & 2.127088 & 38.039690 & ITSN2;SCARB2;DENND1B;SCOC;C2CD5;KDELR1;DENND1A;ITSN1;UBE2Z;BICD1;BICD2;RAB43;PPP6C;GOLGA4;TFG;GJA5;TBC1D10C;ARFIP2;DENND5A;TBC1D10A;TBC1D10B;RAB8B;TMED9;COG4;DENND2A;COG2;DYNLL1;RAB33B;RAB32;KIF9;TBC1D24;KDELR2;KDELR3;VAMP4;SEC22B;KIF20B;RAB7B;PAFAH1B2;NBAS;SEC23A;RABGAP1;TSG101;AGPAT3;STX10;GGA2;RAB21;SCFD1;KIF3B;MAN2A2;KIF3A;MAN2A1;LMAN2;VPS52;CD59;TBC1D17;EPS15;CYTH1;UBQLN2;SEC31A;SEC16B;RAB4A;SEC24B;ANKRD27;SURF4;HPS4;RAB39B;TRAPPC8;RAB27B;SYNJ2;STAM;MYO1E;GJB2;TF;AKR1B10;RAB18;TRIP11;COPS8;SEC24C & NaN & NaN & 0.122449 & NaN \\
48 & 2 & 1270 & Processing Of Capped Intron-Containing Pre-mRNA R-HSA-72203 & 40/242 & 0.000004 & ['Metabolism of RNA'] & Reactome_2022 & 0.000000 & 0.000000 & 0.000000 & 2.982854 & 52.359770 & FYTTD1;NUP205;POLDIP3;SF3B6;SRSF1;DDX42;CWC25;YBX1;NXF1;PABPN1;PAPOLA;MTREX;RBM5;NDC1;CHTOP;CPSF7;CPSF6;CPSF1;NUP155;GPKOW;WTAP;UPF3B;THOC3;NUP153;TFIP11;THOC2;PLRG1;THOC5;THOC7;THOC6;CHERP;HNRNPL;HNRNPK;HNRNPH1;SYF2;SARNP;HNRNPF;CD2BP2;SLU7;RBM22 & NaN & NaN & 0.165289 & NaN \\
39 & 2 & 1270 & Intra-Golgi And Retrograde Golgi-to-ER Traffic R-HSA-6811442 & 33/181 & 0.000005 & ['Vesicle-mediated transport'] & Reactome_2022 & 0.000000 & 0.000000 & 0.000000 & 3.349461 & 57.419697 & SCOC;NBAS;KDELR1;UBE2Z;BICD1;BICD2;AGPAT3;STX10;RAB43;GOLGA4;KIF3B;MAN2A2;KIF3A;MAN2A1;VPS52;ARFIP2;CYTH1;TMED9;COG4;SURF4;COG2;DYNLL1;RAB33B;KIF9;AKR1B10;RAB18;TRIP11;KDELR2;KDELR3;KIF20B;SEC22B;VAMP4;PAFAH1B2 & NaN & NaN & 0.182320 & NaN \\
61 & 2 & 1270 & Endosome Membrane (GO:0010008) & 50/361 & 0.000005 & ['cellular anatomical structure'] & GO_Cellular_Component_2023 & 0.000000 & 0.000000 & 0.000000 & 2.427257 & 37.919689 & SCARB2;WASHC4;ARHGAP1;SNX12;ANTXR1;SCAMP5;ZFYVE27;LAMP1;CHMP1B;ANKFY1;ANXA8;RAB8B;ATP6AP1;ATG9B;VPS33B;VPS13A;ZDHHC11;SCAMP1;BACE1;CLIP3;RNF167;RAP2B;TMBIM1;ATP6V0D1;RAB7B;ATP6V0C;TSG101;CLEC16A;LY96;VPS26A;ABHD6;TMEM165;SNX3;GGA2;RAB21;NEU3;MICALL1;ATP6V0A2;VPS11;RAB4A;TMEM30A;TPCN2;RMC1;TPCN1;MYO1B;SNX16;SNX17;DOP1B;CD207;VPS41 & GO:0010008 & {'GO:0110165'} & 0.138504 & NaN \\
112 & 2 & 1270 & Small GTPase Binding (GO:0031267) & 35/199 & 0.000006 & ['binding'] & GO_Molecular_Function_2023 & 0.000000 & 0.000000 & 0.000000 & 3.208305 & 54.989391 & DOCK5;DOCK4;RABGAP1;ARHGAP1;IQGAP2;BICD1;FGD1;BICD2;GGA2;GOLGA4;GOLGA5;PARD6A;KIF3B;KIF3A;MICALL1;ARHGDIB;TBC1D30;ANKFY1;ARFIP2;DENND5A;KNTC1;EVI5L;EXPH5;RABGAP1L;ANKRD27;ATP6AP1;SPHK2;ARHGEF16;HPS4;RHOH;NUTF2;MYO9B;CYRIB;CDC42EP1;TRIP11 & GO:0031267 & {'GO:0005488'} & 0.175879 & NaN \\
46 & 2 & 1270 & mRNA 3-End Processing R-HSA-72187 & 17/58 & 0.000008 & ['Metabolism of RNA'] & Reactome_2022 & 0.000000 & 0.000000 & 0.000000 & 6.184435 & 102.305587 & FYTTD1;CHTOP;CPSF7;CPSF6;CPSF1;POLDIP3;SRSF1;UPF3B;THOC3;THOC2;THOC5;THOC7;THOC6;PABPN1;SARNP;PAPOLA;SLU7 & NaN & NaN & 0.293103 & NaN \\
62 & 2 & 1270 & Histone Acetylation (GO:0016573) & 18/60 & 0.000008 & [] & GO_Biological_Process_2023 & 0.000000 & 0.000000 & 0.000000 & 6.397079 & 114.097852 & DR1;MEAF6;YEATS4;SUPT3H;SUPT7L;TAF5L;TAF6L;ING3;TADA2A;YEATS2;ATXN7;TADA3;MBIP;EPC1;TAF6;BRD8;TAF5;TAF2 & GO:0016573 & set() & 0.300000 & NaN \\
71 & 2 & 1270 & Regulation Of RNA Splicing (GO:0043484) & 24/102 & 0.000008 & ['biological regulation'] & GO_Biological_Process_2023 & 0.000000 & 0.000000 & 0.000000 & 4.606001 & 82.430912 & RBM38;RBM39;TIA1;MBNL2;YTHDC1;SRSF1;LARP7;CLK4;SUPT7L;TAF5L;SUPT3H;CLK2;CLK1;HNRNPL;TAF6L;HNRNPK;ATXN7;HNRNPH1;HNRNPF;FASTK;TADA3;METTL16;RBM22;ZPR1 & GO:0043484 & {'GO:0065007'} & 0.235294 & NaN \\
21 & 2 & 1270 & Asparagine N-linked Glycosylation R-HSA-446203 & 43/282 & 0.000008 & ['Metabolism of proteins'] & Reactome_2022 & 0.000000 & 0.000000 & 0.000000 & 2.711355 & 44.305801 & SEC23A;UBXN1;ST6GALNAC2;KDELR1;PRKCSH;UAP1;NEU3;PPP6C;SCFD1;FUT8;GANAB;TFG;MAN2A2;MAN2A1;LMAN2;MGAT5;GNPNAT1;CD59;SEC31A;SEC16B;TMED9;EGFL7;SEC24B;ST6GAL2;ST8SIA1;COG4;ALG5;COG2;ALG3;ALG13;MOGS;DYNLL1;RAD23B;RNF103;MGAT4A;MGAT4B;STT3A;KDELR2;MVD;KDELR3;SEC22B;SEC24C;B4GALT4 & NaN & NaN & 0.152482 & NaN \\

In [33]:
list(go_df_filtered["Term"])

['Golgi Membrane (GO:0000139)',
 'Bounding Membrane Of Organelle (GO:0098588)',
 'RNA Binding (GO:0003723)',
 'Protein Glycosylation (GO:0006486)',
 'Metabolism Of RNA R-HSA-8953854',
 'Intracellular Non-Membrane-Bounded Organelle (GO:0043232)',
 'Post-translational Protein Modification R-HSA-597592',
 'Nucleolus (GO:0005730)',
 'Nuclear Lumen (GO:0031981)',
 'Metabolism Of Proteins R-HSA-392499',
 'Protein O-linked Glycosylation (GO:0006493)',
 'Endosomal Transport (GO:0016197)',
 'mRNA Binding (GO:0003729)',
 'Golgi Vesicle Transport (GO:0048193)',
 'RNA transport',
 'Membrane Trafficking R-HSA-199991',
 'N-Glycan biosynthesis',
 'Vesicle-Mediated Transport (GO:0016192)',
 'Endocytic Recycling (GO:0032456)',
 'Endoplasmic Reticulum Membrane (GO:0005789)',
 'Acetylglucosaminyltransferase Activity (GO:0008375)',
 'Vesicle-mediated Transport R-HSA-5653656',
 'Processing Of Capped Intron-Containing Pre-mRNA R-HSA-72203',
 'Intra-Golgi And Retrograde Golgi-to-ER Traffic R-HSA-6811442',
 'Endosome Membrane (GO:0010008)',
 'Small GTPase Binding (GO:0031267)',
 'mRNA 3-End Processing R-HSA-72187',
 'Histone Acetylation (GO:0016573)',
 'Regulation Of RNA Splicing (GO:0043484)',
 'Asparagine N-linked Glycosylation R-HSA-446203',
 'GTPase Regulator Activity (GO:0030695)',
 'rRNA Modification In Nucleus And Cytosol R-HSA-6790901',
 'RNA Polymerase II Transcription Termination R-HSA-73856',
 'Mucin type O-glycan biosynthesis',
 'Sphingolipid metabolism',
 'Lysophosphatidic Acid Acyltransferase Activity (GO:0042171)',
 'Vesicle-Mediated Transport To The Plasma Membrane (GO:0098876)',
 'RHO GTPase Cycle R-HSA-9012999',
 'GTPase Binding (GO:0051020)',
 'Glycerophospholipid Biosynthesis R-HSA-1483206',
 'THO Complex Part Of Transcription Export Complex (GO:0000445)',
 'O-glycan Processing (GO:0016266)',
 'Rab Regulation Of Trafficking R-HSA-9007101',
 'Negative Regulation Of Organelle Assembly (GO:1902116)',
 'Lytic Vacuole (GO:0000323)',
 'Early Endosome (GO:0005769)',
 'SAGA-type Complex (GO:0070461)',
 'Protein Modification By Small Protein Conjugation (GO:0032446)',
 '1-Acylglycerol-3-Phosphate O-acyltransferase Activity (GO:0003841)',
 'Translation Initiation Factor Activity (GO:0003743)',
 'Intracellular Protein Transport (GO:0006886)',
 'Endosome To Lysosome Transport (GO:0008333)',
 'Phospholipid Biosynthetic Process (GO:0008654)',
 'RNA Metabolic Process (GO:0016070)',
 'Protein Localization (GO:0008104)',
 'Regulation Of Translation (GO:0006417)',
 'Formation Of Cytoplasmic Translation Initiation Complex (GO:0001732)',
 'Protein Transport (GO:0015031)',
 'Endosome Organization (GO:0007032)',
 'Late SARS-CoV-2 Infection Events R-HSA-9772573',
 'HATs Acetylate Histones R-HSA-3214847',
 'rRNA Processing In Nucleus And Cytosol R-HSA-8868773',
 'Transport Of Mature mRNA Derived From An Intron-Containing Transcript R-HSA-159236',
 'rRNA Processing R-HSA-72312',
 'Retrograde Vesicle-Mediated Transport, Golgi To Endoplasmic Reticulum (GO:0006890)',
 'mRNA Export From Nucleus (GO:0006406)',
 'mRNA Methylation (GO:0080009)',
 'Lysosome (GO:0005764)',
 'Transport Of Mature Transcript To Cytoplasm R-HSA-72202',
 'Histone H3 Acetylation (GO:0043966)',
 'Cytosolic Transport (GO:0016482)',
 'RNA Processing (GO:0006396)',
 'Glycoprotein Biosynthetic Process (GO:0009101)',
 'RNA Export From Nucleus (GO:0006405)',
 'Lysosomal Transport (GO:0007041)',
 'mRNA Transport (GO:0051028)',
 'Organelle Organization (GO:0006996)',
 'COPII Vesicle Coat (GO:0030127)',
 'Late Endosome (GO:0005770)',
 'Chromatin Modifying Enzymes R-HSA-3247509',
 'Negative Regulation Of Macroautophagy (GO:0016242)',
 'Sphingolipid Metabolism R-HSA-428157',
 'Acylglycerol O-acyltransferase Activity (GO:0016411)',
 'trans-Golgi Network (GO:0005802)',
 'Positive Regulation Of rRNA Processing (GO:2000234)',
 'Sphingolipid De Novo Biosynthesis R-HSA-1660661',
 'Ubiquitin Binding (GO:0043130)',
 'Signaling By Rho GTPases, Miro GTPases And RHOBTB3 R-HSA-9716542',
 'TBC/RABGAPs R-HSA-8854214',
 'Endomembrane System Organization (GO:0010256)',
 'cullin-RING Ubiquitin Ligase Complex (GO:0031461)',
 'Glycosaminoglycan biosynthesis',
 'Glycosphingolipid biosynthesis',
 'Protein Ubiquitination (GO:0016567)',
 'protein-RNA Complex Assembly (GO:0022618)']

In [34]:
list(go_df_filtered["Category"].unique())

["['cellular anatomical structure']",
 "['binding']",
 '[]',
 "['Metabolism of RNA']",
 "['Metabolism of proteins']",
 "['cellular process']",
 "['localization', 'cellular process']",
 "['Vesicle-mediated transport']",
 "['Glycan biosynthesis and metabolism']",
 "['catalytic activity']",
 "['biological regulation']",
 "['molecular function regulator activity']",
 "['Gene expression (Transcription)']",
 "['Lipid metabolism']",
 "['Signal Transduction']",
 "['Metabolism']",
 "['protein-containing complex']",
 "['translation factor activity']",
 "['localization']",
 "['Disease']",
 "['Chromatin organization']"]