In [1]:
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import numpy as np
import json
import gseapy as gp

In [2]:
DISEASE = input("Disease: ")
DISEASE_FOLDER = f"../output/{DISEASE}/"
RESULT_FOLDER = DISEASE_FOLDER + "leiden_results"

# Loading

In [3]:
def load(d):
    with open(f"../output/{d}/leiden_results/result_communities_selected.pkl", "rb") as f:
        communities = pickle.load(f)
    with open(f"../output/{d}/leiden_results/result_communities_HGNC_selected.pkl", "rb") as f:
        communities_HGNC = pickle.load(f)
    # with open(f"../output/{d}/leiden_results/result_graph.pkl", "rb") as f:
    #     graph = pickle.load(f)    
    with open(f"../output/{d}/gene_to_index_distinct.json", "r") as file:
        gene_to_index_distinct = json.load(file)
        
    return communities,communities_HGNC,gene_to_index_distinct

In [4]:
communities_selected,communities_HGNC_selected,gene_to_index_distinct = load(DISEASE)

# index to HGNC

In [5]:
index_to_gene_distinct = {v: u for (u,v) in gene_to_index_distinct.items()}

In [6]:
hgnc = pd.read_csv("../../Data/hgnc_complete_set.txt", sep="\t", dtype=str)
ncbi_to_hgnc_dict = dict(
    zip(
        hgnc["entrez_id"].dropna(),
        hgnc.loc[hgnc["entrez_id"].notna(), "symbol"]
    )
)

# Community deepdive

In [7]:
comm_idx = 4

In [8]:
important_terms = pd.read_csv(DISEASE_FOLDER + "important_terms.csv")

In [9]:
important_terms

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,Overlap (value)
0,0,1097,RNA Binding (GO:0003723),351/1411,6.843116e-143,['binding'],GO_Molecular_Function_2023,1.677234e-145,0.0,0.0,7.920093,2640.224035,EIF4A1;TCERG1;RTCA;RRP1;PPAN;HNRNPU;GPATCH4;HN...,0.248760
1,0,1097,Protein K48-linked Ubiquitination (GO:0070936),16/70,3.159683e-05,['cellular process'],GO_Biological_Process_2023,9.036131e-07,0.0,0.0,5.166410,71.900224,RNF34;UBE2B;UBE2E3;CUL3;UBE2D3;UBE3A;RNF6;UBE2...,0.228571
2,0,1097,Protein Neddylation (GO:0045116),9/22,3.887523e-05,['cellular process'],GO_Biological_Process_2023,1.129988e-06,0.0,0.0,12.019938,164.592658,UBE2F;DCUN1D5;DCUN1D4;DCUN1D1;UBA3;NEDD8;RNF7;...,0.409091
3,0,1097,"Preribosome, Small Subunit Precursor (GO:0030688)",6/10,4.159620e-05,['protein-containing complex'],GO_Cellular_Component_2023,4.661644e-06,0.0,0.0,25.983960,318.982791,LTV1;NOP14;RIOK3;TSR1;RIOK2;RIOK1,0.600000
4,0,1097,"mRNA Cis Splicing, Via Spliceosome (GO:0045292)",8/17,4.214994e-05,['cellular process'],GO_Biological_Process_2023,1.244935e-06,0.0,0.0,15.422100,209.685458,CLNS1A;DDX23;SRSF1;WBP4;SDE2;HNRNPC;CACTIN;SNR...,0.470588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,11,132,Intermediate Filament (GO:0005882),23/69,6.461525e-33,['cellular anatomical structure'],GO_Cellular_Component_2023,8.811171e-34,0.0,0.0,90.926606,6920.594236,KRT71;KRT80;KRT3;KRT2;KRT1;KRT79;KRT78;KRT10;K...,0.333333
3110,11,132,Supramolecular Fiber Organization (GO:0097435),38/316,1.015771e-35,['cellular process'],GO_Biological_Process_2023,1.953405e-37,0.0,0.0,28.486913,2407.886896,KRT80;KRT24;TCHH;KRT20;KRT86;KRT85;KRT40;KRT84...,0.120253
3111,11,132,Keratin Filament (GO:0045095),22/39,8.680165e-38,['cellular anatomical structure'],GO_Cellular_Component_2023,7.891059e-39,0.0,0.0,233.541176,20489.755737,KRT71;KRT80;KRT3;KRT2;KRT1;KRT79;KRT78;KRT10;K...,0.564103
3112,11,132,Keratinocyte Differentiation (GO:0030216),11/42,4.221335e-14,"['developmental process', 'cellular process']",GO_Biological_Process_2023,2.435386e-15,0.0,0.0,58.173021,1957.444847,TGM1;SPRR2F;SPRR3;SPRR2G;CDSN;KRT16;LORICRIN;K...,0.261905
3113,11,132,Formation Of Cornified Envelope R-HSA-6809371,40/74,1.055509e-68,['Developmental Biology'],Reactome_2022,9.895393e-70,0.0,0.0,253.631714,40299.260723,FLG;SPRR2E;SPRR2F;SPRR3;SPRR2G;TCHH;KLK5;KLK8;...,0.540541

In [10]:
go_df_filtered = important_terms[important_terms["Community Index"] == comm_idx]

In [11]:
go_df_filtered = go_df_filtered.sort_values(by = ["Adjusted P-value"], ascending = [True])

In [12]:
go_df_filtered

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,Overlap (value)
869,4,824,Biological Oxidations R-HSA-211859,106/218,2.545479e-85,['Metabolism'],Reactome_2022,5.892313e-88,0.0,0.0,25.129129,5047.281949,AHR;CNDP2;ABHD10;AKR7A2;HPGDS;AKR7A3;FDXR;CYP1...,0.486239
870,4,824,Metabolism R-HSA-1430728,281/2049,1.309259e-78,['Metabolism'],Reactome_2022,6.061383e-81,0.0,0.0,5.095339,941.147149,ECI1;ECI2;BSG;FDXR;PDK4;CYP1B1;CHAC2;MLYCD;CHA...,0.137140
871,4,824,Metabolism Of Lipids R-HSA-556833,169/732,2.312232e-78,['Metabolism'],Reactome_2022,1.605716e-80,0.0,0.0,8.530086,1567.260235,SLC27A1;ACAA2;ECI1;ECI2;RORA;AHR;TM7SF2;FADS2;...,0.230874
872,4,824,Fatty Acid Metabolism R-HSA-8978868,85/173,6.932126e-69,['Metabolism'],Reactome_2022,6.418635e-71,0.0,0.0,24.948948,4032.357191,ACAA2;ECI1;ECI2;DBI;PCTP;CROT;FADS2;HPGDS;ACOX...,0.491329
873,4,824,Phase I - Functionalization Of Compounds R-HSA...,67/104,4.771982e-65,['Metabolism'],Reactome_2022,5.523127e-67,0.0,0.0,45.782177,6984.723844,AHR;CYP26B1;ALDH2;CYP4V2;CYP2R1;FDXR;CYP1B1;NC...,0.644231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044,4,824,Sterol Transport (GO:0015918),7/25,7.749795e-04,['localization'],GO_Biological_Process_2023,4.923199e-05,0.0,0.0,9.119135,90.452399,GRAMD1C;OSBPL5;OSBP;OSBPL2;LCAT;CD36;LDLR,0.280000
1043,4,824,mRNA Transcription (GO:0009299),9/43,8.160876e-04,['cellular process'],GO_Biological_Process_2023,5.229039e-05,0.0,0.0,6.217178,61.293280,RXRB;NCOA1;CYP27B1;NCOA2;RXRA;NR1H2;NR1H3;PPAR...,0.209302
1042,4,824,Alcohol Dehydrogenase [NAD(P)+] Activity (GO:0...,4/7,8.477588e-04,['catalytic activity'],GO_Molecular_Function_2023,9.061554e-05,0.0,0.0,31.175610,290.210159,ADH4;ADH1C;ADH7;ADH6,0.571429
1041,4,824,Androsterone Dehydrogenase Activity (GO:0047023),4/7,8.477588e-04,['catalytic activity'],GO_Molecular_Function_2023,9.061554e-05,0.0,0.0,31.175610,290.210159,AKR1C3;RDH16;AKR1C4;HSD17B6,0.571429
905,4,824,Synthesis Of Epoxy (EET) And Dihydroxyeicosatr...,4/8,9.586634e-04,['Metabolism'],Reactome_2022,1.753111e-04,0.0,0.0,23.380488,202.216629,CYP2J2;EPHX2;CYP1A1;CYP1B1,0.500000

In [13]:
go_df_filtered[go_df_filtered["Gene_set"] == "Reactome_2022"]

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,Overlap (value)
869,4,824,Biological Oxidations R-HSA-211859,106/218,2.545479e-85,['Metabolism'],Reactome_2022,5.892313e-88,0.0,0.0,25.129129,5047.281949,AHR;CNDP2;ABHD10;AKR7A2;HPGDS;AKR7A3;FDXR;CYP1...,0.486239
870,4,824,Metabolism R-HSA-1430728,281/2049,1.309259e-78,['Metabolism'],Reactome_2022,6.061383e-81,0.0,0.0,5.095339,941.147149,ECI1;ECI2;BSG;FDXR;PDK4;CYP1B1;CHAC2;MLYCD;CHA...,0.137140
871,4,824,Metabolism Of Lipids R-HSA-556833,169/732,2.312232e-78,['Metabolism'],Reactome_2022,1.605716e-80,0.0,0.0,8.530086,1567.260235,SLC27A1;ACAA2;ECI1;ECI2;RORA;AHR;TM7SF2;FADS2;...,0.230874
872,4,824,Fatty Acid Metabolism R-HSA-8978868,85/173,6.932126e-69,['Metabolism'],Reactome_2022,6.418635e-71,0.0,0.0,24.948948,4032.357191,ACAA2;ECI1;ECI2;DBI;PCTP;CROT;FADS2;HPGDS;ACOX...,0.491329
873,4,824,Phase I - Functionalization Of Compounds R-HSA...,67/104,4.771982e-65,['Metabolism'],Reactome_2022,5.523127e-67,0.0,0.0,45.782177,6984.723844,AHR;CYP26B1;ALDH2;CYP4V2;CYP2R1;FDXR;CYP1B1;NC...,0.644231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901,4,824,"BMAL1:CLOCK,NPAS2 Activates Circadian Gene Exp...",7/27,4.874661e-04,['Circadian clock'],Reactome_2022,8.462952e-05,0.0,0.0,8.206365,76.952948,NCOA1;NCOA2;RXRA;NOCT;HSD17B4;PPARA;KLF15,0.259259
902,4,824,NR1H3 And NR1H2 Regulate Gene Expression Linke...,8/36,4.942091e-04,['Signal Transduction'],Reactome_2022,8.694420e-05,0.0,0.0,6.704482,62.688541,RXRB;ABCA1;NCOA1;RXRA;NR1H2;APOC1;NR1H3;ABCG1,0.222222
903,4,824,TYSND1 Cleaves Peroxisomal Proteins R-HSA-9033500,4/7,5.083885e-04,['Protein localization'],Reactome_2022,9.061554e-05,0.0,0.0,31.175610,290.210159,PHYH;ACOX1;HSD17B4;ACAA1,0.571429
904,4,824,Triglyceride Metabolism R-HSA-8979227,8/37,5.923776e-04,['Metabolism'],Reactome_2022,1.069571e-04,0.0,0.0,6.472955,59.182763,FABP1;FABP2;FABP3;FABP4;FABP7;PNPLA4;ABHD5;PLIN1,0.216216
905,4,824,Synthesis Of Epoxy (EET) And Dihydroxyeicosatr...,4/8,9.586634e-04,['Metabolism'],Reactome_2022,1.753111e-04,0.0,0.0,23.380488,202.216629,CYP2J2;EPHX2;CYP1A1;CYP1B1,0.500000

In [14]:
print(go_df_filtered[["Term","Adjusted P-value","Overlap"]].to_latex(longtable=True,index=False,caption=f"Enriched terms for {DISEASE} Community {comm_idx}",label=f"appendix:{DISEASE}_{comm_idx}_term", float_format="%.2e",column_format="p{8cm}cc",))

\begin{longtable}{p{8cm}cc}
\caption{Enriched terms for BIPOLAR Community 4} \label{appendix:BIPOLAR_4_term} \\
\toprule
Term & Adjusted P-value & Overlap \\
\midrule
\endfirsthead
\caption[]{Enriched terms for BIPOLAR Community 4} \\
\toprule
Term & Adjusted P-value & Overlap \\
\midrule
\endhead
\midrule
\multicolumn{3}{r}{Continued on next page} \\
\midrule
\endfoot
\bottomrule
\endlastfoot
Biological Oxidations R-HSA-211859 & 2.55e-85 & 106/218 \\
Metabolism R-HSA-1430728 & 1.31e-78 & 281/2049 \\
Metabolism Of Lipids R-HSA-556833 & 2.31e-78 & 169/732 \\
Fatty Acid Metabolism R-HSA-8978868 & 6.93e-69 & 85/173 \\
Phase I - Functionalization Of Compounds R-HSA-211945 & 4.77e-65 & 67/104 \\
PPAR signaling pathway & 9.34e-40 & 44/74 \\
Fatty Acid Metabolic Process (GO:0006631) & 4.36e-35 & 51/122 \\
Metabolism of xenobiotics by cytochrome P450 & 7.42e-35 & 41/76 \\
Bile Acid And Bile Salt Metabolism R-HSA-194068 & 1.35e-34 & 33/45 \\
Cytochrome P450 - Arranged By Substrate Type R-HSA-211897 & 3.13e-34 & 38/65 \\
Metabolism Of Steroids R-HSA-8957322 & 8.51e-30 & 50/153 \\
Arachidonic Acid Metabolism R-HSA-2142753 & 7.18e-29 & 33/59 \\
Fatty acid degradation & 1.10e-28 & 29/43 \\
Glutathione Conjugation R-HSA-156590 & 4.91e-27 & 26/36 \\
Synthesis Of Bile Acids And Bile Salts R-HSA-192105 & 2.39e-26 & 25/34 \\
Oxidoreductase Activity, Acting On The CH-OH Group Of Donors, NAD Or NADP As Acceptor (GO:0016616) & 2.23e-25 & 38/95 \\
Glutathione metabolism & 3.54e-25 & 30/57 \\
Peroxisomal Matrix (GO:0005782) & 1.45e-24 & 28/49 \\
Microbody Lumen (GO:0031907) & 1.45e-24 & 28/49 \\
Peroxisome & 2.85e-24 & 34/82 \\
Lipid Transport (GO:0006869) & 6.50e-24 & 39/108 \\
Long-Chain Fatty Acid Metabolic Process (GO:0001676) & 6.50e-24 & 34/78 \\
Steroid Metabolic Process (GO:0008202) & 1.55e-23 & 36/92 \\
Peroxisomal Lipid Metabolism R-HSA-390918 & 7.22e-22 & 21/29 \\
Drug metabolism & 7.81e-21 & 35/108 \\
Peroxisome (GO:0005777) & 1.08e-19 & 37/129 \\
Steroid Biosynthetic Process (GO:0006694) & 2.87e-19 & 25/50 \\
Arachidonic Acid Metabolic Process (GO:0019369) & 7.15e-19 & 25/52 \\
Fatty Acid Oxidation (GO:0019395) & 7.15e-19 & 25/52 \\
Phase II - Conjugation Of Compounds R-HSA-156580 & 8.17e-19 & 33/107 \\
Bile Acid Metabolic Process (GO:0008206) & 2.00e-18 & 20/31 \\
Bile Acid Biosynthetic Process (GO:0006699) & 7.25e-18 & 18/25 \\
Monocarboxylic Acid Transport (GO:0015718) & 5.93e-17 & 27/73 \\
PPARA Activates Gene Expression R-HSA-1989781 & 1.18e-16 & 32/116 \\
Endoplasmic Reticulum Membrane (GO:0005789) & 1.21e-16 & 90/801 \\
Arachidonic acid metabolism & 1.43e-16 & 24/61 \\
Drug ADME R-HSA-9748784 & 1.83e-16 & 29/95 \\
Regulation Of Lipid Metabolism By PPARalpha R-HSA-400206 & 1.83e-16 & 32/118 \\
Organic Hydroxy Compound Biosynthetic Process (GO:1901617) & 2.51e-16 & 21/42 \\
Monocarboxylic Acid Biosynthetic Process (GO:0072330) & 3.42e-16 & 25/65 \\
Peroxisomal Protein Import R-HSA-9033241 & 3.57e-16 & 24/63 \\
Fatty Acid Beta-Oxidation (GO:0006635) & 6.23e-16 & 22/49 \\
Synthesis Of Bile Acids And Bile Salts Via 7Alpha-Hydroxycholesterol R-HSA-193368 & 7.75e-16 & 16/24 \\
Long-Chain Fatty Acid Transport (GO:0015909) & 1.46e-15 & 16/23 \\
Monocarboxylic Acid Metabolic Process (GO:0032787) & 1.56e-15 & 29/97 \\
Retinol metabolism & 2.41e-15 & 24/68 \\
Sterol Metabolic Process (GO:0016125) & 6.46e-15 & 23/60 \\
Pyruvate metabolism & 1.04e-14 & 20/47 \\
Ethanol Oxidation R-HSA-71384 & 1.24e-14 & 11/11 \\
Oxidoreductase Activity, Acting On Paired Donors, With Incorporation Or Reduction Of Molecular Oxygen, Reduced Flavin Or Flavoprotein As One Donor, And Incorporation Of One Atom Of Oxygen (GO:0016712) & 1.82e-14 & 16/25 \\
Prostaglandin Metabolic Process (GO:0006693) & 1.88e-14 & 17/30 \\
Metabolic Disorders Of Biological Oxidation Enzymes R-HSA-5579029 & 6.30e-14 & 17/34 \\
Glutathione Transferase Activity (GO:0004364) & 1.20e-13 & 16/28 \\
Oxidoreductase Activity, Acting On The Aldehyde Or Oxo Group Of Donors, NAD Or NADP As Acceptor (GO:0016620) & 1.20e-13 & 14/20 \\
Recycling Of Bile Acids And Salts R-HSA-159418 & 1.31e-13 & 13/18 \\
Signaling By Retinoic Acid R-HSA-5362517 & 1.58e-13 & 18/41 \\
Aflatoxin Activation And Detoxification R-HSA-5423646 & 3.64e-13 & 13/19 \\
Heme Binding (GO:0020037) & 5.30e-13 & 25/87 \\
Icosanoid Metabolic Process (GO:0006690) & 5.82e-13 & 20/52 \\
Paracetamol ADME R-HSA-9753281 & 6.03e-13 & 15/28 \\
Fatty Acid Catabolic Process (GO:0009062) & 1.57e-12 & 21/61 \\
Very Long-Chain Fatty Acid Metabolic Process (GO:0000038) & 1.77e-12 & 16/32 \\
beta-Alanine metabolism & 2.23e-12 & 15/30 \\
Prostanoid Metabolic Process (GO:0006692) & 3.01e-12 & 12/16 \\
Biosynthesis of unsaturated fatty acids & 7.02e-12 & 14/27 \\
Endogenous Sterols R-HSA-211976 & 7.66e-12 & 14/27 \\
Synthesis Of Prostaglandins (PG) And Thromboxanes (TX) R-HSA-2162123 & 9.85e-12 & 11/15 \\
Fatty Acids R-HSA-211935 & 9.85e-12 & 11/15 \\
Synthesis Of Bile Acids And Bile Salts Via 27-Hydroxycholesterol R-HSA-193807 & 9.85e-12 & 11/15 \\
Cholesterol Metabolic Process (GO:0008203) & 1.12e-11 & 21/67 \\
Fatty Acid Beta-Oxidation Using acyl-CoA Oxidase (GO:0033540) & 1.12e-11 & 10/11 \\
Eicosanoids R-HSA-211979 & 1.18e-11 & 10/12 \\
Glutathione Synthesis And Recycling R-HSA-174403 & 1.18e-11 & 10/12 \\
ABC transporters & 1.30e-11 & 17/45 \\
Protein Localization R-HSA-9609507 & 1.35e-11 & 31/164 \\
Glycolysis / Gluconeogenesis & 1.97e-11 & 20/67 \\
Unsaturated Fatty Acid Metabolic Process (GO:0033559) & 2.57e-11 & 18/49 \\
Bile Acid And Bile Salt Transport (GO:0015721) & 5.12e-11 & 13/23 \\
Cholesterol Transport (GO:0030301) & 5.30e-11 & 18/51 \\
Plasma Lipoprotein Assembly, Remodeling, And Clearance R-HSA-174824 & 6.60e-11 & 20/71 \\
Primary bile acid biosynthesis & 6.67e-11 & 11/17 \\
Cholesterol metabolism & 7.68e-11 & 17/50 \\
Beta-oxidation Of Very Long Chain Fatty Acids R-HSA-390247 & 2.19e-10 & 9/11 \\
Epoxygenase P450 Pathway (GO:0019373) & 3.63e-10 & 11/17 \\
Fatty Acid Biosynthetic Process (GO:0006633) & 5.27e-10 & 19/65 \\
Sterol Homeostasis (GO:0055092) & 5.43e-10 & 20/73 \\
Fatty Acid Transport (GO:0015908) & 5.73e-10 & 15/38 \\
Aldehyde Dehydrogenase (NAD+) Activity (GO:0004029) & 6.06e-10 & 10/14 \\
Oxidoreductase Activity, Acting On Paired Donors, With Incorporation Or Reduction Of Molecular Oxygen, NAD(P)H As One Donor, And Incorporation Of One Atom Of Oxygen (GO:0016709) & 6.06e-10 & 13/27 \\
Aldehyde Dehydrogenase [NAD(P)+] Activity (GO:0004030) & 6.06e-10 & 10/14 \\
Bile secretion & 7.98e-10 & 21/90 \\
Positive Regulation Of Lipid Biosynthetic Process (GO:0046889) & 8.66e-10 & 15/39 \\
Fatty acyl-CoA Biosynthesis R-HSA-75105 & 1.17e-09 & 14/37 \\
Retinoid Metabolic Process (GO:0001523) & 1.29e-09 & 15/40 \\
Arachidonic Acid Epoxygenase Activity (GO:0008392) & 1.56e-09 & 10/15 \\
Synthesis Of Leukotrienes (LT) And Eoxins (EX) R-HSA-2142691 & 1.62e-09 & 11/21 \\
Chemical carcinogenesis & 2.89e-09 & 34/239 \\
RA Biosynthesis Pathway R-HSA-5365859 & 2.95e-09 & 11/22 \\
Organic Anion Transport (GO:0015711) & 3.16e-09 & 21/89 \\
Cholesterol Homeostasis (GO:0042632) & 3.16e-09 & 19/72 \\
Arachidonic Acid Monooxygenase Activity (GO:0008391) & 3.59e-09 & 10/16 \\
Sterol Binding (GO:0032934) & 5.04e-09 & 17/59 \\
Organic Hydroxy Compound Transport (GO:0015850) & 8.35e-09 & 15/45 \\
Ethanol Oxidation (GO:0006069) & 9.70e-09 & 7/7 \\
Nonribosomal Peptide Biosynthetic Process (GO:0019184) & 9.70e-09 & 7/7 \\
Diterpenoid Metabolic Process (GO:0016101) & 1.76e-08 & 12/28 \\
Steroid hormone biosynthesis & 2.06e-08 & 16/61 \\
NR1H2 And NR1H3-mediated Signaling R-HSA-9024446 & 2.91e-08 & 14/46 \\
Miscellaneous Substrates R-HSA-211958 & 3.80e-08 & 8/12 \\
Vitamins R-HSA-211916 & 5.19e-08 & 6/6 \\
fatty-acyl-CoA Biosynthetic Process (GO:0046949) & 6.68e-08 & 11/25 \\
Beta-oxidation Of pristanoyl-CoA R-HSA-389887 & 6.77e-08 & 7/9 \\
NR1H2 And NR1H3 Regulate Gene Expression Linked To Lipogenesis R-HSA-9029558 & 6.77e-08 & 7/9 \\
Alpha-Linolenic (Omega3) And Linoleic (Omega6) Acid Metabolism R-HSA-2046104 & 8.64e-08 & 8/13 \\
Signaling By Nuclear Receptors R-HSA-9006931 & 9.53e-08 & 33/260 \\
Tyrosine metabolism & 1.02e-07 & 12/36 \\
Adipocytokine signaling pathway & 1.28e-07 & 16/69 \\
Xenobiotics R-HSA-211981 & 1.49e-07 & 10/24 \\
Secondary Alcohol Metabolic Process (GO:1902652) & 1.53e-07 & 14/47 \\
Carboxylic Acid Metabolic Process (GO:0019752) & 1.53e-07 & 12/33 \\
Fatty Acid Transmembrane Transport (GO:1902001) & 1.53e-07 & 8/12 \\
Alcohol Dehydrogenase Activity, Zinc-Dependent (GO:0004024) & 1.69e-07 & 6/6 \\
Synthesis Of Bile Acids And Bile Salts Via 24-Hydroxycholesterol R-HSA-193775 & 1.82e-07 & 8/14 \\
Glutathione Biosynthetic Process (GO:0006750) & 2.04e-07 & 6/6 \\
Positive Regulation Of Fatty Acid Metabolic Process (GO:0045923) & 2.45e-07 & 9/17 \\
Carnitine Metabolic Process (GO:0009437) & 2.67e-07 & 7/9 \\
Positive Regulation Of Triglyceride Metabolic Process (GO:0090208) & 4.52e-07 & 9/18 \\
Carnitine Metabolism R-HSA-200425 & 5.16e-07 & 7/11 \\
Aldo-Keto Reductase (NADP) Activity (GO:0004033) & 6.26e-07 & 8/14 \\
NAD-retinol Dehydrogenase Activity (GO:0004745) & 6.27e-07 & 9/19 \\
Tryptophan metabolism & 6.47e-07 & 12/42 \\
Heme Degradation R-HSA-189483 & 6.93e-07 & 8/16 \\
Ethanol Metabolic Process (GO:0006067) & 7.51e-07 & 8/14 \\
Histidine metabolism & 7.94e-07 & 9/22 \\
Positive Regulation Of Cholesterol Transport (GO:0032376) & 8.21e-07 & 11/31 \\
Retinal Dehydrogenase Activity (GO:0001758) & 9.11e-07 & 6/7 \\
Long-Chain Fatty Acid Biosynthetic Process (GO:0042759) & 9.26e-07 & 10/25 \\
NR1H2 And NR1H3 Regulate Gene Expression To Limit Cholesterol Uptake R-HSA-9031525 & 9.94e-07 & 5/5 \\
NR1H2 And NR1H3 Regulate Gene Expression Linked To Triglyceride Lipolysis In Adipose R-HSA-9031528 & 9.94e-07 & 5/5 \\
NR1H2 And NR1H3 Regulate Gene Expression Linked To Gluconeogenesis R-HSA-9632974 & 9.94e-07 & 5/5 \\
CoA Hydrolase Activity (GO:0016289) & 1.05e-06 & 8/15 \\
Carboxylic Ester Hydrolase Activity (GO:0052689) & 1.07e-06 & 19/104 \\
Peroxisome Proliferator Activated Receptor Signaling Pathway (GO:0035357) & 1.19e-06 & 6/7 \\
Cholesterol Binding (GO:0015485) & 1.81e-06 & 13/50 \\
Fatty acid biosynthesis & 1.84e-06 & 8/18 \\
Positive Regulation Of Triglyceride Biosynthetic Process (GO:0010867) & 2.01e-06 & 7/11 \\
Synthesis Of Very Long-Chain Fatty acyl-CoAs R-HSA-75876 & 2.04e-06 & 9/24 \\
Steroid Dehydrogenase Activity, Acting On The CH-OH Group Of Donors, NAD Or NADP As Acceptor (GO:0033764) & 2.23e-06 & 9/22 \\
Carnitine O-acyltransferase Activity (GO:0016406) & 2.35e-06 & 5/5 \\
arachidonate-CoA Ligase Activity (GO:0047676) & 2.35e-06 & 5/5 \\
Alcohol Dehydrogenase (NAD+) Activity (GO:0004022) & 2.40e-06 & 6/8 \\
Atorvastatin ADME R-HSA-9754706 & 2.90e-06 & 6/9 \\
Synthesis Of 5-Eicosatetraenoic Acids R-HSA-2142688 & 2.90e-06 & 6/9 \\
Ferroptosis & 4.00e-06 & 11/41 \\
Plasma Lipoprotein Remodeling R-HSA-8963899 & 4.09e-06 & 10/33 \\
Cyclooxygenase Pathway (GO:0019371) & 4.32e-06 & 6/8 \\
Negative Regulation Of Cholesterol Storage (GO:0010887) & 4.32e-06 & 6/8 \\
Prostaglandin Biosynthetic Process (GO:0001516) & 4.65e-06 & 8/17 \\
Long-Chain fatty-acyl-CoA Biosynthetic Process (GO:0035338) & 4.65e-06 & 8/17 \\
Flavin Adenine Dinucleotide Binding (GO:0050660) & 4.79e-06 & 13/55 \\
Glutathione Binding (GO:0043295) & 6.36e-06 & 6/9 \\
Alcohol Dehydrogenase (NADP+) Activity (GO:0008106) & 6.82e-06 & 8/19 \\
Plasma Lipoprotein Clearance R-HSA-8964043 & 7.40e-06 & 10/35 \\
Nuclear Receptor Transcription Pathway R-HSA-383280 & 9.40e-06 & 12/53 \\
Mitochondrial Fatty Acid Beta-Oxidation R-HSA-77289 & 9.53e-06 & 10/36 \\
acyl-CoA Oxidase Activity (GO:0003997) & 1.02e-05 & 5/6 \\
ABC-type Glutathione S-conjugate Transporter Activity (GO:0015431) & 1.02e-05 & 5/6 \\
acyl-CoA Hydrolase Activity (GO:0047617) & 1.02e-05 & 8/20 \\
Transport Across Blood-Brain Barrier (GO:0150104) & 1.07e-05 & 16/85 \\
Transcriptional Regulation Of White Adipocyte Differentiation R-HSA-381340 & 1.12e-05 & 15/84 \\
SUMOylation Of Intracellular Receptors R-HSA-4090294 & 1.12e-05 & 9/29 \\
alditol:NADP+ 1-Oxidoreductase Activity (GO:0004032) & 1.23e-05 & 6/10 \\
ABC-type Xenobiotic Transporter Activity (GO:0008559) & 1.23e-05 & 6/10 \\
Xenobiotic Catabolic Process (GO:0042178) & 1.30e-05 & 8/19 \\
Triglyceride Catabolism R-HSA-163560 & 1.61e-05 & 8/23 \\
Regulation Of Cholesterol Storage (GO:0010885) & 1.62e-05 & 7/14 \\
Positive Regulation Of Transporter Activity (GO:0032411) & 1.62e-05 & 7/14 \\
Biosynthesis Of DHA-derived SPMs R-HSA-9018677 & 1.85e-05 & 7/17 \\
Phospholipid Transport (GO:0015914) & 1.91e-05 & 13/59 \\
Leukotriene Metabolic Process (GO:0006691) & 1.95e-05 & 8/20 \\
Amino-Acid Betaine Metabolic Process (GO:0006577) & 1.97e-05 & 5/6 \\
Leukotriene Transport (GO:0071716) & 1.97e-05 & 5/6 \\
Lipid Biosynthetic Process (GO:0008610) & 2.81e-05 & 14/71 \\
ABC-family Proteins Mediated Transport R-HSA-382556 & 2.81e-05 & 16/102 \\
RORA Activates Gene Expression R-HSA-1368082 & 2.83e-05 & 7/18 \\
Steroid Hydroxylase Activity (GO:0008395) & 3.08e-05 & 8/23 \\
Adenyl Nucleotide Binding (GO:0030554) & 3.83e-05 & 9/31 \\
Linoleic Acid (LA) Metabolism R-HSA-2046105 & 3.94e-05 & 5/8 \\
Biosynthesis Of Specialized Proresolving Mediators (SPMs) R-HSA-9018678 & 4.19e-05 & 7/19 \\
Regulation Of Lipid Metabolic Process (GO:0019216) & 4.31e-05 & 12/54 \\
Regulation Of Fatty Acid Oxidation (GO:0046320) & 4.36e-05 & 7/16 \\
Regulation Of Triglyceride Biosynthetic Process (GO:0010866) & 4.36e-05 & 7/16 \\
Reverse Cholesterol Transport (GO:0043691) & 4.36e-05 & 7/16 \\
Synthesis Of PC R-HSA-1483191 & 5.72e-05 & 8/27 \\
Regulation Of Cholesterol Transport (GO:0032374) & 5.91e-05 & 8/23 \\
Aromatic Compound Catabolic Process (GO:0019439) & 5.91e-05 & 5/7 \\
Long-Chain fatty-acyl-CoA Metabolic Process (GO:0035336) & 5.91e-05 & 8/23 \\
Fatty acid elongation & 6.17e-05 & 8/27 \\
Organelle Outer Membrane (GO:0031968) & 6.44e-05 & 22/170 \\
Oxidoreductase Activity, Acting On Paired Donors, With Incorporation Or Reduction Of Molecular Oxygen, Reduced Iron-Sulfur Protein As One Donor, And Incorporation Of One Atom Of Oxygen (GO:0016713) & 7.33e-05 & 5/8 \\
Carbonyl Reductase (NADPH) Activity (GO:0004090) & 7.33e-05 & 5/8 \\
Organonitrogen Compound Biosynthetic Process (GO:1901566) & 7.40e-05 & 18/123 \\
Metabolism Of Porphyrins R-HSA-189445 & 7.60e-05 & 8/28 \\
NAD Binding (GO:0051287) & 7.78e-05 & 8/26 \\
NR1H2 And NR1H3 Regulate Gene Expression To Control Bile Acid Homeostasis R-HSA-9623433 & 7.94e-05 & 5/9 \\
Synthesis Of (16-20)-Hydroxyeicosatetraenoic Acids (HETE) R-HSA-2142816 & 7.94e-05 & 5/9 \\
Negative Regulation Of Macrophage Derived Foam Cell Differentiation (GO:0010745) & 8.97e-05 & 6/12 \\
fatty-acyl-CoA Metabolic Process (GO:0035337) & 1.01e-04 & 7/18 \\
Negative Regulation Of Lipid Storage (GO:0010888) & 1.01e-04 & 7/18 \\
Intracellular Lipid Transport (GO:0032365) & 1.01e-04 & 7/18 \\
Ribonucleoside Bisphosphate Metabolic Process (GO:0033875) & 1.07e-04 & 8/25 \\
Organophosphate Ester Transport (GO:0015748) & 1.07e-04 & 8/25 \\
Purine Nucleoside Bisphosphate Metabolic Process (GO:0034032) & 1.07e-04 & 8/25 \\
Fat-Soluble Vitamin Catabolic Process (GO:0042363) & 1.35e-04 & 5/8 \\
Circadian Clock R-HSA-400253 & 1.36e-04 & 12/69 \\
Positive Regulation Of Fatty Acid Biosynthetic Process (GO:0045723) & 1.39e-04 & 6/13 \\
Regulation Of Fatty Acid Biosynthetic Process (GO:0042304) & 1.39e-04 & 8/26 \\
Leukotriene Biosynthetic Process (GO:0019370) & 1.39e-04 & 7/19 \\
acyl-CoA Biosynthetic Process (GO:0071616) & 1.39e-04 & 6/13 \\
Linoleic Acid Metabolic Process (GO:0043651) & 1.39e-04 & 7/19 \\
Monocarboxylic Acid Binding (GO:0033293) & 1.40e-04 & 8/28 \\
Valine, leucine and isoleucine degradation & 1.41e-04 & 10/48 \\
Oxidoreductase Activity, Acting On NAD(P)H, Heme Protein As Acceptor (GO:0016653) & 1.43e-04 & 5/9 \\
Retinoic Acid 4-Hydroxylase Activity (GO:0008401) & 1.43e-04 & 5/9 \\
Vascular Transport (GO:0010232) & 1.45e-04 & 14/83 \\
Oxidoreductase Activity, Acting On NAD(P)H, Quinone Or Similar Compound As Acceptor (GO:0016655) & 1.88e-04 & 6/15 \\
Xenobiotic Transport (GO:0042908) & 2.00e-04 & 7/20 \\
Retinoid Binding (GO:0005501) & 2.20e-04 & 8/30 \\
Glycerolipid metabolism & 2.22e-04 & 11/61 \\
Prostanoid Biosynthetic Process (GO:0046457) & 2.23e-04 & 6/14 \\
Medium-Chain Fatty Acid Metabolic Process (GO:0051791) & 2.23e-04 & 6/14 \\
Lipid Import Into Cell (GO:0140354) & 2.55e-04 & 5/9 \\
Long-Chain Fatty Acid Import Into Cell (GO:0044539) & 2.55e-04 & 5/9 \\
Organic Hydroxy Compound Catabolic Process (GO:1901616) & 2.55e-04 & 5/9 \\
CYP2E1 Reactions R-HSA-211999 & 2.64e-04 & 5/11 \\
Positive Regulation Of Sterol Transport (GO:0032373) & 2.69e-04 & 4/5 \\
Cholesterol Import (GO:0070508) & 2.69e-04 & 4/5 \\
Taurine and hypotaurine metabolism & 2.74e-04 & 5/11 \\
High-Density Lipoprotein Particle Remodeling (GO:0034375) & 3.29e-04 & 6/15 \\
Regulation Of Lipoprotein Lipase Activity (GO:0051004) & 3.29e-04 & 6/15 \\
Nitric Oxide Biosynthetic Process (GO:0006809) & 3.29e-04 & 6/15 \\
Positive Regulation Of Cholesterol Efflux (GO:0010875) & 3.63e-04 & 7/22 \\
Aspirin ADME R-HSA-9749641 & 3.75e-04 & 9/44 \\
Oxysterol Binding (GO:0008142) & 4.02e-04 & 4/6 \\
Fatty Acid Elongase Activity (GO:0009922) & 4.02e-04 & 4/6 \\
Vitamin D (Calciferol) Metabolism R-HSA-196791 & 4.26e-04 & 5/12 \\
Omega-Hydroxylase P450 Pathway (GO:0097267) & 4.54e-04 & 5/10 \\
Heme Catabolic Process (GO:0042167) & 4.54e-04 & 5/10 \\
Cholesterol Efflux (GO:0033344) & 4.78e-04 & 7/23 \\
Triglyceride Homeostasis (GO:0070328) & 4.78e-04 & 8/31 \\
Nitric Oxide Metabolic Process (GO:0046209) & 4.78e-04 & 6/16 \\
Retinal Metabolic Process (GO:0042574) & 4.78e-04 & 6/16 \\
BMAL1:CLOCK,NPAS2 Activates Circadian Gene Expression R-HSA-1368108 & 4.87e-04 & 7/27 \\
NR1H3 And NR1H2 Regulate Gene Expression Linked To Cholesterol Transport And Efflux R-HSA-9029569 & 4.94e-04 & 8/36 \\
TYSND1 Cleaves Peroxisomal Proteins R-HSA-9033500 & 5.08e-04 & 4/7 \\
Triglyceride Metabolism R-HSA-8979227 & 5.92e-04 & 8/37 \\
Regulation Of Cholesterol Efflux (GO:0010874) & 6.08e-04 & 8/32 \\
Acylglycerol Homeostasis (GO:0055090) & 6.27e-04 & 7/24 \\
Fat-Soluble Vitamin Metabolic Process (GO:0006775) & 6.27e-04 & 7/24 \\
Fatty Acid Elongation, Monounsaturated Fatty Acid (GO:0034625) & 6.43e-04 & 4/6 \\
Regulation Of Cellular Response To Insulin Stimulus (GO:1900076) & 6.43e-04 & 4/6 \\
Very Long-Chain Fatty Acid Catabolic Process (GO:0042760) & 6.43e-04 & 4/6 \\
Positive Regulation Of Lipoprotein Lipase Activity (GO:0051006) & 6.43e-04 & 4/6 \\
Fatty Acid Elongation, Polyunsaturated Fatty Acid (GO:0034626) & 6.43e-04 & 4/6 \\
Fatty Acid Elongation, Unsaturated Fatty Acid (GO:0019368) & 6.43e-04 & 4/6 \\
Fatty Acid Elongation, Saturated Fatty Acid (GO:0019367) & 6.43e-04 & 4/6 \\
Steroid biosynthesis & 6.80e-04 & 6/20 \\
Leukotriene D4 Metabolic Process (GO:1901748) & 6.99e-04 & 5/11 \\
Intramolecular Oxidoreductase Activity, Transposing C=C Bonds (GO:0016863) & 7.14e-04 & 5/12 \\
Lipid Droplet (GO:0005811) & 7.68e-04 & 13/82 \\
Sterol Transport (GO:0015918) & 7.75e-04 & 7/25 \\
mRNA Transcription (GO:0009299) & 8.16e-04 & 9/43 \\
Alcohol Dehydrogenase [NAD(P)+] Activity (GO:0018455) & 8.48e-04 & 4/7 \\
Androsterone Dehydrogenase Activity (GO:0047023) & 8.48e-04 & 4/7 \\
Synthesis Of Epoxy (EET) And Dihydroxyeicosatrienoic Acids (DHET) R-HSA-2142670 & 9.59e-04 & 4/8 \\
\end{longtable}

In [15]:
list(go_df_filtered["Term"])[:30]

['Biological Oxidations R-HSA-211859',
 'Metabolism R-HSA-1430728',
 'Metabolism Of Lipids R-HSA-556833',
 'Fatty Acid Metabolism R-HSA-8978868',
 'Phase I - Functionalization Of Compounds R-HSA-211945',
 'PPAR signaling pathway',
 'Fatty Acid Metabolic Process (GO:0006631)',
 'Metabolism of xenobiotics by cytochrome P450',
 'Bile Acid And Bile Salt Metabolism R-HSA-194068',
 'Cytochrome P450 - Arranged By Substrate Type R-HSA-211897',
 'Metabolism Of Steroids R-HSA-8957322',
 'Arachidonic Acid Metabolism R-HSA-2142753',
 'Fatty acid degradation',
 'Glutathione Conjugation R-HSA-156590',
 'Synthesis Of Bile Acids And Bile Salts R-HSA-192105',
 'Oxidoreductase Activity, Acting On The CH-OH Group Of Donors, NAD Or NADP As Acceptor (GO:0016616)',
 'Glutathione metabolism',
 'Peroxisomal Matrix (GO:0005782)',
 'Microbody Lumen (GO:0031907)',
 'Peroxisome',
 'Lipid Transport (GO:0006869)',
 'Long-Chain Fatty Acid Metabolic Process (GO:0001676)',
 'Steroid Metabolic Process (GO:0008202)',
 'Peroxisomal Lipid Metabolism R-HSA-390918',
 'Drug metabolism',
 'Peroxisome (GO:0005777)',
 'Steroid Biosynthetic Process (GO:0006694)',
 'Arachidonic Acid Metabolic Process (GO:0019369)',
 'Fatty Acid Oxidation (GO:0019395)',
 'Phase II - Conjugation Of Compounds R-HSA-156580']

In [16]:
list(go_df_filtered["Category"].unique())

["['Metabolism']",
 "['Endocrine system']",
 "['cellular process']",
 "['Xenobiotics biodegradation and metabolism']",
 "['Lipid metabolism']",
 "['catalytic activity']",
 "['Metabolism of other amino acids']",
 "['cellular anatomical structure']",
 "['Transport and catabolism']",
 "['localization']",
 '[]',
 "['Drug ADME']",
 "['Protein localization']",
 "['Metabolism of cofactors and vitamins']",
 "['Carbohydrate metabolism']",
 "['Disease']",
 "['Signal Transduction']",
 "['binding']",
 "['Membrane transport']",
 "['Transport of small molecules']",
 "['Digestive system']",
 "['homeostatic process']",
 "['biological regulation']",
 "['Amino acid metabolism']",
 "['localization', 'cellular process']",
 "['biological regulation', 'cellular process']",
 "['catalytic activity', 'ATP-dependent activity']",
 "['Cell growth and death']",
 "['Gene expression (Transcription)']",
 "['transporter activity', 'ATP-dependent activity']",
 "['multicellular organismal process', 'localization']",
 "['Developmental Biology']",
 "['Metabolism of proteins']",
 "['multicellular organismal process', 'cellular process']",
 "['Circadian clock']"]