In [1]:
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import numpy as np
import json
import gseapy as gp

In [2]:
DISEASE = input("Disease: ")
DISEASE_FOLDER = f"../output/{DISEASE}/"
RESULT_FOLDER = DISEASE_FOLDER + "leiden_results"

# Loading

In [3]:
def load(d):
    with open(f"../output/{d}/leiden_results/result_communities_selected.pkl", "rb") as f:
        communities = pickle.load(f)
    with open(f"../output/{d}/leiden_results/result_communities_HGNC_selected.pkl", "rb") as f:
        communities_HGNC = pickle.load(f)
    # with open(f"../output/{d}/leiden_results/result_graph.pkl", "rb") as f:
    #     graph = pickle.load(f)    
    with open(f"../output/{d}/gene_to_index_distinct.json", "r") as file:
        gene_to_index_distinct = json.load(file)
        
    return communities,communities_HGNC,gene_to_index_distinct

In [4]:
communities_selected,communities_HGNC_selected,gene_to_index_distinct = load(DISEASE)

# index to HGNC

In [5]:
index_to_gene_distinct = {v: u for (u,v) in gene_to_index_distinct.items()}

In [6]:
hgnc = pd.read_csv("../../Data/hgnc_complete_set.txt", sep="\t", dtype=str)
ncbi_to_hgnc_dict = dict(
    zip(
        hgnc["entrez_id"].dropna(),
        hgnc.loc[hgnc["entrez_id"].notna(), "symbol"]
    )
)

# Select top genes

In [7]:
# comm_idx = 0

In [8]:
def zscore(values):
    arr = np.asarray(values, dtype=float)
    if arr.size == 0:
        return arr

    mean = arr.mean()
    std = arr.std(ddof=0)

    if std == 0 or np.isnan(std):
        # no variation: all z-scores = 0
        return np.zeros_like(arr)

    return (arr - mean) / std

def community_central_genes_ranked(G, community_nodes, weight="weight"):
    C = set(community_nodes)
    H = G.subgraph(C).copy()                       # induced subgraph
    # within-community (weighted) degree
    k = {u: H.degree(u, weight=weight) for u in H}
    ks = np.array(list(k.values()), dtype=float)
    zscore_list = zscore(ks)
    Z = dict(zip(H,zscore_list))        # within-module degree z-score
    
    return Z

In [9]:
index_to_gene_distinct

{10: '1',
 11: '2',
 12: '3',
 13: '9',
 14: '10',
 15: '12',
 16: '13',
 17: '14',
 18: '15',
 19: '16',
 20: '18',
 21: '19',
 22: '20',
 23: '21',
 24: '22',
 25: '23',
 26: '24',
 27: '25',
 28: '26',
 29: '27',
 30: '28',
 31: '29',
 32: '30',
 33: '31',
 34: '32',
 35: '33',
 36: '34',
 37: '35',
 38: '36',
 39: '37',
 40: '38',
 41: '39',
 42: '40',
 43: '41',
 44: '43',
 45: '47',
 46: '48',
 47: '49',
 48: '50',
 49: '51',
 50: '52',
 51: '53',
 52: '54',
 53: '55',
 54: '56',
 55: '58',
 56: '59',
 57: '60',
 58: '69',
 59: '70',
 60: '71',
 61: '72',
 62: '81',
 63: '83',
 64: '86',
 65: '87',
 66: '88',
 67: '89',
 68: '90',
 69: '91',
 70: '92',
 71: '93',
 72: '94',
 73: '95',
 74: '97',
 75: '98',
 76: '100',
 77: '101',
 78: '102',
 79: '103',
 80: '104',
 81: '105',
 82: '107',
 83: '108',
 84: '109',
 85: '111',
 86: '112',
 87: '113',
 88: '114',
 89: '115',
 90: '116',
 91: '117',
 92: '118',
 93: '119',
 94: '120',
 95: '123',
 96: '124',
 97: '125',
 98: '126',
 99: '127',
 100: '128',
 101: '130',
 102: '131',
 103: '132',
 104: '133',
 105: '134',
 106: '135',
 107: '136',
 108: '137',
 109: '140',
 110: '141',
 111: '142',
 112: '143',
 113: '146',
 114: '147',
 115: '148',
 116: '150',
 117: '151',
 118: '152',
 119: '153',
 120: '154',
 121: '155',
 122: '156',
 123: '157',
 124: '158',
 125: '159',
 126: '160',
 127: '161',
 128: '162',
 129: '163',
 130: '164',
 131: '165',
 132: '166',
 133: '167',
 134: '172',
 135: '173',
 136: '174',
 137: '175',
 138: '176',
 139: '177',
 140: '178',
 141: '181',
 142: '182',
 143: '183',
 144: '185',
 145: '186',
 146: '187',
 147: '189',
 148: '190',
 149: '191',
 150: '196',
 151: '197',
 152: '199',
 153: '202',
 154: '203',
 155: '204',
 156: '205',
 157: '207',
 158: '208',
 159: '210',
 160: '211',
 161: '212',
 162: '213',
 163: '214',
 164: '215',
 165: '216',
 166: '217',
 167: '218',
 168: '219',
 169: '220',
 170: '221',
 171: '222',
 172: '223',
 173: '224',
 174: '225',
 175: '226',
 176: '228',
 177: '229',
 178: '230',
 179: '231',
 180: '238',
 181: '239',
 182: '240',
 183: '241',
 184: '242',
 185: '245',
 186: '246',
 187: '247',
 188: '248',
 189: '249',
 190: '250',
 191: '251',
 192: '257',
 193: '258',
 194: '259',
 195: '262',
 196: '265',
 197: '266',
 198: '267',
 199: '268',
 200: '269',
 201: '270',
 202: '271',
 203: '272',
 204: '273',
 205: '274',
 206: '275',
 207: '276',
 208: '277',
 209: '278',
 210: '279',
 211: '280',
 212: '283',
 213: '284',
 214: '285',
 215: '286',
 216: '287',
 217: '288',
 218: '290',
 219: '291',
 220: '292',
 221: '293',
 222: '301',
 223: '302',
 224: '303',
 225: '304',
 226: '305',
 227: '306',
 228: '307',
 229: '308',
 230: '309',
 231: '310',
 232: '311',
 233: '312',
 234: '313',
 235: '314',
 236: '316',
 237: '317',
 238: '318',
 239: '319',
 240: '320',
 241: '321',
 242: '322',
 243: '323',
 244: '324',
 245: '325',
 246: '326',
 247: '327',
 248: '328',
 249: '329',
 250: '330',
 251: '331',
 252: '332',
 253: '333',
 254: '334',
 255: '335',
 256: '336',
 257: '337',
 258: '338',
 259: '339',
 260: '341',
 261: '342',
 262: '343',
 263: '344',
 264: '345',
 265: '346',
 266: '347',
 267: '348',
 268: '350',
 269: '351',
 270: '353',
 271: '354',
 272: '355',
 273: '356',
 274: '357',
 275: '358',
 276: '359',
 277: '360',
 278: '361',
 279: '362',
 280: '363',
 281: '364',
 282: '366',
 283: '367',
 284: '368',
 285: '369',
 286: '372',
 287: '373',
 288: '374',
 289: '375',
 290: '377',
 291: '378',
 292: '379',
 293: '381',
 294: '382',
 295: '383',
 296: '384',
 297: '387',
 298: '388',
 299: '389',
 300: '390',
 301: '391',
 302: '392',
 303: '393',
 304: '394',
 305: '395',
 306: '396',
 307: '397',
 308: '398',
 309: '399',
 310: '400',
 311: '401',
 312: '402',
 313: '403',
 314: '405',
 315: '406',
 316: '407',
 317: '408',
 318: '409',
 319: '410',
 320: '411',
 321: '412',
 322: '414',
 323: '415',
 324: '416',
 325: '417',
 326: '419',
 327: '420',
 328: '421',
 329: '427',
 330: '429',
 331: '430',
 332: '432',
 333: '433',
 334: '434',
 335: '435',
 336: '438',
 337: '439',
 338: '440',
 339: '443',
 340: '444',
 341: '445',
 342: '454',
 343: '460',
 344: '462',
 345: '463',
 346: '466',
 347: '467',
 348: '468',
 349: '471',
 350: '472',
 351: '473',
 352: '474',
 353: '475',
 354: '476',
 355: '477',
 356: '478',
 357: '479',
 358: '480',
 359: '481',
 360: '482',
 361: '483',
 362: '486',
 363: '487',
 364: '488',
 365: '489',
 366: '490',
 367: '491',
 368: '492',
 369: '493',
 370: '495',
 371: '496',
 372: '498',
 373: '501',
 374: '506',
 375: '509',
 376: '513',
 377: '514',
 378: '515',
 379: '516',
 380: '517',
 381: '518',
 382: '520',
 383: '521',
 384: '522',
 385: '523',
 386: '525',
 387: '526',
 388: '527',
 389: '528',
 390: '529',
 391: '533',
 392: '534',
 393: '535',
 394: '537',
 395: '538',
 396: '539',
 397: '540',
 398: '541',
 399: '545',
 400: '546',
 401: '547',
 402: '549',
 403: '550',
 404: '551',
 405: '552',
 406: '553',
 407: '554',
 408: '558',
 409: '563',
 410: '566',
 411: '567',
 412: '570',
 413: '571',
 414: '572',
 415: '573',
 416: '575',
 417: '576',
 418: '577',
 419: '578',
 420: '579',
 421: '580',
 422: '581',
 423: '582',
 424: '583',
 425: '585',
 426: '586',
 427: '587',
 428: '590',
 429: '593',
 430: '594',
 431: '595',
 432: '596',
 433: '597',
 434: '598',
 435: '599',
 436: '602',
 437: '604',
 438: '605',
 439: '606',
 440: '607',
 441: '608',
 442: '610',
 443: '611',
 444: '613',
 445: '617',
 446: '618',
 447: '622',
 448: '623',
 449: '624',
 450: '627',
 451: '629',
 452: '631',
 453: '632',
 454: '633',
 455: '634',
 456: '635',
 457: '636',
 458: '637',
 459: '638',
 460: '639',
 461: '640',
 462: '641',
 463: '642',
 464: '643',
 465: '644',
 466: '645',
 467: '646',
 468: '648',
 469: '649',
 470: '650',
 471: '651',
 472: '652',
 473: '653',
 474: '654',
 475: '655',
 476: '656',
 477: '657',
 478: '658',
 479: '659',
 480: '660',
 481: '661',
 482: '662',
 483: '663',
 484: '664',
 485: '665',
 486: '666',
 487: '667',
 488: '668',
 489: '669',
 490: '670',
 491: '671',
 492: '672',
 493: '673',
 494: '675',
 495: '676',
 496: '677',
 497: '678',
 498: '680',
 499: '682',
 500: '683',
 501: '684',
 502: '685',
 503: '686',
 504: '687',
 505: '688',
 506: '689',
 507: '690',
 508: '694',
 509: '695',
 510: '696',
 511: '699',
 512: '701',
 513: '705',
 514: '706',
 515: '708',
 516: '710',
 517: '711',
 518: '712',
 519: '713',
 520: '714',
 521: '715',
 522: '716',
 523: '717',
 524: '718',
 525: '719',
 526: '720',
 527: '721',
 528: '722',
 529: '725',
 530: '726',
 531: '727',
 532: '728',
 533: '729',
 534: '730',
 535: '731',
 536: '732',
 537: '733',
 538: '734',
 539: '735',
 540: '738',
 541: '740',
 542: '741',
 543: '744',
 544: '745',
 545: '746',
 546: '747',
 547: '750',
 548: '752',
 549: '753',
 550: '754',
 551: '755',
 552: '757',
 553: '758',
 554: '759',
 555: '760',
 556: '761',
 557: '762',
 558: '763',
 559: '765',
 560: '766',
 561: '767',
 562: '768',
 563: '770',
 564: '771',
 565: '773',
 566: '774',
 567: '775',
 568: '776',
 569: '777',
 570: '778',
 571: '779',
 572: '780',
 573: '781',
 574: '782',
 575: '783',
 576: '784',
 577: '785',
 578: '786',
 579: '788',
 580: '789',
 581: '790',
 582: '793',
 583: '794',
 584: '795',
 585: '796',
 586: '797',
 587: '799',
 588: '800',
 589: '801',
 590: '805',
 591: '808',
 592: '810',
 593: '811',
 594: '813',
 595: '814',
 596: '815',
 597: '816',
 598: '817',
 599: '818',
 600: '819',
 601: '820',
 602: '821',
 603: '822',
 604: '823',
 605: '824',
 606: '825',
 607: '826',
 608: '827',
 609: '828',
 610: '829',
 611: '830',
 612: '831',
 613: '832',
 614: '833',
 615: '834',
 616: '835',
 617: '836',
 618: '837',
 619: '838',
 620: '839',
 621: '840',
 622: '841',
 623: '842',
 624: '843',
 625: '844',
 626: '845',
 627: '846',
 628: '847',
 629: '857',
 630: '858',
 631: '859',
 632: '860',
 633: '861',
 634: '862',
 635: '863',
 636: '864',
 637: '865',
 638: '866',
 639: '867',
 640: '868',
 641: '869',
 642: '871',
 643: '873',
 644: '874',
 645: '875',
 646: '881',
 647: '883',
 648: '885',
 649: '886',
 650: '887',
 651: '889',
 652: '890',
 653: '891',
 654: '892',
 655: '894',
 656: '895',
 657: '896',
 658: '898',
 659: '899',
 660: '900',
 661: '901',
 662: '902',
 663: '904',
 664: '905',
 665: '908',
 666: '909',
 667: '910',
 668: '911',
 669: '912',
 670: '913',
 671: '914',
 672: '915',
 673: '916',
 674: '917',
 675: '919',
 676: '920',
 677: '921',
 678: '922',
 679: '923',
 680: '924',
 681: '925',
 682: '926',
 683: '928',
 684: '929',
 685: '930',
 686: '931',
 687: '932',
 688: '933',
 689: '936',
 690: '938',
 691: '939',
 692: '940',
 693: '941',
 694: '942',
 695: '943',
 696: '944',
 697: '945',
 698: '946',
 699: '947',
 700: '948',
 701: '949',
 702: '950',
 703: '951',
 704: '952',
 705: '953',
 706: '954',
 707: '955',
 708: '956',
 709: '957',
 710: '958',
 711: '959',
 712: '960',
 713: '961',
 714: '962',
 715: '963',
 716: '965',
 717: '966',
 718: '967',
 719: '968',
 720: '969',
 721: '970',
 722: '971',
 723: '972',
 724: '973',
 725: '974',
 726: '975',
 727: '976',
 728: '977',
 729: '978',
 730: '983',
 731: '984',
 732: '987',
 733: '988',
 734: '989',
 735: '990',
 736: '991',
 737: '993',
 738: '994',
 739: '995',
 740: '996',
 741: '997',
 742: '998',
 743: '999',
 744: '1000',
 745: '1001',
 746: '1002',
 747: '1003',
 748: '1004',
 749: '1005',
 750: '1006',
 751: '1007',
 752: '1008',
 753: '1009',
 754: '1010',
 755: '1012',
 756: '1013',
 757: '1014',
 758: '1015',
 759: '1016',
 760: '1017',
 761: '1018',
 762: '1019',
 763: '1020',
 764: '1021',
 765: '1022',
 766: '1024',
 767: '1025',
 768: '1026',
 769: '1027',
 770: '1028',
 771: '1029',
 772: '1030',
 773: '1031',
 774: '1032',
 775: '1033',
 776: '1036',
 777: '1038',
 778: '1039',
 779: '1040',
 780: '1041',
 781: '1043',
 782: '1044',
 783: '1045',
 784: '1046',
 785: '1047',
 786: '1048',
 787: '1050',
 788: '1051',
 789: '1052',
 790: '1053',
 791: '1054',
 792: '1056',
 793: '1057',
 794: '1058',
 795: '1059',
 796: '1060',
 797: '1062',
 798: '1063',
 799: '1066',
 800: '1068',
 801: '1069',
 802: '1070',
 803: '1071',
 804: '1072',
 805: '1073',
 806: '1075',
 807: '1080',
 808: '1081',
 809: '1082',
 810: '1084',
 811: '1087',
 812: '1088',
 813: '1089',
 814: '1101',
 815: '1102',
 816: '1103',
 817: '1104',
 818: '1105',
 819: '1106',
 820: '1107',
 821: '1108',
 822: '1109',
 823: '1111',
 824: '1112',
 825: '1113',
 826: '1114',
 827: '1116',
 828: '1117',
 829: '1118',
 830: '1119',
 831: '1120',
 832: '1121',
 833: '1122',
 834: '1123',
 835: '1124',
 836: '1128',
 837: '1129',
 838: '1130',
 839: '1131',
 840: '1132',
 841: '1133',
 842: '1134',
 843: '1135',
 844: '1136',
 845: '1137',
 846: '1138',
 847: '1139',
 848: '1140',
 849: '1141',
 850: '1142',
 851: '1143',
 852: '1144',
 853: '1145',
 854: '1146',
 855: '1147',
 856: '1149',
 857: '1152',
 858: '1153',
 859: '1154',
 860: '1155',
 861: '1158',
 862: '1159',
 863: '1160',
 864: '1161',
 865: '1163',
 866: '1164',
 867: '1173',
 868: '1174',
 869: '1175',
 870: '1176',
 871: '1178',
 872: '1179',
 873: '1180',
 874: '1181',
 875: '1182',
 876: '1183',
 877: '1184',
 878: '1185',
 879: '1186',
 880: '1187',
 881: '1188',
 882: '1191',
 883: '1192',
 884: '1193',
 885: '1195',
 886: '1196',
 887: '1198',
 888: '1200',
 889: '1201',
 890: '1203',
 891: '1207',
 892: '1208',
 893: '1209',
 894: '1211',
 895: '1212',
 896: '1213',
 897: '1215',
 898: '1230',
 899: '1232',
 900: '1233',
 901: '1234',
 902: '1235',
 903: '1236',
 904: '1237',
 905: '1238',
 906: '1240',
 907: '1241',
 908: '1244',
 909: '1258',
 910: '1259',
 911: '1260',
 912: '1261',
 913: '1262',
 914: '1263',
 915: '1264',
 916: '1265',
 917: '1266',
 918: '1267',
 919: '1268',
 920: '1269',
 921: '1270',
 922: '1271',
 923: '1272',
 924: '1277',
 925: '1278',
 926: '1280',
 927: '1281',
 928: '1282',
 929: '1284',
 930: '1285',
 931: '1286',
 932: '1287',
 933: '1288',
 934: '1289',
 935: '1290',
 936: '1291',
 937: '1292',
 938: '1293',
 939: '1294',
 940: '1295',
 941: '1296',
 942: '1297',
 943: '1298',
 944: '1299',
 945: '1300',
 946: '1301',
 947: '1302',
 948: '1303',
 949: '1305',
 950: '1306',
 951: '1307',
 952: '1308',
 953: '1310',
 954: '1311',
 955: '1312',
 956: '1314',
 957: '1315',
 958: '1316',
 959: '1317',
 960: '1318',
 961: '1325',
 962: '1326',
 963: '1327',
 964: '1329',
 965: '1337',
 966: '1339',
 967: '1340',
 968: '1345',
 969: '1346',
 970: '1347',
 971: '1349',
 972: '1350',
 973: '1351',
 974: '1352',
 975: '1353',
 976: '1355',
 977: '1356',
 978: '1357',
 979: '1358',
 980: '1359',
 981: '1360',
 982: '1361',
 983: '1362',
 984: '1363',
 985: '1364',
 986: '1365',
 987: '1366',
 988: '1368',
 989: '1369',
 990: '1370',
 991: '1371',
 992: '1373',
 993: '1374',
 994: '1375',
 995: '1376',
 996: '1378',
 997: '1379',
 998: '1380',
 999: '1381',
 1000: '1382',
 1001: '1384',
 1002: '1385',
 1003: '1386',
 1004: '1387',
 1005: '1388',
 1006: '1389',
 1007: '1390',
 1008: '1392',
 1009: '1393',
 ...}

In [10]:
# zscore_dict = community_central_genes_ranked(graph,communities[comm_idx])

In [11]:
# zscore_dict = dict(sorted(zscore_dict.items(), key=lambda x: x[1], reverse=True))

In [12]:
# zscore_dict

In [13]:
# top_genes = [u for u,v in zscore_dict.items()][:3]

In [14]:
# top_genes

# Community deepdive

In [15]:
comm_idx = 0

In [16]:
comm_HGNC = communities_HGNC_selected[comm_idx]

In [17]:
len(comm_HGNC)

1369

In [18]:
important_terms = pd.read_csv(DISEASE_FOLDER + "important_terms.csv")

In [19]:
go_df_filtered = important_terms[important_terms["Community Index"] == comm_idx]

In [20]:
go_df_filtered = go_df_filtered.sort_values(by = ["Adjusted P-value"], ascending = [True])

In [21]:
go_df_filtered

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,GO_ID,Slim_IDs,Overlap (value),KEGG_ID
213,0,1369,Immune System R-HSA-168256,285/1943,1.026963e-34,['Immune System'],Reactome_2022,8.853125e-38,0.0,0.0,2.691471,229.629455,CYFIP2;IFITM3;CNTFR;CYFIP1;IFITM1;IL1RN;IFITM2...,NaN,NaN,0.146680,NaN
109,0,1369,Regulation Of Apoptotic Process (GO:0042981),126/705,2.939267e-20,['biological regulation'],GO_Biological_Process_2023,7.108263e-24,0.0,0.0,3.160430,168.453399,FOXA1;PHB1;TFRC;PDCD5;FAIM2;IFIT3;IFIT2;IGF1R;...,GO:0042981,{'GO:0065007'},0.178723,NaN
221,0,1369,Signal Transduction R-HSA-162582,289/2465,7.961780e-19,['Signal Transduction'],Reactome_2022,1.372721e-21,0.0,0.0,2.023546,97.206076,CYFIP2;CYFIP1;PHB1;TRIO;TFRC;HHIP;ITSN1;STMN2;...,NaN,NaN,0.117241,NaN
206,0,1369,Cytokine Signaling In Immune System R-HSA-1280215,120/702,1.650074e-18,['Immune System'],Reactome_2022,4.267434e-21,0.0,0.0,2.979538,139.750101,IFITM3;CNTFR;IFITM1;IL1RN;IFITM2;IFIT5;F13A1;U...,NaN,NaN,0.170940,NaN
67,0,1369,Positive Regulation Of Intracellular Signal Tr...,100/525,5.802099e-18,['biological regulation'],GO_Biological_Process_2023,3.557771e-21,0.0,0.0,3.375701,158.945402,PHB1;TFRC;NCF1;TRAF3IP2;IFIT5;IFI35;IGF1R;TBK1...,GO:1902533,{'GO:0065007'},0.190476,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0,1369,Negative Regulation Of Angiogenesis (GO:0016525),17/86,9.234840e-04,['biological regulation'],GO_Biological_Process_2023,6.253338e-05,0.0,0.0,3.382579,32.742719,SLC12A2;FOXC1;SEMA6A;SERPINF1;PTPRM;NRG1;VASH1...,GO:0016525,{'GO:0065007'},0.197674,NaN
391,0,1369,Regulation Of Actin Filament-Based Process (GO...,15/70,9.315534e-04,['biological regulation'],GO_Biological_Process_2023,6.330508e-05,0.0,0.0,3.741641,36.172482,RALA;RHOG;ARHGAP18;NEDD9;NRG1;FZD10;F11R;IQGAP...,GO:0032970,{'GO:0065007'},0.214286,NaN
126,0,1369,Collagen Degradation R-HSA-1442490,11/40,9.784876e-04,['Extracellular matrix organization'],Reactome_2022,5.398552e-05,0.0,0.0,5.195826,51.058310,MMP12;MMP14;MMP7;MMP13;TMPRSS6;MMP1;CTSK;MMP2;...,NaN,NaN,0.275000,NaN
277,0,1369,Sterol Biosynthetic Process (GO:0016126),9/28,9.850395e-04,['cellular process'],GO_Biological_Process_2023,6.741625e-05,0.0,0.0,6.482508,62.262053,MVK;HMGCS1;INSIG2;INSIG1;HMGCR;DHCR7;LSS;TM7SF...,GO:0016126,{'GO:0009987'},0.321429,NaN
253,0,1369,Establishment Of Endothelial Barrier (GO:0061028),9/28,9.850395e-04,"['developmental process', 'cellular process']",GO_Biological_Process_2023,6.741625e-05,0.0,0.0,6.482508,62.262053,PPP1R16B;RAB1A;MARVELD2;SOX18;RDX;MYADM;MSN;RA...,GO:0061028,"{'GO:0032502', 'GO:0009987'}",0.321429,NaN

In [22]:
go_df_filtered[go_df_filtered["Gene_set"] == "Reactome_2022"]

,Community Index,Community Size,Term,Overlap,Adjusted P-value,Category,Gene_set,P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,GO_ID,Slim_IDs,Overlap (value),KEGG_ID
213,0,1369,Immune System R-HSA-168256,285/1943,1.026963e-34,['Immune System'],Reactome_2022,8.853125e-38,0.0,0.0,2.691471,229.629455,CYFIP2;IFITM3;CNTFR;CYFIP1;IFITM1;IL1RN;IFITM2...,NaN,NaN,0.146680,NaN
221,0,1369,Signal Transduction R-HSA-162582,289/2465,7.961780e-19,['Signal Transduction'],Reactome_2022,1.372721e-21,0.0,0.0,2.023546,97.206076,CYFIP2;CYFIP1;PHB1;TRIO;TFRC;HHIP;ITSN1;STMN2;...,NaN,NaN,0.117241,NaN
206,0,1369,Cytokine Signaling In Immune System R-HSA-1280215,120/702,1.650074e-18,['Immune System'],Reactome_2022,4.267434e-21,0.0,0.0,2.979538,139.750101,IFITM3;CNTFR;IFITM1;IL1RN;IFITM2;IFIT5;F13A1;U...,NaN,NaN,0.170940,NaN
217,0,1369,Innate Immune System R-HSA-168249,149/1035,3.632325e-16,['Immune System'],Reactome_2022,1.252526e-18,0.0,0.0,2.446069,100.830317,CYFIP2;OTUD5;CYFIP1;NCF1;DEFB1;UBE2L6;LGALS3;R...,NaN,NaN,0.143961,NaN
131,0,1369,Interferon Signaling R-HSA-913531,51/200,2.351027e-14,['Immune System'],Reactome_2022,1.013374e-16,0.0,0.0,4.799737,176.765090,IFITM3;IFITM1;IFITM2;IFIT5;UBE2L6;IFI35;IFIT1;...,NaN,NaN,0.255000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,0,1369,Defective B3GAT3 Causes JDSSDHD R-HSA-3560801,8/20,5.555088e-04,['Disease'],Reactome_2022,2.825433e-05,0.0,0.0,9.120255,95.527955,SDC4;GPC3;SDC1;CSPG4;GPC4;AGRN;GPC6;DCN,NaN,NaN,0.400000,NaN
210,0,1369,TCF Dependent Signaling In Response To WNT R-H...,30/198,6.510225e-04,['Signal Transduction'],Reactome_2022,3.367358e-05,0.0,0.0,2.462259,25.358302,USP34;WNT8A;LRP6;ZNRF3;TNKS2;RSPO2;DVL2;RSPO3;...,NaN,NaN,0.151515,NaN
119,0,1369,GAG Synthesis Requires Tetrasaccharide Linker ...,9/26,6.570665e-04,['Metabolism'],Reactome_2022,3.455264e-05,0.0,0.0,7.245934,74.437676,SDC4;GPC3;XYLT1;SDC1;CSPG4;GPC4;AGRN;GPC6;DCN,NaN,NaN,0.346154,NaN
196,0,1369,Axon Guidance R-HSA-422475,60/519,8.745334e-04,['Developmental Biology'],Reactome_2022,4.674230e-05,0.0,0.0,1.814687,18.093988,NRP1;TRIO;RPL31;SH3KBP1;ITSN1;CASC3;VLDLR;LAMC...,NaN,NaN,0.115607,NaN
126,0,1369,Collagen Degradation R-HSA-1442490,11/40,9.784876e-04,['Extracellular matrix organization'],Reactome_2022,5.398552e-05,0.0,0.0,5.195826,51.058310,MMP12;MMP14;MMP7;MMP13;TMPRSS6;MMP1;CTSK;MMP2;...,NaN,NaN,0.275000,NaN

In [23]:
print(go_df_filtered[["Term","Adjusted P-value","Overlap"]].to_latex(longtable=True,index=False,caption=f"Enriched terms for {DISEASE} Community {comm_idx}",label=f"appendix:{DISEASE}_{comm_idx}_term", float_format="%.2e",column_format="p{8cm}cc",))

\begin{longtable}{p{8cm}cc}
\caption{Enriched terms for BIPOLAR Community 0} \label{appendix:BIPOLAR_0_term} \\
\toprule
Term & Adjusted P-value & Overlap \\
\midrule
\endfirsthead
\caption[]{Enriched terms for BIPOLAR Community 0} \\
\toprule
Term & Adjusted P-value & Overlap \\
\midrule
\endhead
\midrule
\multicolumn{3}{r}{Continued on next page} \\
\midrule
\endfoot
\bottomrule
\endlastfoot
Immune System R-HSA-168256 & 1.03e-34 & 285/1943 \\
Regulation Of Apoptotic Process (GO:0042981) & 2.94e-20 & 126/705 \\
Signal Transduction R-HSA-162582 & 7.96e-19 & 289/2465 \\
Cytokine Signaling In Immune System R-HSA-1280215 & 1.65e-18 & 120/702 \\
Positive Regulation Of Intracellular Signal Transduction (GO:1902533) & 5.80e-18 & 100/525 \\
Regulation Of Cell Population Proliferation (GO:0042127) & 5.80e-18 & 127/766 \\
Defense Response To Virus (GO:0051607) & 3.85e-17 & 54/189 \\
Wnt Signaling Pathway (GO:0016055) & 3.85e-17 & 34/76 \\
Negative Regulation Of Cellular Process (GO:0048523) & 4.43e-17 & 99/537 \\
Innate Immune System R-HSA-168249 & 3.63e-16 & 149/1035 \\
Defense Response To Symbiont (GO:0140546) & 3.97e-16 & 46/148 \\
Collagen-Containing Extracellular Matrix (GO:0062023) & 4.97e-16 & 76/373 \\
Wnt signaling pathway & 8.45e-16 & 48/166 \\
Frizzled Binding (GO:0005109) & 1.39e-15 & 22/33 \\
Regulation Of I-kappaB kinase/NF-kappaB Signaling (GO:0043122) & 5.24e-15 & 57/232 \\
Negative Regulation Of Cell Population Proliferation (GO:0008285) & 5.32e-15 & 76/379 \\
Positive Regulation Of DNA-templated Transcription (GO:0045893) & 8.02e-15 & 166/1243 \\
Proteoglycans in cancer & 8.43e-15 & 52/205 \\
Regulation Of Cell Migration (GO:0030334) & 9.20e-15 & 82/434 \\
Canonical Wnt Signaling Pathway (GO:0060070) & 9.85e-15 & 29/65 \\
Basal cell carcinoma & 9.95e-15 & 28/63 \\
Interferon Signaling R-HSA-913531 & 2.35e-14 & 51/200 \\
Positive Regulation Of Cellular Process (GO:0048522) & 2.68e-14 & 99/594 \\
Negative Regulation Of Cell Migration (GO:0030336) & 7.55e-14 & 45/163 \\
Interferon Alpha/Beta Signaling R-HSA-909733 & 1.58e-13 & 29/72 \\
Cell-Substrate Junction (GO:0030055) & 4.02e-13 & 73/395 \\
Regulation Of Cell Adhesion (GO:0030155) & 4.62e-13 & 41/144 \\
Negative Regulation Of Signal Transduction (GO:0009968) & 5.60e-13 & 58/267 \\
Negative Regulation Of Apoptotic Process (GO:0043066) & 1.05e-12 & 83/482 \\
Focal Adhesion (GO:0005925) & 1.13e-12 & 71/387 \\
Negative Regulation Of Viral Process (GO:0048525) & 1.13e-12 & 26/61 \\
Regulation Of Canonical Wnt Signaling Pathway (GO:0060828) & 2.11e-12 & 49/207 \\
RHO GTPase Cycle R-HSA-9012999 & 3.01e-12 & 77/441 \\
Neutrophil Degranulation R-HSA-6798695 & 3.01e-12 & 80/468 \\
Negative Regulation Of Programmed Cell Death (GO:0043069) & 4.97e-12 & 70/381 \\
Positive Regulation Of DNA-binding Transcription Factor Activity (GO:0051091) & 9.88e-12 & 53/246 \\
Signaling pathways regulating pluripotency of stem cells & 1.32e-11 & 38/143 \\
Hemostasis R-HSA-109582 & 1.47e-11 & 90/576 \\
Positive Regulation Of I-kappaB kinase/NF-kappaB Signaling (GO:0043123) & 1.98e-11 & 43/175 \\
Protein Kinase Binding (GO:0019901) & 4.57e-11 & 83/511 \\
Positive Regulation Of Transcription By RNA Polymerase II (GO:0045944) & 5.50e-11 & 125/938 \\
Cell-Cell Junction (GO:0005911) & 7.30e-11 & 57/299 \\
Positive Regulation Of Response To External Stimulus (GO:0032103) & 1.12e-10 & 39/155 \\
Bounding Membrane Of Organelle (GO:0098588) & 1.16e-10 & 111/819 \\
Protein Localization To Membrane (GO:0072657) & 1.24e-10 & 44/192 \\
Signaling By Rho GTPases, Miro GTPases And RHOBTB3 R-HSA-9716542 & 1.57e-10 & 96/660 \\
Hippo signaling pathway & 1.88e-10 & 39/163 \\
Negative Regulation Of Viral Genome Replication (GO:0045071) & 1.90e-10 & 22/53 \\
Regulation Of Gene Expression (GO:0010468) & 3.59e-10 & 140/1127 \\
Positive Regulation Of Apoptotic Process (GO:0043065) & 3.66e-10 & 53/270 \\
Signaling By Rho GTPases R-HSA-194315 & 4.92e-10 & 93/644 \\
G Protein-Coupled Receptor Binding (GO:0001664) & 6.14e-10 & 36/140 \\
Neuron Differentiation (GO:0030182) & 8.70e-10 & 40/173 \\
Positive Regulation Of Cell Population Proliferation (GO:0008284) & 9.55e-10 & 76/483 \\
Positive Regulation Of Cytokine Production (GO:0001819) & 9.77e-10 & 58/320 \\
Positive Regulation Of Programmed Cell Death (GO:0043068) & 1.06e-09 & 49/245 \\
Negative Regulation Of Multicellular Organismal Process (GO:0051241) & 1.41e-09 & 47/231 \\
Negative Regulation Of Intracellular Signal Transduction (GO:1902532) & 1.41e-09 & 47/231 \\
Extracellular Matrix Organization R-HSA-1474244 & 1.47e-09 & 54/291 \\
Cellular Response To Cytokine Stimulus (GO:0071345) & 1.75e-09 & 56/308 \\
Extracellular Matrix Disassembly (GO:0022617) & 2.05e-09 & 19/44 \\
Protein Polyubiquitination (GO:0000209) & 2.12e-09 & 46/226 \\
RNA Binding (GO:0003723) & 2.34e-09 & 163/1411 \\
Negative Regulation Of Cell Adhesion (GO:0007162) & 3.26e-09 & 24/72 \\
Regulation Of Viral Genome Replication (GO:0045069) & 4.12e-09 & 23/67 \\
Non-Canonical Wnt Signaling Pathway (GO:0035567) & 4.48e-09 & 18/41 \\
Cellular Component Disassembly (GO:0022411) & 4.64e-09 & 19/46 \\
Negative Regulation Of ERK1 And ERK2 Cascade (GO:0070373) & 1.10e-08 & 19/48 \\
Interferon Gamma Signaling R-HSA-877300 & 1.15e-08 & 26/89 \\
Supramolecular Fiber Organization (GO:0097435) & 1.23e-08 & 55/316 \\
Secretory Granule Membrane (GO:0030667) & 1.29e-08 & 50/279 \\
Ribonucleoside Triphosphate Phosphatase Activity (GO:0017111) & 1.37e-08 & 50/270 \\
Signaling By Receptor Tyrosine Kinases R-HSA-9006934 & 1.39e-08 & 74/496 \\
Cellular Response To Transforming Growth Factor Beta Stimulus (GO:0071560) & 1.40e-08 & 27/96 \\
Positive Regulation Of Cell Differentiation (GO:0045597) & 1.54e-08 & 51/283 \\
WNT Ligand Biogenesis And Trafficking R-HSA-3238698 & 1.59e-08 & 14/26 \\
Purine Ribonucleoside Triphosphate Binding (GO:0035639) & 1.67e-08 & 72/476 \\
GTPase Activity (GO:0003924) & 1.67e-08 & 49/265 \\
Ubiquitin-Protein Transferase Activity (GO:0004842) & 1.93e-08 & 65/412 \\
Regulation Of Epithelial Cell Proliferation (GO:0050678) & 1.99e-08 & 26/91 \\
Positive Regulation Of Gene Expression (GO:0010628) & 2.05e-08 & 72/480 \\
Negative Regulation Of Wnt Signaling Pathway (GO:0030178) & 2.14e-08 & 33/140 \\
Regulation Of Interferon-Beta Production (GO:0032648) & 2.18e-08 & 19/50 \\
Negative Regulation Of Cell Motility (GO:2000146) & 2.18e-08 & 32/133 \\
Positive Regulation Of Multicellular Organismal Process (GO:0051240) & 2.37e-08 & 62/387 \\
Ubiquitin-Like Protein Ligase Binding (GO:0044389) & 2.97e-08 & 51/289 \\
mTOR signaling pathway & 3.73e-08 & 34/154 \\
Positive Regulation Of Macromolecule Metabolic Process (GO:0010604) & 3.96e-08 & 59/364 \\
Response To Molecule Of Bacterial Origin (GO:0002237) & 4.11e-08 & 22/69 \\
Metal Ion Binding (GO:0046872) & 4.92e-08 & 75/521 \\
Negative Regulation Of Hydrolase Activity (GO:0051346) & 5.05e-08 & 18/47 \\
Actin Cytoskeleton (GO:0015629) & 5.05e-08 & 54/327 \\
Guanyl Ribonucleotide Binding (GO:0032561) & 5.35e-08 & 43/226 \\
Positive Regulation Of Type I Interferon Production (GO:0032481) & 5.37e-08 & 21/64 \\
Positive Regulation Of Defense Response (GO:0031349) & 6.07e-08 & 30/124 \\
Epithelium Development (GO:0060429) & 6.23e-08 & 34/154 \\
Ubiquitin Protein Ligase Binding (GO:0031625) & 6.45e-08 & 48/271 \\
Regulation Of ERK1 And ERK2 Cascade (GO:0070372) & 6.59e-08 & 45/244 \\
Regulation Of Protein Binding (GO:0043393) & 7.41e-08 & 29/118 \\
Positive Regulation Of Nucleic Acid-Templated Transcription (GO:1903508) & 7.66e-08 & 78/557 \\
Positive Regulation Of Cell Migration (GO:0030335) & 8.09e-08 & 48/272 \\
Negative Regulation Of MAPK Cascade (GO:0043409) & 8.98e-08 & 27/105 \\
Melanogenesis & 9.85e-08 & 26/101 \\
Positive Regulation Of Signal Transduction (GO:0009967) & 1.12e-07 & 47/266 \\
Class B/2 (Secretin Family Receptors) R-HSA-373080 & 1.14e-07 & 25/92 \\
Positive Regulation Of Protein Phosphorylation (GO:0001934) & 1.28e-07 & 59/377 \\
Negative Regulation Of Canonical Wnt Signaling Pathway (GO:0090090) & 1.32e-07 & 28/114 \\
GTP Binding (GO:0005525) & 1.54e-07 & 39/201 \\
Adherens Junction (GO:0005912) & 2.18e-07 & 32/150 \\
Positive Regulation Of Protein Metabolic Process (GO:0051247) & 2.78e-07 & 38/196 \\
Protein Modification Process (GO:0036211) & 2.91e-07 & 91/711 \\
Generation Of Neurons (GO:0048699) & 2.94e-07 & 35/172 \\
Signaling By Interleukins R-HSA-449147 & 3.00e-07 & 66/453 \\
Membrane Raft (GO:0045121) & 3.28e-07 & 34/169 \\
Protein Homodimerization Activity (GO:0042803) & 3.29e-07 & 86/662 \\
Negative Regulation Of Protein Phosphorylation (GO:0001933) & 3.30e-07 & 32/149 \\
Keratinocyte Differentiation (GO:0030216) & 3.74e-07 & 16/42 \\
Negative Regulation Of Cell Differentiation (GO:0045596) & 3.74e-07 & 39/207 \\
RNA Splicing (GO:0008380) & 3.74e-07 & 25/98 \\
Protein Tyrosine Kinase Binding (GO:1990782) & 3.77e-07 & 23/85 \\
Kinase Binding (GO:0019900) & 3.77e-07 & 66/460 \\
Integrin-Mediated Signaling Pathway (GO:0007229) & 4.35e-07 & 23/85 \\
Cellular Response To Insulin Stimulus (GO:0032869) & 4.55e-07 & 25/99 \\
Wnt Receptor Activity (GO:0042813) & 5.18e-07 & 10/16 \\
Negative Regulation Of Epithelial Cell Migration (GO:0010633) & 6.09e-07 & 14/33 \\
Protein Ubiquitination (GO:0016567) & 6.21e-07 & 63/434 \\
Regulation Of mRNA Splicing, Via Spliceosome (GO:0048024) & 6.69e-07 & 24/94 \\
Positive Regulation Of Epithelial Cell Proliferation (GO:0050679) & 6.69e-07 & 28/123 \\
Ubiquitin-Dependent Protein Catabolic Process (GO:0006511) & 6.69e-07 & 56/367 \\
Gastric cancer & 6.83e-07 & 31/149 \\
Heart Development (GO:0007507) & 7.53e-07 & 34/171 \\
Transmembrane Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169) & 7.53e-07 & 47/284 \\
Skin Development (GO:0043588) & 7.70e-07 & 20/68 \\
Regulation Of Endothelial Cell Migration (GO:0010594) & 7.88e-07 & 23/88 \\
Sema4D In Semaphorin Signaling R-HSA-400685 & 8.12e-07 & 12/24 \\
Sema4D Induced Cell Migration And Growth-Cone Collapse R-HSA-416572 & 8.57e-07 & 11/20 \\
Regulation Of JNK Cascade (GO:0046328) & 9.01e-07 & 26/110 \\
Positive Regulation Of Innate Immune Response (GO:0045089) & 1.00e-06 & 16/45 \\
Regulation Of Intracellular Signal Transduction (GO:1902531) & 1.08e-06 & 48/297 \\
Positive Regulation Of Inflammatory Response (GO:0050729) & 1.13e-06 & 25/104 \\
Negative Regulation Of Epithelial Cell Proliferation (GO:0050680) & 1.23e-06 & 20/70 \\
Negative Regulation Of Gene Expression (GO:0010629) & 1.23e-06 & 52/336 \\
Modification-Dependent Protein Catabolic Process (GO:0019941) & 1.27e-06 & 36/192 \\
Negative Regulation Of GTPase Activity (GO:0034260) & 1.27e-06 & 11/21 \\
Regulation Of Epidermal Growth Factor Receptor Signaling Pathway (GO:0042058) & 1.30e-06 & 16/46 \\
Antiviral Innate Immune Response (GO:0140374) & 1.30e-06 & 16/46 \\
Regulation Of Cell Growth (GO:0001558) & 1.30e-06 & 40/227 \\
mRNA Binding (GO:0003729) & 1.35e-06 & 46/282 \\
Cytoskeleton (GO:0005856) & 1.59e-06 & 77/599 \\
Secretory Granule Lumen (GO:0034774) & 1.59e-06 & 49/316 \\
Positive Regulation Of Response To Biotic Stimulus (GO:0002833) & 1.59e-06 & 15/41 \\
Breast cancer & 1.61e-06 & 30/147 \\
Regulation Of Protein Phosphorylation (GO:0001932) & 1.65e-06 & 44/265 \\
Positive Regulation Of Interferon-Beta Production (GO:0032728) & 1.80e-06 & 14/36 \\
Transmembrane Receptor Protein Serine/Threonine Kinase Signaling Pathway (GO:0007178) & 1.93e-06 & 28/130 \\
Regulation Of Inflammatory Response (GO:0050727) & 2.05e-06 & 41/240 \\
Regulation Of Angiogenesis (GO:0045765) & 2.11e-06 & 37/205 \\
Regulation of actin cytoskeleton & 2.28e-06 & 38/218 \\
Hepatocellular carcinoma & 2.42e-06 & 32/168 \\
Human papillomavirus infection & 2.42e-06 & 50/331 \\
Response To Cytokine (GO:0034097) & 3.01e-06 & 27/125 \\
Gland Development (GO:0048732) & 3.01e-06 & 20/74 \\
Skeletal System Development (GO:0001501) & 3.07e-06 & 30/149 \\
RNA Processing (GO:0006396) & 3.38e-06 & 34/183 \\
Protein Localization To Cell Periphery (GO:1990778) & 3.57e-06 & 29/142 \\
Endocytic Vesicle (GO:0030139) & 3.63e-06 & 35/196 \\
Degradation Of Extracellular Matrix R-HSA-1474228 & 3.75e-06 & 25/109 \\
RHOG GTPase Cycle R-HSA-9013408 & 4.07e-06 & 20/74 \\
Regulation Of Viral Entry Into Host Cell (GO:0046596) & 4.25e-06 & 15/44 \\
mRNA Splicing, Via Spliceosome (GO:0000398) & 4.25e-06 & 37/211 \\
Golgi Membrane (GO:0000139) & 4.26e-06 & 59/427 \\
Golgi Lumen (GO:0005796) & 4.26e-06 & 23/100 \\
Positive Regulation Of Cell Motility (GO:2000147) & 4.84e-06 & 38/221 \\
Protein K48-linked Ubiquitination (GO:0070936) & 5.48e-06 & 19/70 \\
Ubiquitin-Like Protein Transferase Activity (GO:0019787) & 5.49e-06 & 40/240 \\
Protein Localization To Plasma Membrane (GO:0072659) & 5.56e-06 & 28/137 \\
Negative Regulation Of Mitotic Cell Cycle (GO:0045930) & 6.01e-06 & 13/34 \\
Regulation Of Cytoskeleton Organization (GO:0051493) & 6.01e-06 & 25/114 \\
Amyloid Fibril Formation (GO:1990000) & 6.01e-06 & 11/24 \\
Positive Regulation Of Cellular Catabolic Process (GO:0031331) & 6.18e-06 & 29/146 \\
Peptidyl-Tyrosine Dephosphorylation (GO:0035335) & 6.30e-06 & 12/29 \\
Glycosaminoglycan Metabolism R-HSA-1630316 & 6.37e-06 & 26/120 \\
Positive Regulation Of Protein Catabolic Process (GO:0045732) & 6.41e-06 & 22/92 \\
Endosomal Transport (GO:0016197) & 6.41e-06 & 33/180 \\
Cellular Response To Growth Factor Stimulus (GO:0071363) & 6.69e-06 & 30/155 \\
Specific Granule (GO:0042581) & 6.69e-06 & 30/159 \\
Intracellular Non-Membrane-Bounded Organelle (GO:0043232) & 6.75e-06 & 127/1195 \\
RAC1 GTPase Cycle R-HSA-9013149 & 6.96e-06 & 33/178 \\
Early Endosome (GO:0005769) & 7.52e-06 & 46/307 \\
Wnt Signaling Pathway Involved In Midbrain Dopaminergic Neuron Differentiation (GO:1904953) & 7.68e-06 & 7/9 \\
Cadherin Binding (GO:0045296) & 7.81e-06 & 48/319 \\
Negative Regulation Of Binding (GO:0051100) & 8.04e-06 & 21/86 \\
Semaphorin Interactions R-HSA-373755 & 8.21e-06 & 18/64 \\
Positive Regulation Of Wnt Signaling Pathway (GO:0030177) & 9.11e-06 & 24/109 \\
Lysosome (GO:0005764) & 9.16e-06 & 65/503 \\
Class I MHC Mediated Antigen Processing And Presentation R-HSA-983169 & 9.86e-06 & 54/378 \\
RAC3 GTPase Cycle R-HSA-9013423 & 9.86e-06 & 22/93 \\
Protease Binding (GO:0002020) & 9.96e-06 & 26/125 \\
Response To Lipid (GO:0033993) & 1.08e-05 & 24/110 \\
Actin-Based Cell Projection (GO:0098858) & 1.11e-05 & 20/84 \\
Positive Regulation Of Cell Projection Organization (GO:0031346) & 1.11e-05 & 25/118 \\
Non-integrin membrane-ECM Interactions R-HSA-3000171 & 1.22e-05 & 14/41 \\
RHOC GTPase Cycle R-HSA-9013106 & 1.23e-05 & 19/73 \\
Epidermal Cell Differentiation (GO:0009913) & 1.25e-05 & 16/54 \\
Cell Surface Interactions At Vascular Wall R-HSA-202733 & 1.33e-05 & 27/134 \\
Positive Regulation Of NF-kappaB Transcription Factor Activity (GO:0051092) & 1.38e-05 & 29/152 \\
Wnt Signaling Pathway, Planar Cell Polarity Pathway (GO:0060071) & 1.44e-05 & 11/26 \\
Axon guidance & 1.47e-05 & 32/182 \\
Regulation Of Stress Fiber Assembly (GO:0051492) & 1.51e-05 & 19/75 \\
Regulation Of GTPase Activity (GO:0043087) & 1.51e-05 & 36/214 \\
Response To Interferon-Alpha (GO:0035455) & 1.51e-05 & 9/17 \\
Organelle Organization (GO:0006996) & 1.52e-05 & 57/418 \\
Regulation Of NIK/NF-kappaB Signaling (GO:1901222) & 1.79e-05 & 20/83 \\
PDZ Domain Binding (GO:0030165) & 1.86e-05 & 17/62 \\
Cytoplasmic Vesicle Membrane (GO:0030659) & 1.87e-05 & 53/389 \\
Lytic Vacuole (GO:0000323) & 1.87e-05 & 36/223 \\
Positive Regulation Of Binding (GO:0051099) & 2.02e-05 & 21/91 \\
Protein Localization (GO:0008104) & 2.03e-05 & 50/351 \\
Leukocyte Aggregation (GO:0070486) & 2.07e-05 & 6/7 \\
Endosome Membrane (GO:0010008) & 2.10e-05 & 50/361 \\
Nervous System Development (GO:0007399) & 2.12e-05 & 58/433 \\
Regulation Of Epithelial Cell Migration (GO:0010632) & 2.20e-05 & 15/50 \\
Positive Regulation Of Protein Tyrosine Kinase Activity (GO:0061098) & 2.22e-05 & 13/38 \\
Vesicle (GO:0031982) & 2.28e-05 & 37/235 \\
SARS-CoV-2 Infection R-HSA-9694516 & 2.49e-05 & 43/283 \\
mRNA Splicing - Major Pathway R-HSA-72163 & 2.49e-05 & 32/181 \\
RHOA GTPase Cycle R-HSA-8980692 & 2.49e-05 & 28/147 \\
Epithelial Cell Differentiation (GO:0030855) & 2.59e-05 & 26/132 \\
Signaling By WNT R-HSA-195721 & 2.75e-05 & 44/294 \\
Negative Regulation Of Protein Binding (GO:0032091) & 2.76e-05 & 18/71 \\
Calcium Ion Binding (GO:0005509) & 3.21e-05 & 49/346 \\
Cell-Cell Signaling By Wnt (GO:0198738) & 3.24e-05 & 10/23 \\
Positive Regulation Of Phosphorylation (GO:0042327) & 3.29e-05 & 37/231 \\
Regulation Of Programmed Cell Death (GO:0043067) & 3.52e-05 & 33/195 \\
Double-Stranded RNA Binding (GO:0003725) & 3.54e-05 & 17/65 \\
Regulation Of Small GTPase Mediated Signal Transduction (GO:0051056) & 3.57e-05 & 24/118 \\
Receptor Ligand Activity (GO:0048018) & 3.78e-05 & 46/319 \\
Receptor Tyrosine Kinase Binding (GO:0030971) & 3.97e-05 & 16/59 \\
Chordate Embryonic Development (GO:0043009) & 4.03e-05 & 16/59 \\
RAC2 GTPase Cycle R-HSA-9013404 & 4.31e-05 & 20/87 \\
GTPase Binding (GO:0051020) & 4.36e-05 & 36/225 \\
Endopeptidase Inhibitor Activity (GO:0004866) & 4.51e-05 & 23/112 \\
Regulation Of Vascular Endothelial Growth Factor Signaling Pathway (GO:1900746) & 4.52e-05 & 9/19 \\
Response To Interferon-Beta (GO:0035456) & 4.61e-05 & 11/29 \\
GDP Binding (GO:0019003) & 4.64e-05 & 17/67 \\
Small GTPase Binding (GO:0031267) & 4.71e-05 & 33/199 \\
Endocytosis (GO:0006897) & 4.82e-05 & 32/189 \\
RNA Splicing, Via Transesterification Reactions With Bulged Adenosine As Nucleophile (GO:0000377) & 4.82e-05 & 31/180 \\
Negative Regulation Of Peptidase Activity (GO:0010466) & 4.97e-05 & 16/60 \\
Insulin Receptor Signaling Pathway (GO:0008286) & 5.12e-05 & 14/47 \\
Heparan Sulfate/Heparin (HS-GAG) Metabolism R-HSA-1638091 & 5.32e-05 & 15/53 \\
Toll-like Receptor Cascades R-HSA-168898 & 5.32e-05 & 29/162 \\
Negative Regulation Of Proteolysis (GO:0045861) & 5.40e-05 & 13/41 \\
mRNA Splicing R-HSA-72172 & 5.40e-05 & 32/189 \\
Mesenchymal Cell Differentiation (GO:0048762) & 5.78e-05 & 15/54 \\
Protein K63-linked Ubiquitination (GO:0070534) & 5.78e-05 & 15/54 \\
Negative Regulators Of DDX58/IFIH1 Signaling R-HSA-936440 & 5.85e-05 & 12/35 \\
RAGE Receptor Binding (GO:0050786) & 6.00e-05 & 6/8 \\
Tertiary Granule (GO:0070820) & 6.41e-05 & 28/162 \\
Neuron Projection Development (GO:0031175) & 6.57e-05 & 32/192 \\
Regulation Of Epithelial To Mesenchymal Transition (GO:0010717) & 6.59e-05 & 19/83 \\
Negative Regulation Of DNA-templated Transcription (GO:0045892) & 6.59e-05 & 109/1025 \\
HS-GAG Biosynthesis R-HSA-2022928 & 7.16e-05 & 11/30 \\
Positive Regulation Of Autophagy (GO:0010508) & 7.39e-05 & 22/107 \\
Spliceosomal Complex Assembly (GO:0000245) & 7.52e-05 & 16/62 \\
Cell-Cell Adhesion Mediator Activity (GO:0098632) & 8.03e-05 & 13/43 \\
GTPase Regulator Activity (GO:0030695) & 8.03e-05 & 55/424 \\
Regulation Of Cytokine Production (GO:0001817) & 8.04e-05 & 29/167 \\
RHOB GTPase Cycle R-HSA-9013026 & 8.13e-05 & 17/69 \\
RAB Geranylgeranylation R-HSA-8873719 & 8.13e-05 & 16/62 \\
Protein Complex Oligomerization (GO:0051259) & 8.51e-05 & 21/100 \\
Defense Response To Bacterium (GO:0042742) & 8.62e-05 & 33/204 \\
MAPK signaling pathway & 8.69e-05 & 42/294 \\
Intermediate Filament Cytoskeleton (GO:0045111) & 8.75e-05 & 18/81 \\
GDP-dissociation Inhibitor Activity (GO:0005092) & 8.76e-05 & 7/12 \\
Response To Lipopolysaccharide (GO:0032496) & 8.77e-05 & 28/159 \\
Regulation Of Transmembrane Receptor Protein Serine/Threonine Kinase Signaling Pathway (GO:0090092) & 8.89e-05 & 11/31 \\
Positive Regulation Of Protein Localization (GO:1903829) & 8.96e-05 & 19/85 \\
Positive Regulation Of Canonical Wnt Signaling Pathway (GO:0090263) & 8.96e-05 & 19/85 \\
mRNA Processing (GO:0006397) & 8.96e-05 & 34/214 \\
Regulation Of Cell-Cell Adhesion (GO:0022407) & 8.96e-05 & 13/43 \\
Regulation Of Wnt Signaling Pathway (GO:0030111) & 9.52e-05 & 22/109 \\
Regulation Of Innate Immune Response (GO:0045088) & 9.80e-05 & 18/78 \\

In [24]:
list(go_df_filtered["Term"])

['Immune System R-HSA-168256',
 'Regulation Of Apoptotic Process (GO:0042981)',
 'Signal Transduction R-HSA-162582',
 'Cytokine Signaling In Immune System R-HSA-1280215',
 'Positive Regulation Of Intracellular Signal Transduction (GO:1902533)',
 'Regulation Of Cell Population Proliferation (GO:0042127)',
 'Defense Response To Virus (GO:0051607)',
 'Wnt Signaling Pathway (GO:0016055)',
 'Negative Regulation Of Cellular Process (GO:0048523)',
 'Innate Immune System R-HSA-168249',
 'Defense Response To Symbiont (GO:0140546)',
 'Collagen-Containing Extracellular Matrix (GO:0062023)',
 'Wnt signaling pathway',
 'Frizzled Binding (GO:0005109)',
 'Regulation Of I-kappaB kinase/NF-kappaB Signaling (GO:0043122)',
 'Negative Regulation Of Cell Population Proliferation (GO:0008285)',
 'Positive Regulation Of DNA-templated Transcription (GO:0045893)',
 'Proteoglycans in cancer',
 'Regulation Of Cell Migration (GO:0030334)',
 'Canonical Wnt Signaling Pathway (GO:0060070)',
 'Basal cell carcinoma',
 'Interferon Signaling R-HSA-913531',
 'Positive Regulation Of Cellular Process (GO:0048522)',
 'Negative Regulation Of Cell Migration (GO:0030336)',
 'Interferon Alpha/Beta Signaling R-HSA-909733',
 'Cell-Substrate Junction (GO:0030055)',
 'Regulation Of Cell Adhesion (GO:0030155)',
 'Negative Regulation Of Signal Transduction (GO:0009968)',
 'Negative Regulation Of Apoptotic Process (GO:0043066)',
 'Focal Adhesion (GO:0005925)',
 'Negative Regulation Of Viral Process (GO:0048525)',
 'Regulation Of Canonical Wnt Signaling Pathway (GO:0060828)',
 'RHO GTPase Cycle R-HSA-9012999',
 'Neutrophil Degranulation R-HSA-6798695',
 'Negative Regulation Of Programmed Cell Death (GO:0043069)',
 'Positive Regulation Of DNA-binding Transcription Factor Activity (GO:0051091)',
 'Signaling pathways regulating pluripotency of stem cells',
 'Hemostasis R-HSA-109582',
 'Positive Regulation Of I-kappaB kinase/NF-kappaB Signaling (GO:0043123)',
 'Protein Kinase Binding (GO:0019901)',
 'Positive Regulation Of Transcription By RNA Polymerase II (GO:0045944)',
 'Cell-Cell Junction (GO:0005911)',
 'Positive Regulation Of Response To External Stimulus (GO:0032103)',
 'Bounding Membrane Of Organelle (GO:0098588)',
 'Protein Localization To Membrane (GO:0072657)',
 'Signaling By Rho GTPases, Miro GTPases And RHOBTB3 R-HSA-9716542',
 'Hippo signaling pathway',
 'Negative Regulation Of Viral Genome Replication (GO:0045071)',
 'Regulation Of Gene Expression (GO:0010468)',
 'Positive Regulation Of Apoptotic Process (GO:0043065)',
 'Signaling By Rho GTPases R-HSA-194315',
 'G Protein-Coupled Receptor Binding (GO:0001664)',
 'Neuron Differentiation (GO:0030182)',
 'Positive Regulation Of Cell Population Proliferation (GO:0008284)',
 'Positive Regulation Of Cytokine Production (GO:0001819)',
 'Positive Regulation Of Programmed Cell Death (GO:0043068)',
 'Negative Regulation Of Multicellular Organismal Process (GO:0051241)',
 'Negative Regulation Of Intracellular Signal Transduction (GO:1902532)',
 'Extracellular Matrix Organization R-HSA-1474244',
 'Cellular Response To Cytokine Stimulus (GO:0071345)',
 'Extracellular Matrix Disassembly (GO:0022617)',
 'Protein Polyubiquitination (GO:0000209)',
 'RNA Binding (GO:0003723)',
 'Negative Regulation Of Cell Adhesion (GO:0007162)',
 'Regulation Of Viral Genome Replication (GO:0045069)',
 'Non-Canonical Wnt Signaling Pathway (GO:0035567)',
 'Cellular Component Disassembly (GO:0022411)',
 'Negative Regulation Of ERK1 And ERK2 Cascade (GO:0070373)',
 'Interferon Gamma Signaling R-HSA-877300',
 'Supramolecular Fiber Organization (GO:0097435)',
 'Secretory Granule Membrane (GO:0030667)',
 'Ribonucleoside Triphosphate Phosphatase Activity (GO:0017111)',
 'Signaling By Receptor Tyrosine Kinases R-HSA-9006934',
 'Cellular Response To Transforming Growth Factor Beta Stimulus (GO:0071560)',
 'Positive Regulation Of Cell Differentiation (GO:0045597)',
 'WNT Ligand Biogenesis And Trafficking R-HSA-3238698',
 'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
 'GTPase Activity (GO:0003924)',
 'Ubiquitin-Protein Transferase Activity (GO:0004842)',
 'Regulation Of Epithelial Cell Proliferation (GO:0050678)',
 'Positive Regulation Of Gene Expression (GO:0010628)',
 'Negative Regulation Of Wnt Signaling Pathway (GO:0030178)',
 'Regulation Of Interferon-Beta Production (GO:0032648)',
 'Negative Regulation Of Cell Motility (GO:2000146)',
 'Positive Regulation Of Multicellular Organismal Process (GO:0051240)',
 'Ubiquitin-Like Protein Ligase Binding (GO:0044389)',
 'mTOR signaling pathway',
 'Positive Regulation Of Macromolecule Metabolic Process (GO:0010604)',
 'Response To Molecule Of Bacterial Origin (GO:0002237)',
 'Metal Ion Binding (GO:0046872)',
 'Negative Regulation Of Hydrolase Activity (GO:0051346)',
 'Actin Cytoskeleton (GO:0015629)',
 'Guanyl Ribonucleotide Binding (GO:0032561)',
 'Positive Regulation Of Type I Interferon Production (GO:0032481)',
 'Positive Regulation Of Defense Response (GO:0031349)',
 'Epithelium Development (GO:0060429)',
 'Ubiquitin Protein Ligase Binding (GO:0031625)',
 'Regulation Of ERK1 And ERK2 Cascade (GO:0070372)',
 'Regulation Of Protein Binding (GO:0043393)',
 'Positive Regulation Of Nucleic Acid-Templated Transcription (GO:1903508)',
 'Positive Regulation Of Cell Migration (GO:0030335)',
 'Negative Regulation Of MAPK Cascade (GO:0043409)',
 'Melanogenesis',
 'Positive Regulation Of Signal Transduction (GO:0009967)',
 'Class B/2 (Secretin Family Receptors) R-HSA-373080',
 'Positive Regulation Of Protein Phosphorylation (GO:0001934)',
 'Negative Regulation Of Canonical Wnt Signaling Pathway (GO:0090090)',
 'GTP Binding (GO:0005525)',
 'Adherens Junction (GO:0005912)',
 'Positive Regulation Of Protein Metabolic Process (GO:0051247)',
 'Protein Modification Process (GO:0036211)',
 'Generation Of Neurons (GO:0048699)',
 'Signaling By Interleukins R-HSA-449147',
 'Membrane Raft (GO:0045121)',
 'Protein Homodimerization Activity (GO:0042803)',
 'Negative Regulation Of Protein Phosphorylation (GO:0001933)',
 'Keratinocyte Differentiation (GO:0030216)',
 'Negative Regulation Of Cell Differentiation (GO:0045596)',
 'RNA Splicing (GO:0008380)',
 'Protein Tyrosine Kinase Binding (GO:1990782)',
 'Kinase Binding (GO:0019900)',
 'Integrin-Mediated Signaling Pathway (GO:0007229)',
 'Cellular Response To Insulin Stimulus (GO:0032869)',
 'Wnt Receptor Activity (GO:0042813)',
 'Negative Regulation Of Epithelial Cell Migration (GO:0010633)',
 'Protein Ubiquitination (GO:0016567)',
 'Regulation Of mRNA Splicing, Via Spliceosome (GO:0048024)',
 'Positive Regulation Of Epithelial Cell Proliferation (GO:0050679)',
 'Ubiquitin-Dependent Protein Catabolic Process (GO:0006511)',
 'Gastric cancer',
 'Heart Development (GO:0007507)',
 'Transmembrane Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169)',
 'Skin Development (GO:0043588)',
 'Regulation Of Endothelial Cell Migration (GO:0010594)',
 'Sema4D In Semaphorin Signaling R-HSA-400685',
 'Sema4D Induced Cell Migration And Growth-Cone Collapse R-HSA-416572',
 'Regulation Of JNK Cascade (GO:0046328)',
 'Positive Regulation Of Innate Immune Response (GO:0045089)',
 'Regulation Of Intracellular Signal Transduction (GO:1902531)',
 'Positive Regulation Of Inflammatory Response (GO:0050729)',
 'Negative Regulation Of Epithelial Cell Proliferation (GO:0050680)',
 'Negative Regulation Of Gene Expression (GO:0010629)',
 'Modification-Dependent Protein Catabolic Process (GO:0019941)',
 'Negative Regulation Of GTPase Activity (GO:0034260)',
 'Regulation Of Epidermal Growth Factor Receptor Signaling Pathway (GO:0042058)',
 'Antiviral Innate Immune Response (GO:0140374)',
 'Regulation Of Cell Growth (GO:0001558)',
 'mRNA Binding (GO:0003729)',
 'Cytoskeleton (GO:0005856)',
 'Secretory Granule Lumen (GO:0034774)',
 'Positive Regulation Of Response To Biotic Stimulus (GO:0002833)',
 'Breast cancer',
 'Regulation Of Protein Phosphorylation (GO:0001932)',
 'Positive Regulation Of Interferon-Beta Production (GO:0032728)',
 'Transmembrane Receptor Protein Serine/Threonine Kinase Signaling Pathway (GO:0007178)',
 'Regulation Of Inflammatory Response (GO:0050727)',
 'Regulation Of Angiogenesis (GO:0045765)',
 'Regulation of actin cytoskeleton',
 'Hepatocellular carcinoma',
 'Human papillomavirus infection',
 'Response To Cytokine (GO:0034097)',
 'Gland Development (GO:0048732)',
 'Skeletal System Development (GO:0001501)',
 'RNA Processing (GO:0006396)',
 'Protein Localization To Cell Periphery (GO:1990778)',
 'Endocytic Vesicle (GO:0030139)',
 'Degradation Of Extracellular Matrix R-HSA-1474228',
 'RHOG GTPase Cycle R-HSA-9013408',
 'Regulation Of Viral Entry Into Host Cell (GO:0046596)',
 'mRNA Splicing, Via Spliceosome (GO:0000398)',
 'Golgi Membrane (GO:0000139)',
 'Golgi Lumen (GO:0005796)',
 'Positive Regulation Of Cell Motility (GO:2000147)',
 'Protein K48-linked Ubiquitination (GO:0070936)',
 'Ubiquitin-Like Protein Transferase Activity (GO:0019787)',
 'Protein Localization To Plasma Membrane (GO:0072659)',
 'Negative Regulation Of Mitotic Cell Cycle (GO:0045930)',
 'Regulation Of Cytoskeleton Organization (GO:0051493)',
 'Amyloid Fibril Formation (GO:1990000)',
 'Positive Regulation Of Cellular Catabolic Process (GO:0031331)',
 'Peptidyl-Tyrosine Dephosphorylation (GO:0035335)',
 'Glycosaminoglycan Metabolism R-HSA-1630316',
 'Positive Regulation Of Protein Catabolic Process (GO:0045732)',
 'Endosomal Transport (GO:0016197)',
 'Cellular Response To Growth Factor Stimulus (GO:0071363)',
 'Specific Granule (GO:0042581)',
 'Intracellular Non-Membrane-Bounded Organelle (GO:0043232)',
 'RAC1 GTPase Cycle R-HSA-9013149',
 'Early Endosome (GO:0005769)',
 'Wnt Signaling Pathway Involved In Midbrain Dopaminergic Neuron Differentiation (GO:1904953)',
 'Cadherin Binding (GO:0045296)',
 'Negative Regulation Of Binding (GO:0051100)',
 'Semaphorin Interactions R-HSA-373755',
 'Positive Regulation Of Wnt Signaling Pathway (GO:0030177)',
 'Lysosome (GO:0005764)',
 'Class I MHC Mediated Antigen Processing And Presentation R-HSA-983169',
 'RAC3 GTPase Cycle R-HSA-9013423',
 'Protease Binding (GO:0002020)',
 'Response To Lipid (GO:0033993)',
 'Actin-Based Cell Projection (GO:0098858)',
 'Positive Regulation Of Cell Projection Organization (GO:0031346)',
 'Non-integrin membrane-ECM Interactions R-HSA-3000171',
 'RHOC GTPase Cycle R-HSA-9013106',
 'Epidermal Cell Differentiation (GO:0009913)',
 'Cell Surface Interactions At Vascular Wall R-HSA-202733',
 'Positive Regulation Of NF-kappaB Transcription Factor Activity (GO:0051092)',
 'Wnt Signaling Pathway, Planar Cell Polarity Pathway (GO:0060071)',
 'Axon guidance',
 'Regulation Of Stress Fiber Assembly (GO:0051492)',
 'Regulation Of GTPase Activity (GO:0043087)',
 'Response To Interferon-Alpha (GO:0035455)',
 'Organelle Organization (GO:0006996)',
 'Regulation Of NIK/NF-kappaB Signaling (GO:1901222)',
 'PDZ Domain Binding (GO:0030165)',
 'Cytoplasmic Vesicle Membrane (GO:0030659)',
 'Lytic Vacuole (GO:0000323)',
 'Positive Regulation Of Binding (GO:0051099)',
 'Protein Localization (GO:0008104)',
 'Leukocyte Aggregation (GO:0070486)',
 'Endosome Membrane (GO:0010008)',
 'Nervous System Development (GO:0007399)',
 'Regulation Of Epithelial Cell Migration (GO:0010632)',
 'Positive Regulation Of Protein Tyrosine Kinase Activity (GO:0061098)',
 'Vesicle (GO:0031982)',
 'SARS-CoV-2 Infection R-HSA-9694516',
 'mRNA Splicing - Major Pathway R-HSA-72163',
 'RHOA GTPase Cycle R-HSA-8980692',
 'Epithelial Cell Differentiation (GO:0030855)',
 'Signaling By WNT R-HSA-195721',
 'Negative Regulation Of Protein Binding (GO:0032091)',
 'Calcium Ion Binding (GO:0005509)',
 'Cell-Cell Signaling By Wnt (GO:0198738)',
 'Positive Regulation Of Phosphorylation (GO:0042327)',
 'Regulation Of Programmed Cell Death (GO:0043067)',
 'Double-Stranded RNA Binding (GO:0003725)',
 'Regulation Of Small GTPase Mediated Signal Transduction (GO:0051056)',
 'Receptor Ligand Activity (GO:0048018)',
 'Receptor Tyrosine Kinase Binding (GO:0030971)',
 'Chordate Embryonic Development (GO:0043009)',
 'RAC2 GTPase Cycle R-HSA-9013404',
 'GTPase Binding (GO:0051020)',
 'Endopeptidase Inhibitor Activity (GO:0004866)',
 'Regulation Of Vascular Endothelial Growth Factor Signaling Pathway (GO:1900746)',
 'Response To Interferon-Beta (GO:0035456)',
 'GDP Binding (GO:0019003)',
 'Small GTPase Binding (GO:0031267)',
 'Endocytosis (GO:0006897)',
 'RNA Splicing, Via Transesterification Reactions With Bulged Adenosine As Nucleophile (GO:0000377)',
 'Negative Regulation Of Peptidase Activity (GO:0010466)',
 'Insulin Receptor Signaling Pathway (GO:0008286)',
 'Heparan Sulfate/Heparin (HS-GAG) Metabolism R-HSA-1638091',
 'Toll-like Receptor Cascades R-HSA-168898',
 'Negative Regulation Of Proteolysis (GO:0045861)',
 'mRNA Splicing R-HSA-72172',
 'Mesenchymal Cell Differentiation (GO:0048762)',
 'Protein K63-linked Ubiquitination (GO:0070534)',
 'Negative Regulators Of DDX58/IFIH1 Signaling R-HSA-936440',
 'RAGE Receptor Binding (GO:0050786)',
 'Tertiary Granule (GO:0070820)',
 'Neuron Projection Development (GO:0031175)',
 'Regulation Of Epithelial To Mesenchymal Transition (GO:0010717)',
 'Negative Regulation Of DNA-templated Transcription (GO:0045892)',
 'HS-GAG Biosynthesis R-HSA-2022928',
 'Positive Regulation Of Autophagy (GO:0010508)',
 'Spliceosomal Complex Assembly (GO:0000245)',
 'Cell-Cell Adhesion Mediator Activity (GO:0098632)',
 'GTPase Regulator Activity (GO:0030695)',
 'Regulation Of Cytokine Production (GO:0001817)',
 'RHOB GTPase Cycle R-HSA-9013026',
 'RAB Geranylgeranylation R-HSA-8873719',
 'Protein Complex Oligomerization (GO:0051259)',
 'Defense Response To Bacterium (GO:0042742)',
 'MAPK signaling pathway',
 'Intermediate Filament Cytoskeleton (GO:0045111)',
 'GDP-dissociation Inhibitor Activity (GO:0005092)',
 'Response To Lipopolysaccharide (GO:0032496)',
 'Regulation Of Transmembrane Receptor Protein Serine/Threonine Kinase Signaling Pathway (GO:0090092)',
 'Positive Regulation Of Protein Localization (GO:1903829)',
 'Positive Regulation Of Canonical Wnt Signaling Pathway (GO:0090263)',
 'mRNA Processing (GO:0006397)',
 'Regulation Of Cell-Cell Adhesion (GO:0022407)',
 'Regulation Of Wnt Signaling Pathway (GO:0030111)',
 'Regulation Of Innate Immune Response (GO:0045088)',
 'Regulation Of Interferon-Alpha Production (GO:0032647)',
 'Positive Regulation Of Interferon-Alpha Production (GO:0032727)',
 'ECM-receptor interaction',
 'Positive Regulation Of Macroautophagy (GO:0016239)',
 'Pathways in cancer',
 'Negative Regulation Of Transmembrane Receptor Protein Serine/Threonine Kinase Signaling Pathway (GO:0090101)',
 'Regulation Of Substrate Adhesion-Dependent Cell Spreading (GO:1900024)',
 'Glycosaminoglycan Biosynthetic Process (GO:0006024)',
 'Cellular Response To Lipid (GO:0071396)',
 'Apoptotic Process (GO:0006915)',
 'Glycosaminoglycan biosynthesis',
 'Wound Healing (GO:0042060)',
 'Cell Surface Receptor Signaling Pathway Involved In Cell-Cell Signaling (GO:1905114)',
 'Protein Binding Involved In Heterotypic Cell-Cell Adhesion (GO:0086080)',
 'Actin Binding (GO:0003779)',
 'Spliceosome',
 'Cellular Response To dsRNA (GO:0071359)',
 'Negative Regulation Of Endopeptidase Activity (GO:0010951)',
 'Regulation Of Proteolysis (GO:0030162)',
 'Positive Regulation Of Epidermal Growth Factor Receptor Signaling Pathway (GO:0045742)',
 'Regulation Of Type I Interferon-Mediated Signaling Pathway (GO:0060338)',
 'Positive Regulation Of Proteolysis (GO:0045862)',
 'Muscle Cell Migration (GO:0014812)',
 'Ubiquitin Protein Ligase Activity (GO:0061630)',
 'Regulation Of Signal Transduction (GO:0009966)',
 'Clathrin-Coated Endocytic Vesicle (GO:0045334)',
 'Regulation Of Protein Catabolic Process (GO:0042176)',
 'SARS-CoV Infections R-HSA-9679506',
 'Response To Chemokine (GO:1990868)',
 'Regulation Of mRNA Catabolic Process (GO:0061013)',
 'Activation Of Matrix Metalloproteinases R-HSA-1592389',
 'Adaptive Immune System R-HSA-1280218',
 'Pigment Granule (GO:0048770)',
 'Extracellular Matrix Organization (GO:0030198)',
 'Endothelial Cell Migration (GO:0043542)',
 'Circulatory System Development (GO:0072359)',
 'Regulation Of BMP Signaling Pathway (GO:0030510)',
 'Embryonic Skeletal System Development (GO:0048706)',
 'Dissolution Of Fibrin Clot R-HSA-75205',
 'Defective EXT1 Causes Exostoses 1, TRPS2 And CHDS R-HSA-3656253',
 'NOD-like receptor signaling pathway',
 'Toll Like Receptor 4 (TLR4) Cascade R-HSA-166016',
 'CDC42 GTPase Cycle R-HSA-9013148',
 'Regulation Of Nuclear-Transcribed mRNA Catabolic Process, Deadenylation-Dependent Decay (GO:1900151)',
 'Cytosolic Pattern Recognition Receptor Signaling Pathway (GO:0002753)',
 'Negative Regulation Of Cytokine Production (GO:0001818)',
 'Antiviral Mechanism By IFN-stimulated Genes R-HSA-1169410',
 'Cushing syndrome',
 'Positive Regulation Of Neuron Projection Development (GO:0010976)',
 'Cellular Response To Retinoic Acid (GO:0071300)',
 'Phagocytosis (GO:0006909)',
 'Maintenance Of Blood-Brain Barrier (GO:0035633)',
 'Regulation Of Establishment Of Planar Polarity (GO:0090175)',
 'Regulation Of mRNA Processing (GO:0050684)',
 'Dendrite Morphogenesis (GO:0048813)',
 "mRNA 3'-UTR Binding (GO:0003730)",
 'Melanosome (GO:0042470)',
 'Actin Filament Organization (GO:0007015)',
 'Microvillus (GO:0005902)',
 'Ubiquitin-Like Protein Ligase Activity (GO:0061659)',
 'Negative Regulation Of Nucleic Acid-Templated Transcription (GO:1903507)',
 'Positive Regulation Of Response To Cytokine Stimulus (GO:0060760)',
 'Cellular Response To Exogenous dsRNA (GO:0071360)',
 'Mammary Gland Epithelium Development (GO:0061180)',
 'Positive Regulation Of Cytoplasmic Translation (GO:2000767)',
 'Antigen Processing: Ubiquitination And Proteasome Degradation R-HSA-983168',
 'Secondary Alcohol Biosynthetic Process (GO:1902653)',
 'Regulation Of Heterotypic Cell-Cell Adhesion (GO:0034114)',
 'Negative Regulation Of Protein Modification Process (GO:0031400)',
 'Midbrain Dopaminergic Neuron Differentiation (GO:1904948)',
 'Ubiquitin mediated proteolysis',
 'Regulation Of Transforming Growth Factor Beta Receptor Signaling Pathway (GO:0017015)',
 'Cytoskeleton Organization (GO:0007010)',
 'G Alpha (12/13) Signaling Events R-HSA-416482',
 'Positive Regulation Of Catabolic Process (GO:0009896)',
 'Positive Regulation Of Epithelial Cell Migration (GO:0010634)',
 'Regulation Of Neuron Projection Development (GO:0010975)',
 'Positive Regulation Of Stress Fiber Assembly (GO:0051496)',
 'Phosphate-Containing Compound Metabolic Process (GO:0006796)',
 'Transforming Growth Factor Beta Receptor Signaling Pathway (GO:0007179)',
 'Response To Type II Interferon (GO:0034341)',
 'Inner Ear Morphogenesis (GO:0042472)',
 'Regulation Of Protein Ubiquitination (GO:0031396)',
 'Positive Regulation Of Signaling (GO:0023056)',
 'Cholesterol Biosynthetic Process (GO:0006695)',
 'Positive Regulation Of Cell Cycle (GO:0045787)',
 'Regulation Of Protein Localization To Cell Surface (GO:2000008)',
 'Regulation Of Macrophage Activation (GO:0043030)',
 'Negative Regulation Of Macromolecule Metabolic Process (GO:0010605)',
 'Cellular Response To Peptide Hormone Stimulus (GO:0071375)',
 'Regulation Of Lipase Activity (GO:0060191)',
 'Positive Regulation Of Cytokine-Mediated Signaling Pathway (GO:0001961)',
 'Intermediate Filament Bundle Assembly (GO:0045110)',
 'Regulation Of Response To Wounding (GO:1903034)',
 'Positive Regulation Of Vascular Endothelial Growth Factor Signaling Pathway (GO:1900748)',
 'Positive Regulation Of Neuron Projection Arborization (GO:0150012)',
 'Endothelial Cell Development (GO:0001885)',
 'Negative Regulation Of Viral Life Cycle (GO:1903901)',
 'trans-Golgi Network (GO:0005802)',
 'Neuron Development (GO:0048666)',
 'WW Domain Binding (GO:0050699)',
 'Response To Transforming Growth Factor Beta (GO:0071559)',
 'Ficolin-1-Rich Granule (GO:0101002)',
 'Cell-Cell Contact Zone (GO:0044291)',
 'Syndecan Interactions R-HSA-3000170',

In [25]:
list(go_df_filtered["Category"].unique())

["['Immune System']",
 "['biological regulation']",
 "['Signal Transduction']",
 "['response to stimulus', 'biological process involved in interspecies interaction between organisms']",
 "['biological regulation', 'cellular process']",
 '[]',
 "['Signal transduction']",
 "['binding']",
 "['Cancer: overview']",
 "['Cancer: specific types']",
 "['cellular anatomical structure']",
 "['Cellular community - eukaryotes']",
 "['Hemostasis']",
 "['localization', 'cellular process']",
 "['developmental process', 'cellular process']",
 "['Extracellular matrix organization']",
 "['response to stimulus']",
 "['cellular process']",
 "['catalytic activity']",
 "['developmental process']",
 "['Endocrine system']",
 "['response to stimulus', 'cellular process']",
 "['molecular transducer activity']",
 "['Developmental Biology']",
 "['response to stimulus', 'immune system process', 'biological process involved in interspecies interaction between organisms']",
 "['Cell motility']",
 "['Infectious disease: viral']",
 "['localization']",
 "['Metabolism']",
 "['Development and regeneration']",
 "['Disease']",
 "['Metabolism of RNA']",
 "['molecular function regulator activity', 'binding']",
 "['developmental process', 'multicellular organismal process']",
 "['molecular function regulator activity']",
 "['Metabolism of proteins']",
 "['Signaling molecules and interaction']",
 "['Transcription']",
 "['Immune system']",
 "['immune system process', 'biological regulation', 'cellular process']",
 "['Endocrine and metabolic disease']",
 "['homeostatic process', 'multicellular organismal process']",
 "['Folding, sorting and degradation']",
 "['protein-containing complex']"]